src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

add new version 0.0.4 for testing

update: add new version 0.0.4

---

src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

update to minor version for release

---

examples/FluentUIServerSample/Components/FluentTabsTest.razor

The tabs example was broken due to binding type mismatches. This caused the example to fail to render at runtime.
This change updates the bindings to use the right type values.
NA
NA

fix bindings for tabs example

---

src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

Bumping package to deliver design system improvements.

update to bump package

---

examples/FluentUIServerSample/Components/FluentDialogTest.razor
src/Microsoft.Fast.Components.FluentUI/Components/FluentDialog.razor

This is an implementation of `show` and `hide` from `fluent-dialog` component that fixes the issue #62.
My intention was to use the Javascript methods using `JSInterop`, but since you can't directly work in the DOM with Blazor, we would have to create a new Javascript file to hand the `show`/`hide` methods.
This implementation is pretty basic and it only adds a new property called `Hidden`, which will be used to update the `fluent-design` component.
There are two new methods added to the `FluentDialog` component called `Show` and `Hide`. 
```razor
<fluent-dialog Modal="@Modal" @attributes="AdditionalAttributes" hidden="@(Hidden)">@ChildContent</fluent-dialog>
@code
{
[Parameter] public bool? Modal { get; set; }
[Parameter] public RenderFragment ChildContent { get; set; } …
```

feat: add Show/Hide methods to FluentDialog

---

README.md
examples/FluentUIServerSample/App.razor
src/Microsoft.Fast.Components.FluentUI/FluentDesignSystemProvider.cs

This PR makes updates to align to @fluentui/web-components^1.0.0.
- The DesignSystemProvider component has had the "use-defaults" API removed because that is no-longer a feature of the `<fluent-design-system-provider>`. Default Design Token values are made available automatically to components.
- Removed the wrapping DesignSystemProvider from the examples section and removed parallel documentation from the README.md because wrapping the whole app in a DSP is no longer necessary.

update documentation and DSP to reflect changes made in fluent-ui v1

---

src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

This updates the package from `0.2.0` to `0.3.0` as required in order to run our package publishing process.

Update package to new minor version in preparation for release update

---

examples/FluentUIServerSample/Components/FluentToolbarTest.razor
examples/FluentUIServerSample/Pages/Webcomponents.razor
src/Microsoft.Fast.Components.FluentUI/Components/FluentToolbar.razor
src/Microsoft.Fast.Components.FluentUI/Orientation.cs

This PR adds a `<FluentToolbar>` component (and associated files) to wrap the `<fluent-toolbar>` web component
Besides the component itself (`FluentToolbar.razor`), pages have been added and modified to test the component. See the 'files changed' in this PR.
Visist the `FluentToolbarTest.razor` page to see several variations on using the toolbar.
Review and determine if functionality is sufficient/stuff is missing

Add <FluentToolbar>

---

examples/FluentUIServerSample/Components/FluentHorizontalScrollTest.razor
examples/FluentUIServerSample/Pages/Webcomponents.razor
src/Microsoft.Fast.Components.FluentUI/Components/FluentHorizontalScroll.razor

This PR adds a `<FluentHorizontalScroll>` component (and associated files) to wrap the `<fluent-horizontal-scroll>` web component
Besides the component itself (`FluentHorizontalScroll.razor`), pages have been added and modified to test the component. See the 'files changed' in this PR.
Visist the `FluentHorizontalScroll.razor` page to see several variations on using the toolbar.
Review and determine if functionality is sufficient/is missing

Add <FluentHorizontalScroll>

---

examples/FluentUI.Demo.Client/wwwroot/css/site.css
examples/FluentUI.Demo.Server/wwwroot/css/site.css
examples/FluentUI.Demo.Shared/Pages/ComponentBindings.razor

This PR adds fit-and-finish to the binding page.

adds fit-and-finish to binding page

---

CONTRIBUTING.md
README.md

Improves accuracy in documentation.
* Update references from previous project name to current project name
* Remove references to Migration docs which do not exist

Update documentation for better clarity and accuracy

---

examples/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
examples/FluentUI.Demo.Shared/FluentUI.Demo.Shared.csproj
src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

Updates the projects to use the final .NET 6 packages

Update to final .NET 6 NuGet packages and update version to 1.0.0.

---

README.md

Updating the readme to point to the official docs and provide a bit more example code.

doc(readme): update some content for release

---

README.md
src/Microsoft.Fast.Components.FluentUI/Appearance.cs
src/Microsoft.Fast.Components.FluentUI/Autocomplete.cs
src/Microsoft.Fast.Components.FluentUI/BindAttributes.cs
src/Microsoft.Fast.Components.FluentUI/Color.cs
src/Microsoft.Fast.Components.FluentUI/ColumnDefinition.cs
src/Microsoft.Fast.Components.FluentUI/Components/FluentCombobox.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/FluentListbox.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/FluentOption.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/FluentSelect.razor.cs
src/Microsoft.Fast.Components.FluentUI/DataGridCellType.cs
src/Microsoft.Fast.Components.FluentUI/DataGridRowType.cs
src/Microsoft.Fast.Components.FluentUI/Direction.cs
src/Microsoft.Fast.Components.FluentUI/EventHandlers.cs
src/Microsoft.Fast.Components.FluentUI/ExpandMode.cs
src/Microsoft.Fast.Components.FluentUI/FluentInputBase.cs
src/Microsoft.Fast.Components.FluentUI/FluentOptionContext.cs
src/Microsoft.Fast.Components.FluentUI/GenerateHeaderOptions.cs
src/Microsoft.Fast.Components.FluentUI/HorizontalPosition.cs
src/Microsoft.Fast.Components.FluentUI/LocalizationDirection.cs
src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj
src/Microsoft.Fast.Components.FluentUI/Orientation.cs
src/Microsoft.Fast.Components.FluentUI/Positioning.cs
src/Microsoft.Fast.Components.FluentUI/Resize.cs
src/Microsoft.Fast.Components.FluentUI/Scaling.cs
src/Microsoft.Fast.Components.FluentUI/Shape.cs
src/Microsoft.Fast.Components.FluentUI/TextFieldType.cs
src/Microsoft.Fast.Components.FluentUI/TooltipPosition.cs
src/Microsoft.Fast.Components.FluentUI/UpdateMode.cs
src/Microsoft.Fast.Components.FluentUI/VerticalPosition.cs

The title says it all. No functional chnges, just some more mordern .NET 6/c# 10 syntax
-
-
Nothing to test. No functional changes

Use c#10 namespace declaration style and enable Implicit usings

---

src/Microsoft.Fast.Components.FluentUI/Components/FluentDataGridCell.razor

Fix bug #149. The attributes attribute was missing an @ sign at the beginning
#149 
I've tested it with the sample code provided in the issue and verified it does show the expected output now.

Missing @ sign in attributes (fix #149)

---

src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

Updates to new minor version, to test the code signing with new certificate.

update release version

---

nuget.config

simple PR to update the nuget configuration file for details of new certificate used for code signing.

update nuget config

---

.azure-devops/cd-publish-templates.yml

New pipeline for publishing .NET templates.

add new automated publish for templates

---

examples/FluentUI.Demo.Shared/Pages/Lab/PresenceBadge/PresenceBadge.razor.cs

on some cultures, default tostring method has an issue for numeric types. so I changed it to use Invariant culture

Fix ToString for other culture

---

src/Microsoft.Fast.Components.FluentUI.Tests/Breadcrumb/BreadcrumbItemRenderShould.cs
src/Microsoft.Fast.Components.FluentUI.Tests/Breadcrumb/BreadcrumbRenderShould.cs
src/Microsoft.Fast.Components.FluentUI/Components/Breadcrumb/FluentBreadcrumb.razor.cs

- bUnit tests covering FluentBreadcrumbItem and FluentBreadcrum components
- the test cases checking the generated HTML
- no related issues
I raised a [question](https://github.com/microsoft/fast-blazor/discussions/287) regarding FluentBreadcrumb, but the answer there is not a dependency for this PR.

FluentBreadcrumbItem and FluentBreadcrumb bUnit render tests

---

Directory.Build.props
examples/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
examples/FluentUI.Demo.Generators/FluentUI.Demo.Generators.csproj
examples/FluentUI.Demo.Shared/Pages/ComponentBindings.razor
examples/FluentUI.Demo.Shared/Pages/DataGrid/DataGridPage.razor
examples/FluentUI.Demo.Shared/Pages/DataGrid/Examples/DataGridCustomPaging.razor
examples/FluentUI.Demo.Shared/Pages/DataGrid/Examples/DataGridCustomPaging.razor.css
examples/FluentUI.Demo.Shared/wwwroot/sources/DataGridCustomPaging.razor.css.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/DataGridCustomPaging.razor.txt
src/Microsoft.Fast.Components.FluentUI.Generators/Microsoft.Fast.Components.FluentUI.Generators.csproj
src/Microsoft.Fast.Components.FluentUI.Tests/Microsoft.Fast.Components.FluentUI.Tests.csproj
src/Microsoft.Fast.Components.FluentUI/Components/Checkbox/FluentCheckbox.razor
src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/FluentDataGrid.razor
src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/FluentDataGridRow.razor
src/Microsoft.Fast.Components.FluentUI/Components/NumberField/FluentNumberField.razor
src/Microsoft.Fast.Components.FluentUI/Components/Radio/FluentRadioGroup.razor
src/Microsoft.Fast.Components.FluentUI/Components/Slider/FluentSlider.razor
src/Microsoft.Fast.Components.FluentUI/Components/Switch/FluentSwitch.razor
src/Microsoft.Fast.Components.FluentUI/Events/EventHandlers.cs
src/Microsoft.Fast.Components.FluentUI/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js
src/Microsoft.Fast.Components.FluentUI/wwwroot/css/reboot.css

Fix #304 
Fix #298 
Backport to 1.6.1

Changes needed to fix #304 and #298

---

src/Microsoft.Fast.Components.FluentUI.Tests/Button/ButtonRenderShould.cs
src/Microsoft.Fast.Components.FluentUI.Tests/Calendar/CalendarRenderShould.cs

This PR contains fixes for the warnings I introduced in my #299 PR

Fix: warnings in Calendar and Button tests

---

src/Microsoft.Fast.Components.FluentUI.Tests/Checkbox/CheckboxRenderShould.cs

bUnit tests against FluentCheckbox
There is no related issue.
- the tests are covering parameters coming from base classes (FluentInputBase and FluentComponentBase)

tests: bunit render tests against FluentCheckbox

---

Directory.Build.props
README.md
WHATSNEW.md
examples/FluentUI.Demo.Shared/Pages/Combobox/Examples/ComboboxFromListOfOptions.razor
examples/FluentUI.Demo.Shared/Pages/Index/Index.razor
examples/FluentUI.Demo.Shared/wwwroot/sources/ComboboxFromListOfOptions.razor.txt
src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/Columns/ColumnBase.razor
src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcon.cs
src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcons.cs
src/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.csproj

Add more information to Readme, Add code to `FLuentIcons` to take icons used by library into account

Fix issue #333

---

examples/FluentUI.Demo.Shared/Pages/HorizontalScroll/Examples/HorizontalScrollExternalNavigation.razor
examples/FluentUI.Demo.Shared/Pages/HorizontalScroll/HorizontalScrollPage.razor
examples/FluentUI.Demo.Shared/wwwroot/sources/HorizontalScrollExternalNavigation.razor.txt
src/Microsoft.Fast.Components.FluentUI/Components/HorizontalScroll/FluentHorizontalScroll.razor
src/Microsoft.Fast.Components.FluentUI/Components/HorizontalScroll/FluentHorizontalScroll.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/HorizontalScroll/FluentHorizontalScroll.razor.js

I added wrappers of functions `scrollToPrevious`, `scrollToNext` and `scrollInView` in `<FluentHorizontalScroll>`
-
-
-
-

FluentHorizontalScroll - external navigation

---

src/Microsoft.Fast.Components.FluentUI/Components/Radio/FluentRadioGroup.razor.cs

Just fix a typo.🙈
- [-] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

Fix a typo

---

README.md

Replace https://aka.ms/fluentui-blazor with the new domain name https://www.fluentui-blazor.net even though we will all remember brave-cliff :)

Update README.md with new domain name

---

src/Microsoft.Fast.Components.FluentUI/Extensions/ServiceCollectionExtensions.cs

Fix issue #399

---

templates/README.md

Template _Short Name_ should be _fluentuiblazorwasm_ not _fluentuiBlazorWebAssembly_.

Update README.md due to incorrect template _Short Name_

---

examples/FluentUI.Demo.Shared/wwwroot/docs/WhatsNew.md

Minor correction to spelling.
Minor spelling errors.

Update WhatsNew.md - minor spelling corrections

---

examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
examples/FluentUI.Demo.Shared/Pages/NumberField/Examples/NumberFieldDefault.razor
examples/FluentUI.Demo.Shared/Pages/NumberField/Examples/NumberFieldFilled.razor
examples/FluentUI.Demo.Shared/Pages/Search/Examples/SearchAppearanceFilled.razor
examples/FluentUI.Demo.Shared/Pages/TextArea/Examples/TextAreaFilled.razor
examples/FluentUI.Demo.Shared/Pages/TextField/Examples/TextFieldFilled.razor
examples/FluentUI.Demo.Shared/Pages/Toolbar/Examples/ToolbarDefault.razor
examples/FluentUI.Demo.Shared/Pages/Toolbar/Examples/ToolbarSlotted.razor
examples/FluentUI.Demo.Shared/wwwroot/sources/NumberFieldDefault.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/NumberFieldFilled.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/SearchAppearanceFilled.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/TextAreaFilled.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/TextFieldFilled.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/ToolbarDefault.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/ToolbarSlotted.razor.txt
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Accent.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Hypertext.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Lightweight.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Neutral.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Stealth.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.cs
src/Microsoft.Fast.Components.FluentUI/Components/DateTime/FluentDatePicker.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/DateTime/FluentTimePicker.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/NumberField/FluentNumberField.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/Search/FluentSearch.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/TextArea/FluentTextArea.razor.cs
src/Microsoft.Fast.Components.FluentUI/Components/TextField/FluentTextField.razor.cs
src/Microsoft.Fast.Components.FluentUI/Enums/FluentInputAppearance.cs
src/Microsoft.Fast.Components.FluentUI/Extensions/DateTimeExtensions.cs

and apply to all impacted `FluentInput...` derived components

Rename TextFieldAppearance => FluentInputAppearance 

---

src/Microsoft.Fast.Components.FluentUI.Tests/DateTime/FluentDatePickerTests.cs
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameters.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_AutoFocusParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_ClassParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_DataListParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_Default.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_DisabledParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_HideStepParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_IdParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_MaxLengthParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_MaxParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_MinLengthParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_MinParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_NameParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_PlaceholderParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_ReadOnlyParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_RequiredParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_SizeParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_StepParameter.verified.html
src/Microsoft.Fast.Components.FluentUI.Tests/NumberField/FluentNumberFieldTests.FluentNumberField_StyleParameter.verified.html
src/Microsoft.Fast.Components.FluentUI/Components/DateTime/FluentDatePicker.razor
src/Microsoft.Fast.Components.FluentUI/Components/DateTime/FluentDatePicker.razor.cs

- Fix Calendar Unit Tests
- Fix Appearance property Unit Tests

Fix Calendar Unit Tests

---

templates/Projects/FluentUIBlazorServerApp/Pages/FetchData.razor

Unintentional change was made to FetchData.razor file for FluentUIBlazorServerApp template. This corrects the problem.
- broke the FluentUIBlazorServerApp template
@vnbaaij - only discovered the error with further testing.

Fixes FetchData.razor for FluentUIBlazorServerApp template

---

src/Microsoft.Fast.Components.FluentUI/Components/DesignSystemProvider/FluentDesignSystemProvider.razor

Fixed the missing `<style>` attribute in the fluent-design-system-provider component.

Fix: style doesn't work in fluent-design-system-provider

---

examples/FluentUI.Demo.Shared/wwwroot/sources/NavMenuDefault.razor.txt
examples/FluentUI.Demo.Shared/wwwroot/sources/ToastProgressToasts.razor.txt
src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.css

Move NavMenuGroup expand/collapse button to the right

---

.azure-devops/build-core-lib.yml
.azure-devops/common/template-to-build-projects.yml

Each time a PR to **new-components** or an update in **new-components** branch, the build pipeline will be automatically executed.
The Unit Tests project will be compiled and will be executed.

[Built Pipeline] Add Triggers and Unit Tests steps

---

examples/Demo/Shared/Pages/Dialog/Examples/DialogDefault.razor
examples/Demo/Shared/Pages/NavMenu/Examples/NavMenuCollapsible.razor
examples/Demo/Shared/Pages/NavMenu/Examples/NavMenuCustomActions.razor
examples/Demo/Shared/Pages/NavMenu/NavMenuPage.razor
src/Core/Components/NavMenu/FluentNavMenu.razor
src/Core/Components/NavMenu/FluentNavMenu.razor.cs
src/Core/Components/NavMenu/FluentNavMenuGroup.razor
src/Core/Components/NavMenu/FluentNavMenuGroup.razor.cs
src/Core/Components/NavMenu/FluentNavMenuItem.cs
src/Core/Components/NavMenu/FluentNavMenuItemBase.cs
src/Core/Components/NavMenu/FluentNavMenuLink.razor
src/Core/Components/NavMenu/FluentNavMenuLink.razor.cs
src/Core/Components/NavMenu/INavMenuChildElement.cs
src/Core/Components/NavMenu/INavMenuItemsOwner.cs
src/Core/Events/NavMenuActionArgs.cs

Allow nav menu items to have custom actions

---

examples/Demo/Shared/Pages/AnchoredRegion/Examples/AnchoredRegionAddToFixed.razor
src/Core/Components/AnchoredRegion/FluentAnchoredRegion.razor
src/Core/Components/AnchoredRegion/FluentAnchoredRegion.razor.cs
src/Core/Components/Menu/FluentMenu.razor.cs
src/Core/DesignTokens/Z-Index.cs

Apply ZIndex values to all existing components (to centralize and allow modifications)

Apply ZIndex const values

---

examples/Demo/Shared/Components/TableOfContents.razor.cs

Add a check to see if _jsModule is null

Check if_jsModule is null

---

src/Microsoft.Fast.Components.FluentUI/Components/Pagination/PaginationState.cs

Make SetTotalItemCountAsync in PaginationState public

---

src/Microsoft.Fast.Components.FluentUI/Components/Slider/FluentSlider.razor

This PR fix slider bugs below.
* Clicking on Readonly/Disabled slider sets CurrentValueAsString null
* Cannot change value by arrow key
* Cannot change value by drag and drop when dropped to outside of slider
Bugs can reproduce on https://www.fluentui-blazor.net/Slider (Version: 2.4.0+2ffef40afc9770676ea05ee3bf8a3db03484c23c)

Fix slider bugs

---

Directory.Build.props
examples/Demo/Shared/FluentUI.Demo.Shared.csproj
src/Core/Components/Radio/FluentRadioGroup.razor
src/Core/Events/EventHandlers.cs
src/Core/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js

Rename 'customclick' event to 'radiogroupclick'

Act on #566

---

unit-tests.md

- Add a markdown page with the documentation
- Add a link to a live demo: https://youtu.be/a5zkV8bUbLQ)

[Documentation] Add UnitTests markdown page

---

examples/Demo/Shared/Pages/Toast/Examples/ToastProgressToasts.razor
src/Core/Components/Progress/FluentProgress.razor.cs
src/Core/Components/Progress/FluentProgressRing.razor.cs
src/Core/Components/Toast/ContentComponents/ProgressToast.razor

FluentProgress: Add ValueChanged 
FluentProgressRing: Add ValueChanged 
Fix #655 and update example

ProgressToast related cahnges

---

.github/pull_request_template.md
README.md
examples/Demo/Shared/Components/DemoSection.razor
examples/Demo/Shared/Components/DemoSection.razor.cs
examples/Demo/Shared/Components/DemoSection.razor.css
examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
examples/Demo/Shared/Pages/CodeEditor/CodeEditorPage.razor
examples/Demo/Shared/Pages/Combobox/Examples/ComboboxDefault.razor
examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
examples/Demo/Shared/Pages/Listbox/Examples/ListboxSize.razor
examples/Demo/Shared/Pages/Listbox/ListboxPage.razor
examples/Demo/Shared/Pages/MessageBox/MessageBoxPage.razor
examples/Demo/Shared/Pages/Panel/PanelPage.razor
examples/Demo/Shared/Pages/Select/Examples/SelectDefault.razor
examples/Demo/Shared/Pages/Select/Examples/SelectLong.razor
examples/Demo/Shared/Pages/SplashScreen/SplashScreenPage.razor
examples/Demo/Shared/Pages/Toast/Examples/ToastProgressToasts.razor
examples/Demo/Shared/SampleData/DataSourceExtensions.cs
src/Core/Components/List/FluentCombobox.razor
src/Core/Components/List/FluentListbox.razor
src/Core/Components/List/FluentListbox.razor.cs
src/Core/Components/List/FluentSelect.razor
src/Core/Components/List/ListComponentBase.cs
src/Core/Components/Progress/FluentProgress.razor.cs
src/Core/Components/Progress/FluentProgressRing.razor.cs
src/Core/Components/Toast/ContentComponents/ProgressToast.razor
src/Core/DesignTokens/Z-Index.cs
unit-tests.md

Fix demo sections label, add colocated files where neede #662, fix and enhance ProgressToast example. Add unit test documentation

Fix demo sections label, add colocated files whe

---

examples/Demo/Client/wwwroot/index.html
examples/Demo/Server/Pages/_Layout.cshtml
examples/Demo/Shared/Pages/CodeEditor/CodeEditorPage.razor

Update demo sites entry pages for FluentCodeEditor FluentCodeEditor: update docs. Addresses #690

FluentCodeEditor: update docs

---

src/Templates/Projects/FluentUIBlazorServerApp/Program.cs

Add missing usings Project template

---

examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
src/Core/Components/DataGrid/FluentDataGridCell.razor.css

[fix] multiline-text word-break

---

examples/Demo/Shared/Components/NotificationCenter.razor
examples/Demo/Shared/Components/SiteSettings.razor
src/Core/Components/MenuButton/FluentMenuButton.razor
src/Core/Components/MenuButton/FluentMenuButton.razor.cs
src/Core/Components/MessageBar/FluentMessageBar.razor.cs

- Notification Center/Settings now use a button instead of just an icon
- FluentMenuButton: add ButtonStyle and MenyStyle parameters
- Fix FluentMessageBar timed message

Couple of enhancements

---

src/Core/Components/List/FluentOptionPeople.razor
src/Core/Components/List/FluentOptionPeople.razor.cs

Add an optional ´FluentOptionPeople.ChildContent` property to allow more customization.

[FluentOptionPeople] Add ChildContent

---

examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
src/Core/Components/DataGrid/FluentDataGrid.razor
src/Core/Components/DataGrid/FluentDataGridRow.razor.cs

-Add a column with buttons to virtualized grid example with sticky header 
-Update FluentDataGridRow to align center when row height is set 
-Update FluentDataGrid to remove code that was already done in row renderingUpdate FluentDataGridRow to align center when row height is set
Update FluentDataGrid to remove code that was already done in row rendering

Update FluentDataGridRow and example

---

SECURITY.md
examples/Demo/Shared/Pages/Autocomplete/Examples/AutocompleteCustomized.razor
src/Core/Components/DataGrid/FluentDataGridRow.razor.cs

Fixes some typos 'the the' => 'the'

Typo 'the the'

---

examples/Demo/Shared/Components/ApiDocumentation.razor.css
src/Core/Components/Dialog/FluentDialogProvider.razor.cs
src/Core/Components/Dialog/Parameters/DialogParameters.cs

For #782. 
Adds the option to prevent dismissing a modal dialog by clicking or touching the overlay.
It is implemented as an additional option and is a non-breaking change.
#782
Option name - **InertModalOverlay** is there a better name.

[WIP] Inert modal overlay

---

WHATSNEW.md
examples/Demo/Shared/Components/ApiDocumentation.razor
examples/Demo/Shared/Components/ApiDocumentation.razor.cs
examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
examples/Demo/Shared/Pages/Button/ButtonPage.razor
examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
examples/Demo/Shared/Pages/Drag/DragDropPage.razor
examples/Demo/Shared/Pages/Emoji/EmojiPage.razor
examples/Demo/Shared/Pages/Icon/IconPage.razor
examples/Demo/Shared/Pages/MessageBox/MessageBoxPage.razor
examples/Demo/Shared/Pages/NumberField/NumberFieldPage.razor
examples/Demo/Shared/Pages/Panel/PanelPage.razor
examples/Demo/Shared/Pages/Radio/RadioPage.razor
examples/Demo/Shared/Pages/RadioGroup/RadioGroupPage.razor
examples/Demo/Shared/Pages/Slider/SliderPage.razor
examples/Demo/Shared/wwwroot/docs/WhatsNew.md
src/Core/Components/DataGrid/Columns/ColumnBase.razor
src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
src/Core/Components/DataGrid/Columns/PropertyColumn.cs
src/Core/Components/DataGrid/FluentDataGrid.razor
src/Core/Components/DataGrid/FluentDataGrid.razor.cs
src/Core/Components/DataGrid/FluentDataGridRow.razor
src/Core/Components/DataGrid/FluentDataGridRow.razor.cs

Also cleaned up the What's New pages a bit by movig pre-v3 content to an archive page
Fix #787

Add a Tooltip parameter to DataGrid columns 

---

examples/Demo/Shared/Pages/DialogServicePage.razor

When you use `DialogService`, it will only take effect when not using Server Side Rendering.
FYI: https://github.com/microsoft/fluentui-blazor/blob/968a0ad400717843adec0358db13088aedc8ebd9/src/Core/Components/Dialog/FluentDialogProvider.razor.cs#L26-L35
https://github.com/microsoft/fluentui-blazor/blob/968a0ad400717843adec0358db13088aedc8ebd9/src/Core/Components/Dialog/FluentDialogProvider.razor.cs#L46-L58

fix: enhanced DialogService doc with asp.net core 8 with ssr

---

examples/Demo/Shared/Pages/Dialog/DialogPage.razor

Corrects minor typo on Dialog examples page
Minor typo

Corrects minor typo on Dialog examples page

---

src/Core/Components/DataGrid/FluentDataGrid.razor.js

Rapidly switching between pages with the data grid eventually causes a JavaScript error, which breaks Blazor.
Exit all of `init` if the passed in gridElement is null.
This change seems to fix the issue, but I haven't tested it. Someone should at least verify that the data grid still works merging.

Fix FluentDataGrid error if page is quickly exited

---

README.md

This is just a minor typo fix.

Fix README.md minor typo

---

src/Core/Components/DataGrid/FluentDataGrid.razor
src/Core/Components/DataGrid/FluentDataGrid.razor.cs

Fix #801 by removing  direct call to Items.Count()

---

src/Core/Components/List/FluentAutocomplete.razor.cs
src/Core/Components/List/FluentPersona.razor.cs

Minor documentation corrections.

Minor documentation corrections

---

tests/Core/Button/FluentButtonTests.FluentButton_Title.verified.razor.html

Fix a missing Unit Test:
```csharp
var cut = Render(@<FluentButton Title="My Title">My button</FluentButton>);
```
```html
xxxxxxxxxxxxxxxxxxxxx
<fluent-button type="button" aria-label="My Title" title="My Title" appearance="neutral">My button</fluent-button>
```

[Unit Tests] Fix Incorrect Unit Test

---

src/Core/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js

Just like the title states 
Fixes #875

Fix #875 typo in Microsoft.Fast.Components.FluentUI.lib.module.js

---

examples/Demo/DocGenerator/CodeCommentsGenerator.cs
examples/Demo/Shared/Components/ApiDocumentation.razor.cs

Description for parameters **Max** and **Min** are incorrect for [Number Field](https://www.fluentui-blazor.net/NumberField).
The description for **Max** should _Gets or sets the maximum value_ and **Min**  should be _Gets or sets the minimum value_.

Fixes partial matching of property names

---

examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
src/Core/Components/Base/FluentInputBase.cs
src/Core/Components/Checkbox/FluentCheckbox.razor
src/Core/Components/DateTime/FluentTimePicker.razor
src/Core/Components/NumberField/FluentNumberField.razor
src/Core/Components/Radio/FluentRadio.razor
src/Core/Components/Radio/FluentRadio.razor.cs
src/Core/Components/Radio/FluentRadioGroup.razor
src/Core/Components/Search/FluentSearch.razor
src/Core/Components/Slider/FluentSlider.razor
src/Core/Components/Switch/FluentSwitch.razor
src/Core/Components/TextArea/FluentTextArea.razor
src/Core/Components/TextField/FluentTextField.razor
tests/Core/Checkbox/FluentCheckboxTests.cs
tests/Core/NumberField/FluentNumberFieldTests.cs
tests/Core/_ToDo/Radio/FluentRadioTests.cs

Updated `Readonly` properties to `ReadOnly` in `FluentInputBase` and `FluentRadio` components to correct naming convention, applying pascal case to adopt the second option.
#898 Consistency of casing for component attributes
Commits and Pull Requests marked as Breaking Change due to the possibility of project breakage.
It was not necessary to implement new test scenarios, since no new functionalities were added, but the existing ones were modified to adapt to the changes in the name of the properties.

fix!: Naming convention

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
tests/Core/Card/FluentCardTests.FluentCard_AdditionalCssClass.verified.html
tests/Core/Card/FluentCardTests.FluentCard_AdditionalParameter.verified.html
tests/Core/Card/FluentCardTests.FluentCard_AdditionalParameters.verified.html
tests/Core/Card/FluentCardTests.FluentCard_AdditionalStyle.verified.html
tests/Core/Card/FluentCardTests.FluentCard_Default.verified.html
tests/Core/Card/FluentCardTests.FluentCard_NotAreaRestricted.verified.html
tests/Core/Card/FluentCardTests.FluentCard_NotAreaRestricted_AdditionalStyle.verified.html

[FluentCard] Update Unit Tests

[FluentCard] Update Unit Tests

---

src/Core/Components/DateTime/FluentDatePicker.razor
tests/Core/DateTime/FluentDatePickerTests.FluentCalendar_DisabledDate.verified.html
tests/Core/DateTime/FluentDatePickerTests.cs

`DisabledDateFunc` wasn't used in the FluentDatePicker even though it supported the parameter. Therefor it wasn't possible to disable certain dates when using the FluentDatePicker.
No relevant issues
A unit test is included to demonstrate and verify the behavior.
No existing tests are affected. A new unit test was added.

Support DisabledDateFunc in FluentDatePicker

---

src/Core/wwwroot/Microsoft.FluentUI.AspNetCore.Components.lib.module.js
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ExternalLogin.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ForgotPassword.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Login.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/LoginWith2fa.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/LoginWithRecoveryCode.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Register.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ResendEmailConfirmation.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ResetPassword.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/App.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/NavMenu.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Program.Main.cs
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Program.cs
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css

Tested all permutations of interactivity/auth/all interactive
Made all pages (including auth) use Fluent components

New Templates

---

.azure-devops/common/template-to-build-projects.yml

Update the `template-to-build-projects.yml` file to include **Archive branches**.

[Azure DevOps] Update template-to-build-projects.yml

---

examples/Demo/Shared/Pages/Home/Home.razor

Update Home.razor 

---

examples/Demo/Shared/wwwroot/docs/CodeSetup.md

Just a typo fix
"aree" in place of "are" in https://www.fluentui-blazor.net/CodeSetup

Fix typo in CodeSetup.md

---

src/Core/Components/Pagination/FluentPaginator.razor

Assign a variable inherited from the `FluentComponentBase` class to the `FluentPaginator` component, to enable inline styles within the paginator tag.
#1070 
I don't know if a test case should be applied to check the assignment of the Style tag, or if it was already applied for the component from which it is inherited.
No test cases applied.
Nothing

fix: FluentPaginator inline styles

---

src/Core/Components/List/FluentListbox.razor.cs

Change listbox style: max-width -> width, max-height -> height

New PR to replace #1016 #v3

---

src/Core.Assets/src/Design/ThemeStorage.ts
src/Core/wwwroot/js/loading-theme.js

Check if **LocalStorage** is available (to avoid crash on some platforms)

[FluentDesignTheme] Check if LocalStorage is available

---

src/Core/Components/Overflow/FluentOverflow.razor.js

[FluentOverflow] Resize when a new element is included or excluded

---

src/Core/Components/List/FluentCombobox.razor

fix Combobox z-index stack order issue

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
src/Core/Components/MainLayout/FluentMainLayout.razor
src/Core/Components/MainLayout/FluentMainLayout.razor.cs
tests/Core/_ToDo/MainLayout/FluentMainLayoutTests.FluentMainLayout_Default.verified.html
tests/Core/_ToDo/MainLayout/FluentMainLayoutTests.cs

Add NavMenuWidth parameter to FluentMainLayout
Added NavMenuWith Parameter to FluentMainLayout component to have a desired menu width

Add NavMenuWidth parameter to FluentMainLayout

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
src/Core/Components/MainLayout/FluentMainLayout.razor.cs
src/Core/Components/Tabs/FluentTab.razor.cs
src/Core/Enums/TooltipPosition.cs

fix some typos

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
examples/Demo/Shared/Pages/Splitter/Examples/SplitterDefault.razor
src/Core.Assets/src/SplitPanels.ts

Fix #1245 by correcting the resize start point

Fix Splitter so it works in RTL mode as well #v3

---

src/Core/Components/NavMenu/FluentNavBase.cs

As suggested in the issue #1241

Add OnClick invoke to OnClickHandler

---

examples/Demo/Shared/Components/SiteSettingsPanel.razor
examples/Demo/Shared/Components/SiteSettingsPanel.razor.cs
src/Core/Components/Card/FluentCard.razor
src/Core/Components/Stack/FluentStack.razor
tests/Core/Card/FluentCardTests.FluentCard_Id.verified.html
tests/Core/Card/FluentCardTests.cs
tests/Core/_ToDo/Stack/FluentSlackTests.FluentStack_Id.verified.razor.html
tests/Core/_ToDo/Stack/FluentSlackTests.razor

- Card: Add Id parameter + tests 
- Stack: Add Id parameter + tests

Add Id parameters

---

src/Core/Components/Dialog/Services/DialogService.cs
src/Core/Components/Dialog/Services/IDialogService.cs

- **Performance Improvement**: Eliminating `async`/`await` can reduce a small amount of performance overhead, particularly in high-frequency call scenarios.
- **Code Clarity**: Directly returning `Task.CompletedTask` makes the purpose of the method clearer, enhancing readability.
- Fix some typos

Optimize Dialog CloseAsync Method 

---

src/Core/Components/Checkbox/FluentCheckbox.razor

Investigate checkbox issue

---

examples/Demo/Shared/Pages/TemplatesPage.razor
src/Templates/README.md

Simplifies template instructions.
I was reading all the documentation again looking for changes. I found that the installation instructions could be confusing to a new user. 
These are only suggested. Please reject if not appropriate.

Simplify template installation instructions

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeExample.razor
src/Core/Components/Accessibility/FluentKeyCode.razor.cs
src/Core/Components/Accessibility/FluentKeyCode.razor.js
src/Core/Components/Accessibility/FluentKeyCodeEventArgs.cs
tests/Core/List/FluentAutocompleteTests.cs

Add 2 new features:
1. `StopPropagation` attribute
2. `TargetId` property received by the `OnKeyDown` event.

[KeyCode] Add StopPropagation and TargetId [v3]

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
src/Core/Components/Tooltip/Services/ITooltipService.cs
src/Core/Components/Tooltip/Services/TooltipService.cs

To simplify the problem described on this page #1412, a new `TooltipService.Refresh` could be interesting.

[TooltipService] Add TooltipService.Refresh method [v3]

---

src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
src/Core/Components/DataGrid/Infrastructure/InternalGridContext.cs

Fix #1478 by creating new sequential ids for rows/cells per grid

Use specific ids for rows and cells

---

examples/Demo/Shared/Pages/NavMenu/NavMenuPage.razor

Minor grammatical corrections and rewording.
Suggestions only :)

Update NavMenuPage.razor - corrects grammar

---

README.md

Badges now link to the badge itself

nuget badge links to nuget

---

src/Core/Components/NavMenu/FluentNavLink.razor
tests/Core/NavMenu/FluentNavLinkTests.FluentNavLink_Id.verified.html
tests/Core/NavMenu/FluentNavLinkTests.cs

Render out Id for FluentNavLink + add test

---

src/Core/Components/DataGrid/FluentDataGrid.razor.js

Fix #1582 by adding pointercancel and pointerleave event listeners

Fix #1582 by adding pointercancel and pointerleave event listeners

---

examples/Demo/Shared/Pages/SortableList/SortableListPage.razor

Fix spelling and missing bracket on h2 element
N/A
N/A
N/A
N/A

Fix typo/spelling errors for Sortable List Page

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

The devcontainer definition in this project was from Dotnet 6 and no longer usable. This PR updates to the new format and updates to Dotnet 8. 
This is for the VSCode devcontainer feature.

Update devcontainer to Dotnet 8

---

Directory.Build.props
Directory.Packages.props
examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
src/Assets/FluentUI.Emojis/Microsoft.FluentUI.AspNetCore.Components.Emoji.csproj
src/Assets/FluentUI.Icons/Microsoft.FluentUI.AspNetCore.Components.Icons.csproj
src/Core/Components/Icons/CoreIcons.cs
src/Core/Components/Overflow/FluentOverflow.razor.cs
src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
src/Extensions/DataGrid.EntityFrameworkAdapter/Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter.csproj

Make the necessary changes to fix #1530 and generate snupkg packages.
The sourcelink link is already set up correctly as can be seen from this screenshot (from the 4.5.0 nupkg)

Add required .csproj settings for generating snupkg packages

---

src/Core/DesignTokens/SwatchExtensions.cs

Just adding a simple extension method. See #1690 and #1688 for backstory

Add Swatch ToColorHex extension

---

examples/Demo/Shared/Pages/TemplatesPage.razor

Corrects spelling and grammar in templates page.
Spelling and grammar

Corrects spelling and grammar in templates page

---

examples/Demo/Shared/Pages/Home/Home.razor

- formatting issue with codesnippets
- spelling and grammar
Mostly aesthetic issues, and some spelling and grammar.
I did multiple commits in case you wish to reject any specific change.

[Demo & docs] Home page cleanup

---

src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/BlazorWeb-CSharp.Client.csproj
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Pages/Error.razor
src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css
src/Templates/content/ComponentsWebAssembly-CSharp/wwwroot/css/app.css

Title says it all. Nothing more, nothing less
- Template CSS fixes.
- Use specific package versions.

[Templates] CSS fixes and use specific package versions

---

src/Core/Components/Pagination/FluentPaginator.razor.cs

Fixes minor spelling mistake in an XML comment in the FluentPaginator.razor.cs class.

fix: spelling issue in FluentPaginator.razor.cs

---

examples/Demo/Shared/Shared/DemoMainLayout.razor
examples/Demo/Shared/wwwroot/css/site.css

Fix the Profile Menu position, in Mobile mode.
#1831

[Demo & Docs] Fix the Profile Menu position

---

src/Core/Components/Badge/FluentBadge.razor
tests/Core/Badge/FluentBadgeTests.FluentBadge_AppearanceAttribute-Accent.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_AppearanceAttribute-Lightweight.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_AppearanceAttribute-Neutral.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_CircularAttribute.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_ColorAttribute.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_DefaultAttributes.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_FillAttribute.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_WithAdditionalCssClass.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_WithAdditionalStyle.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_WithAnAdditionalAttribute.verified.html
tests/Core/Badge/FluentBadgeTests.FluentBadge_WithMultipleAdditionalAttributes.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html

Fix #1749 by not using a div (block element) in an inline element. See the discussion in the referenced issue

Fix #1749 by not using a div (block element) in an inline element

---

src/Core/Components/Wizard/FluentWizardStep.razor.css

[Wizard RTL] Fix the Wizard Left position, in RTL mode

---

examples/Demo/Shared/Pages/ProjectSetup.razor

Fix Typo in PageTitle "Project Serup" -> "Project Setup"
See title

[Demo] Fix Page Title typo - Project Setup

---

examples/Demo/Shared/wwwroot/docs/DesignTokens.md

Fixes minor typo in DesignTokens.md
- typo error

[Doc] Fixes minor typo in DesignTokens.md

---

src/Core/Components/DataGrid/FluentDataGrid.razor.js

fixes an issue where an exception is thrown when opening the col options
#2108 
N/A
can be checked by opening the demo and clicking on the country column filter
None

[DataGrid] : check datagrid's rowelements when correcting column options

---

examples/Demo/Shared/Pages/DialogServicePage.razor
examples/Demo/Shared/wwwroot/css/site.css

Cleanup of DialogService page on demo site.
- clean up formatting of code snippets
- fix empahasis
- remove trailing line following last paragraph in a `blockquote`
Primarily aesthetic changes.
Only change that has an application with impact is the formatting of the last paragraph within a block quote. It was done as a separate commit in case it's not acceptable.

[Demo] Cleanup DialogService Page

---

examples/Demo/Shared/Pages/MessageBar/MessageBarPage.razor
examples/Demo/Shared/Pages/MessageServicePage.razor
examples/Demo/Shared/Pages/ToastServicePage.razor

Cleans up more code snippets. 
- sample code formatted incorrectly or with extraneous spacing
- Changes were for primarily aesthetic purposes.
- Follows pattern used in #2171

[Demo]  Cleans up more code snippets

---

src/Core/Components/Dialog/ContentComponents/RenderFragmentDialog.razor
src/Core/Components/Dialog/Services/DialogService-Dialog.cs

- Add standard namespace
- Remove unnecessary using

[Misc] Code cleanup work

---

examples/Demo/Shared/Pages/TemplatesPage.razor

Minor changes to Template page.
- added spaces between screen shots
- minor rewording
- fix grammar
- as stated above
Some of the changes are subjective. Reject if not appropriate.

[Demo] Minor changes to Template page

---

src/Core/Components/Splitter/FluentMultiSplitter.razor.css

I removed the unnecessary semicolons
It now looks more natural.

[MultiSplitter] Prevent semicolons from being displayed.

---

examples/Demo/Shared/Shared/DemoNavProvider.cs

[Docs] Improve API documentation menu button

---

examples/Demo/Shared/Pages/Lab/IssueTester.razor
src/Core/Components/List/FluentCombobox.razor
src/Core/Components/List/FluentListbox.razor
src/Core/Components/List/FluentSelect.razor
tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Name.verified.razor.html
tests/Core/List/FluentAutocompleteTests.razor
tests/Core/List/FluentComboboxTests.FluentCombobox_NameAttribute.verified.html
tests/Core/List/FluentComboboxTests.cs
tests/Core/List/FluentListboxTests.FluentListbox_NameAttribute.verified.razor.html
tests/Core/List/FluentListboxTests.razor
tests/Core/List/FluentSelectTests.FluentSelect_NameAttribute.verified.razor.html
tests/Core/List/FluentSelectTests.razor
tests/Core/Slider/FluentSliderTests.FluentSlider_Double.verified.razor.html

Pass the `Name` parameter to the name attribute of the web components. This is needed to enable SSR scenarios

[Lists] Pass `Name` parameter

---

README.md
examples/Demo/Shared/Pages/Home/Home.razor
examples/Demo/Shared/Shared/DemoMainLayout.razor
examples/Demo/Shared/wwwroot/css/site.css

[Docs] Better column distribution for homepage

---

src/Core/Components/List/ListComponentBase.razor.cs

#2382 by letting value follow newly selected option

[Select] Fix logic when setting new option

---

examples/Demo/Shared/wwwroot/docs/WhatsNew.md

Fixes a broken link to a GitHub PR
I've checked the entire file for double `(`. Was the only occurence.

[Docs] Fix broken GitHub link

---

src/Core/Components/Dialog/Services/DialogService-SplashScreen.cs

Set Modal to parameters value (instead of always false). This was done earlier in PR #2398 but I forgot one 🤦‍♂️

[SplashScreen] Pass parameters.Modal to ShowSplashScreen... methods

---

examples/Demo/Shared/Pages/TemplatesPage.razor

[Docs] Fix typo in TemplatesPage.razor

---

src/Core/Components/List/FluentAutocomplete.razor

The `@attributes="AdditionalAttributes"` attribute has been omitted.
Fix #2520

[Autocomplete] Add missing AdditionalAttributes

---

examples/Demo/FluentUI.Demo.Client/Documentation/Components/Icon/Examples/IconDefault.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/Icon/FluentIcon.md
examples/Demo/FluentUI.Demo.Client/Documentation/Components/Icon/IconColorTable.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/Icon/IconExplorer.razor
examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Version5.md
examples/Demo/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor
examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.css
spelling.dic
src/Core/Components/Icons/Icon.cs
src/Core/Enums/Color.cs
src/Core/Extensions/EnumExtensions.cs
tests/Core/Components/Icons/FluentIconTests.FluentIcon_Icon_ToMarkup.verified.razor.html
tests/Core/Components/Icons/FluentIconTests.FluentIcon_Icon_ToMarkupColor.verified.razor.html
tests/Core/Components/Icons/FluentIconTests.FluentIcon_Icon_ToMarkupSize.verified.razor.html
tests/Core/Components/Icons/FluentIconTests.razor
tests/Core/Extensions/EnumExtensionsTests.cs

Update the Colors and the Documentation

[dev-v5] Update FluentIcon

---

.github/workflows/build-core-lib.yml

[dev-v5] Fix the Code Coverage task

---

.github/workflows/build-core-lib.yml

Add net8.0 coverage file to ReportGenerator

[dev-v5] Enhance Code Coverage Task

---

examples/Demo/FluentUI.Demo/Components/App.razor

Update the RenderMode for the Demo  Website
```csharp
var DemoRenderMode = new InteractiveWebAssemblyRenderMode(false);
```

[dev-v5] Update the Rendermode

---

examples/Demo/Shared/Components/CodeSnippet.razor.cs
examples/Demo/Shared/Components/CodeSnippet.razor.js
examples/Demo/Shared/Components/MarkdownSection.razor.js

Sometimes, the `hljs` highlightjs object is not yet instantiated. This PR will test the existence of this object to avoid application crashes.
See #2589

[Doc] Fix missing hljs object

---

Directory.Packages.props
src/Core.Scripts/Microsoft.FluentUI.AspNetCore.Components.Scripts.esproj

And also update VS JS SDK version

[dev-v5] Update to .NET 9 RC1

---

Directory.Packages.props
src/Core.Assets/Microsoft.FluentUI.AspNetCore.Components.Assets.esproj

- Update to .NET 9 RC1 SDK
- Update VS JS SDK
_We need tot do this for `dev-v5` branch as well_

[General] Update .NET 9 SDK

---

src/Core/Components/Label/FluentLabel.razor

Add the missing `Id` attribute

[Label] Add FluentLabel.Id

---

examples/Demo/Shared/Pages/Grid/Examples/GridDefault.razor

Removes unnecessary output to conole when viewing https://www.fluentui-blazor.net/Grid.
- clutter in console output
- aesthetic change
-

[Docs] Removes unnecessary output to console for Grid page

---

src/Core/Components/Menu/FluentMenuProvider.razor.cs

Fix #2761 Add z-index to MenuProvider to fix issue that surfaced in Aspire Dashboard

[Menu] Add z-index to MenuProvider

---

examples/Demo/Shared/Pages/TemplatesPage.razor

Removes extra period.
- typo
-

[Docs] Removes extra period from TemplatesPage.razor

---

src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/Index.razor

Title says it all. Fixes #2799

[Templates] Fix typo 'paceholder'

---

src/Core/Components/DataGrid/FluentDataGrid.razor.js

Fix #2836 by changing resize logic in RTL mode

[DataGrid] Fix resize in RTL mode

---

examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Migration/MigrationFluentButton.md
examples/Demo/FluentUI.Demo/Program.cs
examples/Demo/FluentUI.Demo/wwwroot/app.css
src/Core/wwwroot/css/reboot.css

- Add `reboot.css` to the core lib and include in `app.css`
- Use .NET 9 Static Assets code. Use #if to include correct code for 8/9

[dev-v5] Miscellaneous changes

---

examples/Demo/Shared/Pages/Home/Home.razor

fix a typo in https://www.fluentui-blazor.net/

fix a typo in the demo's home page

---

src/Core/Components/Accordion/FluentAccordionItem.razor.css

[Accordion] Fix RTL specific styling

---

README.md

Add Contributors with contrib.rocks

---

examples/Demo/FluentUI.Demo.Client/Documentation/Components/Lab/Examples/Test.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/Lab/Experiments.md
examples/Demo/FluentUI.Demo.Client/Documentation/Components/TextInput/Examples/TextInputPrefixSuffix.razor
examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Migration/MigrationGeneral.md
examples/Demo/FluentUI.Demo.Client/Documentation/Home.md
examples/Demo/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
src/Core/Components/Base/FluentComponentBase.cs
src/Core/Components/Base/FluentInputBase.cs
src/Core/Components/Base/FluentInputImmediateBase.cs
src/Core/Components/Base/FluentJSModule.cs
src/Core/Components/Base/IFluentComponentBase.cs
src/Core/Components/Grid/FluentGrid.razor.cs
src/Core/Components/TextInput/FluentTextInput.razor
src/Core/Components/TextInput/FluentTextInput.razor.cs
tests/Core/Components/Base/ComponentBaseTests.cs

[DRAFT] [dev-v5] Use standard `InputBase` class

---

src/Core/Components/Wizard/FluentWizard.razor.cs

This PR fixes an issue of the validation behavior of GoToNextStepAsync(int, true) in FluentWizard as described in #2939.
Fixes #2939

[Wizard] Fix validation within GoToNextStepAsync method

---

examples/Demo/Shared/Pages/TreeView/Examples/TreeViewDataBinding.razor

Fix #3034 by disabling checkboxes to make clear there is no real 2-way binding

[Docs] Fix TreeView example

---

docs/unit-tests.md

Fixes two typos in unit-tests.md

[Docs] [v5] Fix typos in unit-tests.md

---

examples/Tools/FluentUI.Demo.Generators/CodeCommentsGenerator.cs

Found an issue when attempting to build branch **dev-v5** after cloning it.
The `Microsoft.FluentUI.AspNetCore.Components.xml` file does not exist when this if first run. Thus there are no members to document.

[CodeCommentsGenerator] [v5] Fix initial build after first clone

---

src/Core/Components/DataGrid/FluentDataGrid.razor.js

Fix #3089 by changing a minmax value in the DataGrid script file.

[DataGrid] Make combination of ResizableColumns and AutoFit work

---

src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Ascending.verified.razor.html
tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Descending.verified.razor.html
tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Ascending.verified.razor.html
tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Descending.verified.razor.html
tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Customized_Rendering.verified.razor.html
tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Rendering.verified.razor.html
tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_SingleSelect_Rendering.verified.razor.html
tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_SingleStickySelect_Rendering.verified.razor.html
tests/Core/DataGrid/FluentDataGridTests.FluentDataGrid_Default.verified.razor.html

- Fix #3214 by applying the fix suggested in the issue comments
- Update tests
Images show RTL situation but same goes for LTR

[DataGrid] Fix popups being displays beneath header cells

---

src/Core/Components/Dialog/FluentDialogHeader.razor
tests/Core/Dialog/FluentDialogServiceTests.FluentDialogService_Default.verified.razor.html
tests/Core/Dialog/FluentDialogServiceTests.FluentDialogService_HeightUnset.verified.razor.html
tests/Core/Dialog/FluentDialogServiceTests.FluentDialog_RenderFragment.verified.razor.html

Only for the Customized Dialog box, the Close tooltip did not appear.
Fixed

Fix the Customized Dialog tooltip

---

src/Core/Components/Dialog/FluentDialogProvider.razor
src/Core/Extensions/EnumExtensions.cs
tests/Core/Components/Base/BaseHelpers.cs
tests/Core/Components/Base/ComponentBaseTests.cs
tests/Core/Components/Dialog/FluentDialogTests.razor
tests/Core/Components/Grid/FluentGridTests.razor
tests/Core/Components/Layout/FluentLayoutTests.razor
tests/Core/Components/Slack/FluentStackTests.razor
tests/Core/Components/TextInput/FluentTextInputTests.razor
tests/Core/Migration/AppearanceExtensionsTests.cs

Added some missing unit tests, to cover (including) `switch` fallback.
And to add some missing unit tests (e.g. `DialogOptions`)

[dev-v5] Add Unit Tests

---

examples/Tools/FluentUI.Demo.DocApiGen/Extensions/DocXmlReaderExtensions.cs
examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor
examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.css
examples/Tools/FluentUI.Demo.DocViewer/Extensions/ReflectionExtensions.cs
examples/Tools/FluentUI.Demo.DocViewer/Models/ApiClass.cs
examples/Tools/FluentUI.Demo.DocViewer/Models/ApiClassMember.cs

- Updated the XML documentation with `<see />' tags for Microsoft external links.
- Add a "star" symbol for properties that are directly linked to the component (not through inheritance).  
- Update the CSS to display the method description below the signature, to avoid overflow.

[dev-v5] Update documentation

---

examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor
examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor.cs
src/Core.Scripts/src/FluentUIWebComponents.ts
src/Core.Scripts/src/d-ts/Blazor.d.ts

This feature must be improved later, but with this button we can validate the Dark mode :-)

[dev-v5] Add Dark switcher 

---

examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.cs

[dev-v5] Update the API Generator
Add the "generic type" to document some API when the type is not string.
- `{{ API Type=FluentButton }}` -> No generic type => Already correct
- `{{ API Type=FluentTextInput }}` -> `string` generic type => Already correct
- `{{ API Type=FluentSlided }}` -> `int` generic type => NOT correct
This PR fixed this case using the syntaxt `{{ API Type=FluentSlided<int> }}`

[dev-v5] Update the API Generator

---

docs/unit-tests.md

Translate sentence into English about how to generate multiple tests when you use `[InlineData]`

Unit tests with InlineData

---

examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.css

Change code background-color to adapt to Dark mode

---

src/Core/Components/InputFile/FluentInputFile.razor

Add the missing `@attributes` parameter.
Issue #3440

[InputFile] Add @attributes

---

src/Core.Assets/src/index.ts

Fix #3528 
See the details in the issue report. Small & simple fix.

[NumberField] Add ::part(root) for invalid class

---

src/Core/Components/CounterBadge/FluentCounterBadge.razor
tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_WithAdditionalAttributes.verified.html
tests/Core/CounterBadge/FluentCounterBadgeTests.cs

`AdditionalAttributes` in `FluentCounterBadge` are ignored. This small PR applies them to the component.
Fixes #3541
A new component test needed to be added to check that these attributes appear.

{CounterBadge] Add support for additional attributes

---

Directory.Packages.props
examples/Demo/FluentUI.Demo.Client/_Imports.razor
src/Core/Components/Button/FluentAnchorButton.razor
src/Core/Components/Button/FluentAnchorButton.razor.cs
tests/Core/Components/AnchorButton/FluentAnchorButtonTests.FluentAchorButton_Label.verified.razor.html
tests/Core/Components/AnchorButton/FluentAnchorButtonTests.FluentAnchorButton_LabelChildContent.verified.razor.html
tests/Core/Components/AnchorButton/FluentAnchorButtonTests.razor

Also  add tests and update SDK and NuGet packages

[dev-v5] AnchorButton: Add Label parameter

---

examples/Demo/Shared/Components/Cookies/CookieConsent.razor
examples/Demo/Shared/Components/Cookies/CookieConsent.razor.css
examples/Demo/Shared/Pages/Home/Home.razor

Also 
- Add new version
- Reword versions block

[Docs] Make cookie consent responsive

---

src/Core/Components/Button/FluentAnchorButton.razor
tests/Core/Components/AnchorButton/FluentAnchorButtonTests.FluentAnchorButton_IconEndNoChildConten.verified.razor.html
tests/Core/Components/AnchorButton/FluentAnchorButtonTests.FluentAnchorButton_IconStartNoChildConten.verified.razor.html

- Take Label into account when rendering
- Update tests

[dev-v5] Update FluentAnchorButton

---

src/Core/Components/Overflow/FluentOverflow.razor.cs

Fix #3576 by adding `DynamicDependency` to `FluentOverFlow.razor.cs`

[General] Fix trimming error

---

src/Core/Components/List/FluentCombobox.razor.cs

Fix #3600 by using `InvokeAsync` in `ChangeHandlerAsync` (Aspire)
No tests affected.

[Combobox] Fix issue when used in Dialog

---

examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor

Only modifies demo code.
Fixes #3728 
It might be worth it to add some additional text documentation on this page indicating the importance of this attribute?

Fix missing `DisplayMode` attribute in `DataGridRemoteData.razor`

---

src/Core.Scripts/src/FluentUIWebComponents.ts
src/Core.Scripts/src/Startup.ts
src/Core.Scripts/src/Utilities/Theme.ts

- Creation of a separated `Theme.ts` class.
- Add a media query listener to update the attribute `data-theme` and `data-media` with the associated value.

[dev-v5] Refactoring Theme TS classes

---

src/Core/Components/List/ListComponentBase.razor.cs

Fix #3834 don't set internal value when using multiple.

---

examples/Demo/Shared/Pages/AppBar/Examples/AppBarClick.razor

[Docs] Fix typo in AppBar demo

---

src/Core/Components/DataGrid/FluentDataGrid.razor.cs

Forgot to remove a couple of lines while redoing the PR

[DataGrid] Add IsFixed parameter fix

---

src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
tests/Core/Components/Paginator/FluentPaginatorTests.FluentPaginator_SetItemsPerPage.verified.razor.html
tests/Core/Components/Paginator/FluentPaginatorTests.razor
tests/Core/Components/Paginator/PaginationStateTest.cs
tests/Core/Components/Paginator/TotalItemCountChangedEventArgsTest.cs

[dev-v5] Add tests for PaginationState and TotalItemCountChangedEventArgs

---

examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
examples/Demo/Shared/Pages/FluentComponentBasePage.razor

Fix #3982 by adding MultiLine to the DataGrid

[Docs] Componentbase page: Add MultiLine to DataGrid

---

src/Core/Components/MenuButton/FluentMenuButton.razor

Passes the `MenuButton`'s `Class` parameter to the underlaying `FluentButton`.

[MenuButton] Pass through Class

---

eng/pipelines/build-core-lib.yml

[Pipeline] Add PublishSymbols to core YAML

---

Microsoft.FluentUI-v5.sln
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/Calendar/FluentCalendar.md
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/DatePicker/Examples/DatePickerCulture.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/DatePicker/Examples/DatePickerDefault.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/DatePicker/Examples/DatePickerDoubleClickToDate.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/DatePicker/Examples/DatePickerRendering.razor
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DateTime/DatePicker/FluentDatePicker.md
src/Core/Components/DateTime/FluentCalendar.razor.cs
src/Core/Components/DateTime/FluentCalendar.razor.ts
src/Core/Components/DateTime/FluentDatePicker.razor
src/Core/Components/DateTime/FluentDatePicker.razor.cs
src/Core/Components/DateTime/FluentDatePicker.razor.css
src/Core/Components/Icons/CoreIcons.cs
src/Core/Components/Icons/FluentIcon.razor
src/Core/Components/Icons/FluentIcon.razor.cs
src/Core/Components/Layout/FluentLayout.razor.cs
src/Core/Components/Layout/FluentLayoutItem.razor.cs
src/Core/Enums/DatePickerRenderStyle.cs
src/Core/Enums/DatePickerRenderingMode.cs
src/Core/Enums/GridItemHidden.cs
src/Core/Enums/GridItemSize.cs
src/Core/Localization/LanguageResource.resx
tests/Core/Components/DateTimes/FluentCalendarTests.razor
tests/Core/Components/DateTimes/FluentDatePickerTests.FluentDatePicker_Default.verified.razor.html
tests/Core/Components/DateTimes/FluentDatePickerTests.razor
tests/Core/Components/DateTimes/Utilities/CultureShortestDay.cs

Picking a date can be tough without context. A date picker (DatePicker) offers a popup control that's optimized for picking a single date from a calendar view where contextual information like a disabled day or fullness of the calendar is important.
You can use the Culture parameter to display the month and day names in different languages; and to set the date format displayed in the input field.
The DatePicker can be displayed in different views: day, month, and year.
The user can switch between these views using the title item: the month name or the year number.
```xml
<FluentDatePicker Label="Days view" bind-Value="@SelectedValue" />
```
The DatePicker can be rendered in different modes: FluentUI, Browser.
The FluentUI rendering mode uses the Fluent UI styles and components. This mode …

[dev-v5] Add DatePicker

---

.config/tsaoptions.json

Update the TSA config file to the new internal repo

Update TSA config

---

examples/Demo/FluentUI.Demo.Client/Documentation/Components/DataGrid/FluentDataGrid.md
src/Core/Components/DataGrid/FluentDataGrid.razor
src/Core/Localization/LanguageResource.resx

[dev-v5[DataGrid] Add localization for EmptyContent

---

examples/Demo/FluentUI.Demo.Client/Documentation/Components/DataGrid/Pages/DataGridAutoFitPage.md
examples/Demo/FluentUI.Demo.Client/Documentation/Components/DataGrid/Pages/DataGridTypicalPage.md

Remove extra curly braces in DataGrid demo pages

---

examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor

Add `hidden-when="xs"` on extra content in the footer.
https://github.com/user-attachments/assets/466563d3-ce5c-4a79-984e-91f38dd93496
See #4193

[dev-v5] Layout with responsive foot

---

.config/tsaoptions.json

Update TSAOptions codebaseName

Update TSAOptions codebaseName

---

.config/tsaoptions.json
eng/pipelines/build-core-lib.yml

[dev-v5] Update MSFT pipelines

[dev-v5] Update MSFT pipelines

---

.github/workflows/codeql-analysis.yml

CodeQL - Update .NET SDK

---

.github/workflows/codeql-analysis.yml

[Internal] Update CodeQL
