- examples/FluentUIServerSample/Components/FluentRadioGroupTest.razor
The input type of Required is type bool. This caused the example to fail to load at runtime.
The previous binding was a binding the the string whose text was "true". This change updates it to use the bool value true.
NA
The Tabs example has a similar issue that I'll submit a PR for as well.
> fix radio group example input binding type

- README.md
- examples/FluentUIServerSample/App.razor
- examples/FluentUIServerSample/Pages/Webcomponents.razor
- examples/FluentUIServerSample/Pages/_Host.cshtml
- src/Microsoft.Fast.Components.FluentUI/FluentDesignSystemProvider.cs
This PR adds a `<FluentDesignSystemProvider>` component that wraps the `<fluent-design-system-provider>`. Documentation has been added to the readme file. The component is added to the `FluentUIServerSample` for testing and example usage  
This component was created to deliver a more Blazor-like experience when adding this library to a project. The component is added to the `App.razor` file to fulfill the general HTML wrapping requirement. `App.razor` is a more logical place in a Blazor project to do this than `_Host.cshtml` (or `index.html` in a WebAssemply app). 
When no attributes are supplied, the component automatically adds the `use-defaults` attribute. When attributes are supplied, these are outputted in the element and the `use-defaults` is omitted
Run the `FluentUIServerSample`. …
> Add <FluentDesignSystemProvider> wrapper

- examples/FluentUIServerSample/Components/FluentSwitchTest.razor
- examples/FluentUIServerSample/Components/FluentTreeItemTest.razor
- examples/FluentUIServerSample/Components/FluentTreeViewTest.razor
Fixed a bug where `Identifier 'darkTheme' has already been declared` was being thrown on the following components on the `Web Components` sample page:
- Switch
- Tree Item
- Tree View
#37 
The script doesn't actually need to be there as the darkMode toggle sets it to true when it's undefined. However, setting false beforehand gives more clarity when understanding where the "darkMode setting/variable" comes from.
On the `Web Components` sample page the following should not throw a 'declaration' error:
- Switch
- Tree Item
- Tree View
> fix: darkMode already declared on certain component test pages

- examples/FluentUIServerSample/Components/FluentTextFieldTest.razor
- src/Microsoft.Fast.Components.FluentUI/Components/FluentTextField.razor
- src/Microsoft.Fast.Components.FluentUI/TextFieldType.cs
Additions and changes to the FluentTextField component. 
- Rename parameter `Resize`  to `Size`. As per https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/text-field/text-field.spec.md a `FluentTextField` does not contain a `Resize` parameter (of type Resize?) but does contain a `Size` parameter (of type int?)
Add new parameters:
- MinLength (int?); the minimum number of characters long the input can be and still be considered valid
- MaxLength (int?);  the maximum number of characters the input should accept
- TextFieldType (TextFieldType? enum (text, email, password, tel, url))
- Spellcheck (bool?);controls whether or not to enable spell checking for the input field, or if the default spell checking configuration should be used 
Look at …
> FluentTextField changes and additions

- examples/FluentUIServerSample/Components/FluentTooltipTest.razor
- examples/FluentUIServerSample/Pages/Webcomponents.razor
- src/Microsoft.Fast.Components.FluentUI/Components/FluentTooltip.razor
- src/Microsoft.Fast.Components.FluentUI/TooltipPosition.cs
This PR adds a `<FluentTooltip>` component (and associated files) to wrap the `<fluent-tooltip>` web component
Besides the component itself (`FluentTooltip.razor`), pages have been added and modified to test the component. See the 'files changed' in this PR.
Visist the `FluentTooltipTest.razor` page to see several variations on using the grid.
Review and determine if functionality is sufficient/stuff is missing
> Adding <FluentTooltip>

- .github/workflows/ci-validate.yml
With `paths-ignore` set to `**.md` we can avoid running workflow for PR if there is just documentation file edited (markdown) and ultimately can save resources.
> chore (workflow) - Avoid running workflows for markdown

- examples/FluentUI.Demo.Shared/Pages/ListboxOptionPage.razor
I was testing the sample and I noticed that the page `ListBoxOption` was crashing. this is due to the component FluentOption should have an ancestor FluentSelect, FluentListBox or FluentComboBox, so I wraped all of the `FluentOption` into different `FluentSelect`
--
Nothing really, I just ran the code and went into the sample page
- [x ] I have tested my changes.
- [ x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.
I noticed that the option `Selected="true"` for a default value is not working, neither it does in FluentListBox or FluentComboBox; 
example:
```csharp
<FluentSelect>
<FluentOption>Option …
```
> fix the access to ListboxOptionPage

- README.md
1. For the blazor server project, we have `_Layout.cshtml` instead of `index.cshtml`.
> chore (docs) - Updated usage guidelines for blazor server project

- examples/FluentUI.Demo.Shared/Shared/MainLayout.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/FluentDesignSystemProvider.razor
The BaseLayerLuminance parameter in the FluentDesignSystemProvider was a culture related float value, which leads to the problem that browsers with a region that uses comma instead of dot for float/double values set the value with comma instead of dot in the html tag.
This leads to unexpected colours in Component.
Open the example page on a browser which is set to a region which uses comma instead of dot float/double values (German for example) and trigger the Light / Dark Toggle (I have set it from 0 to 0.2 to test it)!
> (Bug Fix) Base Layer Luminance was culture related

- examples/FluentUI.Demo.Shared/Pages/TreeViewPage.razor
This PR removes the extra Theme/Direction switches from the TreeViewPage
#160 
Nothing to test, just simple deletion of an extraneous `<div>`
> fix: bug #160

- examples/FluentUI.Demo.Shared/Pages/NumberFieldPage.razor
- examples/FluentUI.Demo.Shared/Pages/TextAreaPage.razor
- examples/FluentUI.Demo.Shared/Pages/TextFieldPage.razor
- src/Microsoft.Fast.Components.FluentUI/FluentInputBase.cs
Add FocusAsync methods to FluentInputBase and give examples in the TextField, NumberField and TextArea pages.
This PR exposes the ElementReference.FocusAsync() methods of the underlying element encapsulated by the FluentInputBase derived components. This makes it easier to programmatically set the focus on text based input fields.
closes #157
> feat: Add FocusAsync methods to FluentInputBase

- src/Microsoft.Fast.Components.FluentUI.Tests/Accordion/FluentAccordionItemShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Accordion/FluentAccordionShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Anchor/FluentAnchorRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/AnchoredRegion/FluentAnchoredRegionShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/FluentAnchor/FluentAnchorRenderShould.cs
- chore
- bUnit tests agains FluentAnchor and FluentAnchoredRegion components
- directory rename, so the test directories reflects on the components' directory names
- no related issue
- these tests cover only if the rendered HTML is good or not
- A test class covers a single component
- a test covering the default value case where the component attributes are not set up. This case ensures that if there is a change in the default values of the attributes we will be informed
- tests covering the generated HTML when attributes are set up
- where the input is an enum I created a Theory and all the enum values are exercised (probably overkill, but worth to try how painful manage this way and I do not expect changing these enums frequently)
- the capabilities provided by base class also …
> Fluent anchor bUnit tests

- src/Microsoft.Fast.Components.FluentUI.Tests/Accordion/FluentAccordionItemRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Accordion/FluentAccordionRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/AnchoredRegion/FluentAnchoredRegionRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Badge/FluentBadgeRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Microsoft.Fast.Components.FluentUI.Tests.csproj
bUnit tests covering FluentBadge component rendering, meaning we check if the HTML is valid generated by the Blazor component.
No related issues.
- I renamed previous tests files as they didn't have "Render" in their name
- the additional functionalities (dealing with extra style, css class and unmatched attributes) are exercised at component level
- Appearance input value is checked as the enum contains more value than the component supports (the enum itself is widely used across the components)
- I took the liberty and added FluentAssertions nuget package. I don't know what is the policy when it comes to an additional 3rd party package. If this package cannot be added, please let me know. I'll remove it and assert the exception in a different way.
Testing is not necessary here.
> tests: Fluent badge bunit tests

- src/Microsoft.Fast.Components.FluentUI.Tests/Button/ButtonRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Calendar/CalendarRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Calendar/FluentCalendar.razor.cs
bUnit tests against FluentButton and FluentCalendar components.
The tests check the HTML output of the components
- no relevant issue
- in case of both components the extras provided by FluentComponentBase are checked
- attributes are covered, in case of string null, empty and whitespace is checked
- in case of enum input all enum value is exercised
- in case of FluentCalendar the Month input is not validated, so I added a tests where `13` is the input to show that there is no validation here. I assume there are people checking the tests to understand how component works.
- [the xml doc of the button form target](https://github.com/microsoft/fast-blazor/blob/3f3b741b7602adb9c7ca67d762f86991eacb46bf/src/Microsoft.Fast.Components.FluentUI/Components/Button/FluentButton.razor.cs#L47) …
> FluentButton and FluentCalendar tests

- src/Microsoft.Fast.Components.FluentUI.Tests/Anchor/FluentAnchorRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Badge/FluentBadgeRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Breadcrumb/BreadcrumbItemRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI.Tests/Card/CardRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Anchor/FluentAnchor.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Breadcrumb/FluentBreadcrumbItem.razor.cs
This Pr contains the following changes:
- bunit render tests against FluentCard, the tests checking the rendered HTML
- Target parameter input validation for FluentAnchor and tests extended accordingly
- FluentBadge appearance input parameter validation tests
- Target parameter input validation for FluentBreadcrumbItem and tests extended accordingly
- there are no related issues
- I apologise in advance because I feel that this PR might be bigger/wider than it should be, I wanted to make these changes in one go
- in case of FluentAnchor and FluentBreadcrimbItem Target parameter validation I followed the pattern I found at other components, however I see the opportunity to extract Target possible values and use this common list across components
- the build of this PR will display warnings …
> fix: tests against FluentCard and other fixes

- src/Microsoft.Fast.Components.FluentUI.Tests/Checkbox/CheckboxRenderShould.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Base/FluentInputBase.cs
[v2.1.0](https://github.com/microsoft/fast-blazor/releases/tag/V2.1.0) brought the `bind-Value` to the components using [FluentInputBase](https://github.com/microsoft/fast-blazor/blob/main/src/Microsoft.Fast.Components.FluentUI/Components/Base/FluentInputBase.cs). As a result `class` attribute is always added to the generated HTML tag (see example below), which unnecessarily increases the HTML size. This PR brings a fix for that and as a result the `class` attribute in the HTML tag is displayed only when it has value.
The wrong result
```razor
<fluent-checkbox class="" value="" current-value="" current-checked="">
childContent
</fluent-checkbox>
```
The proper result
```razor
<fluent-checkbox value="" current-value="" current-checked="">
childContent
</fluent-checkbox>
```
- no relevant …
> fix: FluentCheckbox class tag always displayed

- src/Microsoft.Fast.Components.FluentUI/Components/Switch/FluentSwitch.razor
- src/Microsoft.Fast.Components.FluentUI/Events/EventHandlers.cs
- src/Microsoft.Fast.Components.FluentUI/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js
When clicking on label or on/off state the control change visually but the `Checked` property isn't updated.
It works correctly only if you click on the switch.
https://user-images.githubusercontent.com/8057670/226545368-d8ef6461-e483-4380-bcc4-5c6a0f785c44.mp4
https://user-images.githubusercontent.com/8057670/226545410-141112f5-8f88-4fcc-aba0-e0f58ce8799e.mp4
x
x
x
x
> Fix switch click on label and on/off state

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/FluentUI.Demo.Shared/Pages/Drag/DragDropPage.razor
- examples/FluentUI.Demo.Shared/Pages/Drag/Examples/DragDropBasic.razor
- examples/FluentUI.Demo.Shared/Shared/DemoNavMenuList.razor
- examples/FluentUI.Demo.Shared/Shared/DemoNavMenuTree.razor
- examples/FluentUI.Demo.Shared/wwwroot/sources/DragDropBasic.razor.txt
- src/Microsoft.Fast.Components.FluentUI.Tests/Drag/FluentDragTests.FluentDrag_SimpleTest.verified.html
- src/Microsoft.Fast.Components.FluentUI.Tests/Drag/FluentDragTests.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDragContainer.razor
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDragContainer.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDragEventArgs.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDropZone.razor
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDropZone.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Drag/FluentDropZone.razor.css
A web component implementation of a [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).
The user may select draggable elements with a mouse, drag those elements to a droppable element, and drop them by releasing the mouse button. A translucent representation of the draggable elements follows the pointer during the drag operation.
Add these components `FluentDragContainer` and `FluentDropZone`.
```razor
<FluentDragContainer TItem="string">
<FluentDropZone Draggable="true" Droppable="true">
Item 1
</FluentDropZone>
<FluentDropZone Draggable="true" Droppable="true">
Item 2
</FluentDropZone>
</FluentDragContainer>
```
> Add Drag and Drop components

- src/Microsoft.Fast.Components.FluentUI.Tests/Extensions/AdditionalAttributesExtensionsShould.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcon.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Icon/FluentIcons.cs
- src/Microsoft.Fast.Components.FluentUI/Extensions/AdditionalAttributesExtensions.cs
- reduced number of StaticAssetService.GetAsync calls in FluentIcon
- suppression of re-render if parameters haven't changed (when icon is in RenderFragment)
- dedicated dictionary instead of array is used for icon availability check
#370
> Fix #370 - FluentIcon performance improvements

- templates/Projects/FluentUIBlazorServerApp/FluentUIBlazorServerApp.csproj
- templates/Projects/FluentUIBlazorServerApp/Pages/FetchData.razor
- templates/Projects/FluentUIBlazorWebAssemblyApp/FluentUIBlazorWebAssemblyApp.csproj
- templates/Projects/FluentUIBlazorWebAssemblyApp/Pages/FetchData.razor
When creating a new fluent ui wasm project, _FetchData.razor_ page generates nullable warnings on compile.
Warnings generated from code created from template.
``` powershell
Build started...
1>------ Build started: Project: fluentwasm, Configuration: Debug Any CPU ------
1>C:\git\fluentwasm\Pages\FetchData.razor(17,55,17,56): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(18,60,18,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(19,60,19,61): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(20,58,20,59): warning CS8602: Dereference of a possibly null reference.
1>C:\git\fluentwasm\Pages\FetchData.razor(25,41,25,50): warning CS8618: …
```
> Template updates

- src/Microsoft.Fast.Components.FluentUI/Components/DateTime/FluentTimePicker.razor.css
On mobile phones the placeholder is sometimes missing (e.g. iPhone). In this case the width of the DatePicker is very small.
This PR sets a min-width value to avoid this issue.
> Fix DatePicker min-width for mobile devices

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuLink.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuLink.razor.cs
I'd like to not have to use `<FluentIcon>` in my `FluentNavMenu` but use images instead.
This PR adds
*  FluentNavMenu.NavigationIconContent
*  FluentNavMenuLink.IconContent
*  FluentNavMenuGroup.CollapsedIconContent (NavMenu currently does not support this)
*  FluentNavMenuGroup.ExpandedIconContent
> Add NavigationIconContent to FluentNavMenu (Fixes #463)

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/FluentUI.Demo.Shared/Pages/DataGrid/Examples/DataGridCustomComparer.razor
- examples/FluentUI.Demo.Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- examples/FluentUI.Demo.Shared/Pages/Icon/IconPage.razor
- examples/FluentUI.Demo.Shared/Pages/Icon/IconPage.razor.cs
- examples/FluentUI.Demo.Shared/Pages/Search/Examples/SearchInteractive.razor
- examples/FluentUI.Demo.Shared/Pages/Search/Examples/SearchInteractiveWithDebounce.razor
- examples/FluentUI.Demo.Shared/Shared/DemoMainLayout.razor
- examples/FluentUI.Demo.Shared/Shared/DemoMainLayout.razor.cs
- examples/FluentUI.Demo.Shared/wwwroot/sources/DataGridCustomComparer.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/DataGridTypical.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/SearchInteractive.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/SearchInteractiveWithDebounce.razor.txt
- src/Microsoft.Fast.Components.FluentUI/Components/Base/FluentInputBase.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Base/FluentInputBaseHandlers.cs
- src/Microsoft.Fast.Components.FluentUI/Components/Checkbox/FluentCheckbox.razor
- src/Microsoft.Fast.Components.FluentUI/Components/Checkbox/FluentCheckbox.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NumberField/FluentNumberField.razor
- src/Microsoft.Fast.Components.FluentUI/Components/Search/FluentSearch.razor
- src/Microsoft.Fast.Components.FluentUI/Components/TextArea/FluentTextArea.razor
- src/Microsoft.Fast.Components.FluentUI/Components/TextField/FluentTextField.razor
1. Moved `CurrentValue` setter to `SetCurrentValue` method so event-driven attempts to set `CurrentValue` can await `ValueChanged` etc.
2. Moved `CurrentValueAsString` setter to a method for the same reason.
3. Added `AfterBindValue` event to circumvent a .Net 6 lack of `@bind-Value:after` that was introduced in .Net 7 - this ensures a consumer can execute code after a databound value has been updated.
4. Ensured all demos use `AfterBindValue`.
> Add AfterBindValue to FluentInputBase (Fixes #472)

- src/Microsoft.Fast.Components.FluentUI/Components/DataGrid/Columns/ColumnBase.razor
Filter icon button in column header is neccesarry for ColumnOptions popup.  
However, when `Align == Align.Center`, the button is missing.  
In such cases, QuickGrid places the button at the left side, so I have implemented the same behavior.
> Fix missing ColumnOptions button for 'Align.Center'

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/FluentUI.Demo.Shared/Pages/NavMenu/Examples/NavMenuCollapsible.razor
- examples/FluentUI.Demo.Shared/Pages/NavMenu/Examples/NavMenuCustomIconContent.razor
- examples/FluentUI.Demo.Shared/wwwroot/sources/NavMenuCollapsible.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/NavMenuCustomIconContent.razor.txt
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.css
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor.cs
> Prevent NavMenu group text overlapping its expand button

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/FluentUI.Demo.Shared/Pages/NavMenu/Examples/NavMenuCollapsible.razor
- examples/FluentUI.Demo.Shared/Pages/NavMenu/Examples/NavMenuCustomIconContent.razor
- examples/FluentUI.Demo.Shared/Shared/DemoMainLayout.razor.cs
- examples/FluentUI.Demo.Shared/wwwroot/docs/WhatsNew.md
- examples/FluentUI.Demo.Shared/wwwroot/sources/NavMenuCollapsible.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/NavMenuCustomIconContent.razor.txt
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenu.razor.css
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuGroup.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuLink.razor
- src/Microsoft.Fast.Components.FluentUI/Components/NavMenu/FluentNavMenuLink.razor.cs
NavMenu - Add rtl css, add IDisposable to components
fix#495
> Documentation updates NavMenu - Add rtl css, add IDisposable to components

- examples/FluentUI.Demo.Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewDataBinding.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewDefault.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewDisabledItem.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewFlat.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewNested.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewSelectedItem.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/Examples/TreeViewSomeExpanded.razor
- examples/FluentUI.Demo.Shared/Pages/TreeView/TreeViewPage.razor
- examples/FluentUI.Demo.Shared/wwwroot/sources/ApiDocumentation.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewDataBinding.razor.js.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewDataBinding.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewDisabledItem.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewFlat.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewNested.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewSelectedItem.razor.txt
- examples/FluentUI.Demo.Shared/wwwroot/sources/TreeViewSomeExpanded.razor.txt
- src/Microsoft.Fast.Components.FluentUI/Components/TreeView/FluentTreeItem.razor
- src/Microsoft.Fast.Components.FluentUI/Components/TreeView/FluentTreeItem.razor.cs
- src/Microsoft.Fast.Components.FluentUI/Components/TreeView/FluentTreeView.razor
- src/Microsoft.Fast.Components.FluentUI/Components/TreeView/FluentTreeView.razor.cs
- src/Microsoft.Fast.Components.FluentUI/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js
Fix #510
InitiallyExpanded
InitiallySelected
bind Expanded
bind Selected
> FluentTreeView add 2 way binding

- .github/workflows/cicd_publish.yml
- src/Core/Utilities/StyleBuilder.cs
Add a space after colon and semi-colon and trim any of those at the end of a generated CSS string
> Add spaces after colon and semi-colon. Trim them at the end

- src/Microsoft.Fast.Components.FluentUI/Components/DesignSystemProvider/FluentDesignSystemProvider.razor.cs
The units for these properties were incorrect and could not be applied even when values were set, due to the absence of measurement units: `px`. Therefore, it was decided to change their data type to string, allowing users to determine both the value and unit type as needed, while also maintaining consistency with the official FluentUI property types (ref: https://github.com/microsoft/fluentui/blob/57de08c18915440cdc54a1242bbdf948e2b0f562/packages/web-components/src/design-system-provider/index.ts#L426). 
For example, if the TypeRampMinus1FontSize property was assigned a value of float `12`, but did not include a unit such as "px" or "em", the value would not be applied correctly in the user interface. By changing the data type to string, users can now include the appropriate unit of …
> Fix: Lots of properties are not working in fluent-design-system-provider

- examples/Demo/Shared/Pages/Button/Examples/ButtonIcon.razor
Clarification of what you can do when using 'old' way of using icon in a button
> Extend FluentButton sample a bit

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- src/Core/Components/NavMenu/FluentNavMenuGroup.razor
- src/Core/Components/NavMenu/FluentNavMenuGroup.razor.cs
- src/Core/Events/EventHandlers.cs
- src/Core/Events/MouseWithTargetIdEventArgs.cs
- src/Core/Events/TargetIdMouseEventArgs.cs
- src/Core/wwwroot/Microsoft.Fast.Components.FluentUI.lib.module.js
> Allow click on group of collapsed nav menu to trigger its action

- src/Core/Components/Toast/FluentToast.razor
FluentToast does not pass the width correctly to the FluentIcon. This causes warnings in chrome, but works in chrome, and causes icons to be incorrectly sized on other platforms.
the PR fixes #593 
I looked into adding at least a default Testcase for the FluentToast, which isn't tested yet, but the ToastContext made it a bit hard and i had no idea how to make that work in a test case.
i did run the storybook/demo and verified it working correctly :)
n/a
n/a
> fix(toast): set FluentIcon width correctly

- src/Core/Components/List/FluentSelect.razor
My scenario is, that I have a Component with a `FluentSelect`, and I want to reset its value by clicking a button. But it's not updating the value, no matter what I tried. I think the `current-value` in the `FluentSelect` needs to be bound, so the current value is updated in the `FluentSelect`.
I've tried it with the `new-components` branch and it works. I could try to come up with a simplified test case for it.
The `FluentSelect` currently does not reset its value, when updating the bound value. I think the `current-value` on the Web Component needs to be set. This fixes the issue, so the currently selected value can be set.
- #266 
-
-
> Set current-value for FluentSelect

- examples/Demo/Shared/FluentUI.Demo.Shared.csproj
- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipDefault.razor
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipDelay.razor
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipLongExample.razor
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipVisible.razor
- examples/Demo/Shared/Pages/Tooltip/TooltipPage.razor
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- src/Core/Components/Tooltip/FluentTooltip.razor
- src/Core/Components/Tooltip/FluentTooltip.razor.cs
- src/Core/Components/Tooltip/FluentTooltipProvider.razor
- src/Core/Components/Tooltip/FluentTooltipProvider.razor.cs
- src/Core/Components/Tooltip/Services/ITooltipService.cs
- src/Core/Components/Tooltip/Services/TooltipGlobalOptions.cs
- src/Core/Components/Tooltip/Services/TooltipOptions.cs
- src/Core/Components/Tooltip/Services/TooltipService.cs
- src/Core/Extensions/ServiceCollectionExtensions.cs
- src/Core/Infrastructure/LibraryConfiguration.cs
- tests/Core/Tooltip/FluentTooltipTests.FluentTooltip_AllAttributes.verified.html
- tests/Core/Tooltip/FluentTooltipTests.FluentTooltip_Default.verified.html
- tests/Core/Tooltip/FluentTooltipTests.cs
With this provider, all Tooltip definitions will be generated with these global options and will be written at the end of the HTML page to support the different z-index levels.
In the `Program.cs`, inject the Tooltip service with global options. You can also use the `Services.AddFluentUIComponents` method to register all required FluentUI services, including this one.
```csharp
builder.Services.AddScoped<ITooltipService, TooltipService>();
```
At the end of your MainLayout.razor page, include the provider:
```xml
<FluentTooltipProvider />
```
```xml
<FluentIcon Id="myFirstButton" Icon="Icons.Regular.Size24.Notepad" />
<FluentTooltip Anchor="myFirstButton">
Hello World <br />
It is a <i>small</i> tootip.
</FluentTooltip>
```
> **note**: **There is NO Breaking Change**: if the …
> Tooltip Provider

- src/Core/Utilities/CssBuilder.cs
- src/Core/Utilities/StyleBuilder.cs
- src/Core/Utilities/ValueBuilder.cs
same as #615 but target new-components branch.
This ensures that StringBuilder field is not NULL. After testing several components, no problems were found.
> refactor: Optimize string handling capabilities

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- src/Core/Components/TextField/FluentTextField.razor.cs
- src/Core/Components/TextField/FluentTextField.razor.js
Following on from discussion #637:
Added a new property [AutoComplete](https://www.w3schools.com/TAgs/att_autocomplete.asp) (bool?) assigned to the input control.
This code is only applied when the **AutoComplete** and **Id** properties are set.
```javascript
export function setAutocomplete(id, value) {
const fieldElement = document.querySelector("#" + id)?.shadowRoot?.querySelector("#control");
if (!!fieldElement) {
fieldElement?.setAttribute("autocomplete", value);
}
}
```
> Add AutoComplete property to the TextField component

- src/Core/Components/Emojis/Emoji.cs
- src/Core/Components/Emojis/FluentEmoji.razor.cs
- src/Core/Components/Icons/FluentIcon.razor.cs
- src/Core/Components/Icons/Icon.cs
During the publishing phase of a WASM project, the Trimming feature is automatically activated by dotnet.
Previously, when using an **FluentIcon** without an object instance, the icon content was removed during the publishing.
With this PR, the `FluentIcon Icon="..." />` works and the icon content will not removed during the publishing phases.
> Fix Icons and Emojis trimmed during the WASM publishing

- examples/Demo/Shared/Pages/Overflow/Examples/OverflowHorizontalExample.razor
- src/Core/Components/Overflow/FluentOverflow.razor
- src/Core/Components/Tooltip/FluentTooltip.razor.cs
As described in issue #677, the overflow tooltip remains empty.
This PR update the FluentOverflow component to fix this issue.
> Fix the Tooltip used by the FluentOverflow

- src/Core/Components/TextField/FluentTextField.razor.cs
Set TextField.AutoComplete property to string type, to be compliant with W3C standards: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
#680
> Set TextField.AutoComplete property to string type

- src/Core/Components/NumberField/FluentNumberField.razor
- src/Core/Components/Search/FluentSearch.razor
- src/Core/Components/TextArea/FluentTextArea.razor
- src/Core/Components/TextField/FluentTextField.razor
Use the `oninput` attribute to apply the `Immediate` and `ImmediateDelay` properties.
These properties are only used with these components:
- FluentNumberField
- FluentTextField
- FluentSearch
- FluentTextArea
```xml
<FluentTextField @bind-Value="value1" Immediate="true" ImmediateDelay="500" />
<p>You entered: @value1</p>
```
> Apply the Immediate property to "text" components

- examples/Demo/Client/wwwroot/index.html
- examples/Demo/Server/Pages/_Layout.cshtml
- examples/Demo/Shared/Pages/CodeEditor/CodeEditorPage.razor
> Re-add scripts to index.html/_Layout.cshtml, Update docs

- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridCustomComparer.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
Solves issue #695 by adding a reference to rows' and cells' items.
> Add item reference to FluentDataGridRow and FluentDataGridCell (#695)

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/Demo/Shared/Pages/Dialog/DialogPage.razor
- examples/Demo/Shared/Pages/Dialog/Examples/DialogDefault.razor
- examples/Demo/Shared/Pages/Dialog/Examples/DialogServiceExample.razor
- examples/Demo/Shared/Pages/DialogServicePage.razor
- src/Core/Components/Dialog/FluentDialog.razor
- src/Core/Components/Dialog/FluentDialog.razor.cs
- src/Core/Components/Dialog/FluentDialog.razor.css
- src/Core/Components/Dialog/FluentDialogFooter.razor
- src/Core/Components/Dialog/FluentDialogFooter.razor.cs
- src/Core/Components/Dialog/FluentDialogFooter.razor.css
- src/Core/Components/Dialog/FluentDialogHeader.razor
- src/Core/Components/Dialog/FluentDialogHeader.razor.cs
- src/Core/Components/Dialog/FluentDialogHeader.razor.css
Add FluentDialogHeader, FluentDialogFooter components. Update documentation on how to use/override.
> Dialog enhancements

- src/Core/Components/DateTime/FluentDatePicker.razor
With this fix, the DatePicker popup area will be dynamically positioned **below or above** the component, depending on the available space.
> [FluentDatePicker] Update the popup position

- examples/Demo/Shared/Pages/Autocomplete/Examples/AutocompleteCustomized.razor
- src/Core/Components/Icons/CoreIcons.cs
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/ListComponentBase.cs
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.html
This PR update these 3 features:
1. The "right icon" is now a **Search** icon until a item is selected. In this case, the right icon becomes a **Dismiss** icon
2. When at least one element is selected, clicking on the **Dismiss** icon deletes the entire content of the text field.
3. Once an element has been searched, the **Placeholder** text is no longer displayed.
4. When the number of selected items equals the **MaximumSelectedOptions** value, the content `MaximumSelectedOptionsMessage` is displayed to indicate that the user cannot add any further items.
> [FluentAutocomplete] Update some usabilities

- src/Core/Components/DateTime/CalendarExtended.cs
- src/Core/Components/DateTime/FluentCalendar.razor
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
- src/Core/Components/DateTime/FluentTimePicker.razor.cs
- tests/Core/DateTime/FluentTimePickerTests.cs
Previously, using this code, the time was reset to `00:00` when a date was selected.
Conversely, the date was reset to `0001-01-01` when a time was selected.
```xml
<FluentDatePicker @bind-Value="@SelectedValue" />
<FluentTimePicker @bind-Value="@SelectedValue" />
<p>Selected date:</b> @SelectedValue</p>
@code
{
DateTime? SelectedValue;
}
```
Now you can link the same variable to both a **FluentDatePicker** and a **FluentTimePicker**.
Of course, when selecting a date, the time will be set to `00:00` the first time, because C# DateTime object doesn't accept a nullable time only value.
If you prefer to have a nullable date and time, you need to link these two components to two separate variables.
> [FluentDatePicker and FluentTimePicker] Keep existing time/date

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridVirtualize.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.css
- src/Core/Components/MessageBar/Services/MessageOptions.cs
Adding a new `EmptyContent` parameter to the DataGrid:
Implemented as follows:
- Add parameter `EmptyContent` (of type `RenderFragment`)  (name chosen to stay in line with new parameter added on standard Blazor `Virtualize` component)
- Add a class to the isolated `FluentDataGrid.razor.css`:
```
::deep .empty-content {
width: 100%;
height: 100%;
display: flex;
justify-content: center;
align-items: center;
font-weight: 600;
}
```
- The `FluentDataGrid` component will render this when Items/ItemsProvider is empty/has a count of 0:
```
<div class="empty-content">
@if (EmptyContent is null)
{
@("No data to show!");
}
else
{
@EmptyContent
}
</div>
``` 
This allows you to specify your own text and/or layout for when there is no content or uses a sensible default when none is provided.
- Only …
> Add `EmptyContent` parameter to the DataGrid

- src/Core/Components/List/FluentSelect.razor
- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Utilities/InlineStyleBuilder.cs
- tests/Core/Utilities/InlineStyleBuilderTests.cs
Add `InlineStyleBuilder` and fix the `FluentSelect.Height` property
Example, the code...
```csharp
new InlineStyleBuilder()
.AddStyle("div", "color", "red")
.AddStyle("div", "background-color", "blue")
.AddStyle("span", "color", "yellow")
.Build()
```
... will generate this **inline** style:
```html
<style>
div { color: red; background-color: blue; }
span { color: yellow; }
</style>
```
This new class is used in the `FluentSelect` component to always define the **z-index** and **height** style (if a Height value has been defined).
> **note** This PR fixes the discussion #771.
> [InlineStyleBuilder] Fix the FluentSelect.Height property

- examples/Demo/Shared/Pages/Emoji/EmojiExplorer.razor.cs
- examples/Demo/Shared/Pages/Icon/IconExplorer.razor.cs
- examples/Demo/Shared/Pages/Icon/IconPage.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/Dialog/FluentDialogHeader.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor
- src/Core/Components/MessageBar/FluentMessageBar.razor
- src/Core/Components/Pagination/FluentPaginator.razor
- src/Core/Components/Tabs/FluentTab.razor
- src/Core/Components/Toast/FluentToast.razor
- src/Templates/Projects/FluentUIBlazorServerApp/Shared/SurveyPrompt.razor
- src/Templates/Projects/FluentUIBlazorWebAssemblyApp/Shared/SurveyPrompt.razor
During the DotNet Publication process, the unused icons are automatically removed from the final library. You can configure this behavior by setting the `PublishTrimmed` property in your project file. More details on [this page](https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/configure-trimmer).
To avoid this issue, we recommend always using the `Value` property to specify the icon to be rendered (and not the `Icon` property). This ensures that the icon is not deleted from the final library.
With this PR...
1. The "Core/Lib" code has been updated to always use the `Value` attribute (the documentation will be updated in another PR).
2. The documentation has been updated, on the Icon page.
This solves the issue #776
> [FluentIcon] Use of Value attribute (not Icon)

- examples/Demo/Shared/Pages/Button/Examples/ButtonIcon.razor
- examples/Demo/Shared/Pages/Icon/Examples/IconColors.razor
- examples/Demo/Shared/Pages/Icon/Examples/IconDefault.razor
- examples/Demo/Shared/Pages/Icon/Examples/IconPlacement.razor
- examples/Demo/Shared/Pages/Icon/IconPage.razor
- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
- src/Core/Components/Icons/FluentIcon.razor.cs
- src/Core/Components/Icons/Icon.cs
At present, when an icon is added to a button whose appearance is **Accent**, the icon color is not correct (and must be changed manually by adding an icon to the button content).
This PR:
1. Add a method `WithColor(color)` on the **Icon** object to customize the color.
2. Detect the appearance of the **FluentButton** and update the icon color to `Color.Lightweight` if the `Appearance=Appearance.Accent`.
This PR refactors the **Icon page** / **Color options** section to display a table with a list of color possibilities.
> Button and Icon colors

- examples/Demo/Shared/Pages/MessageBar/Examples/MessageBarDefault.razor
- examples/Demo/Shared/Pages/MessageBar/Examples/MessageBarDetailed.razor
- src/Core/Components/Icons/Icon.cs
- src/Core/Components/MessageBar/FluentMessageBar.razor
- src/Core/Components/MessageBar/FluentMessageBar.razor.cs
- src/Core/Components/MessageBar/FluentMessageBarContainer.razor.cs
- src/Core/Components/MessageBar/Message.cs
- src/Core/Components/MessageBar/Services/IMessageService.cs
- src/Core/Components/MessageBar/Services/MessageOptions.cs
- src/Core/Components/MessageBar/Services/MessageService.cs
- OnMessageItemsUpdatedAsync was not handeled
- Title is now nullable and will not be rendered if null
- Link is not generating an object anymore on initialization so also nor being rendered if null
- Sample had been adapted to show this behavior
> Fix MessageBar issues

- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Utilities/InlineStyleBuilder.cs
- tests/Core/MessageBar/FluentMessageBarTests.FluentMessageBar_Default.verified.html
- tests/Core/Utilities/InlineStyleBuilderTests.cs
1. On .NET6, the `InlineStyleBuilder` renders the style tag as a string.
2. After this fix, the style is included in the code like a `style` tag.
#805
> [Fix #805] - Fix the InlineStyleBuilder on .NET6

- examples/Demo/Shared/Pages/InputFile/Examples/InputFileBufferMode.razor
- examples/Demo/Shared/Pages/InputFile/Examples/InputFileByCode.razor
- examples/Demo/Shared/Pages/InputFile/Examples/InputFileStream.razor
- src/Core/Components/InputFile/FluentInputFile.razor.cs
- src/Core/Components/InputFile/FluentInputFile.razor.js
The `ShowFilesDialogAsync` method of the `FluentInputFile` component doesn't work in Safari. Normally, the browser should pop its native file selection dialog. In Safari, this browser dialog doesn't show when the application tries to open it programmatically via C#.
The `ShowFilesDialogAsync` method is pretty simple. It uses JSInterop to call the click JavaScript method of the `<input type="file" />` element inside the component HTML output.
Safari requires the file input dialog to open programmatically as a direct result of a user action. If the file input is clicked programmatically, this must happen in JavaScript code, which handles a user event.
JSInterop cannot be directly associated with a user action, due to its nature. A .NET method itself is not directly triggered by user action. …
> [FluentInputFile] Fix the manual upload on iOS

- src/Core/Components/NumberField/FluentNumberField.razor.cs
The word _length_ is misspelled.
> fixes minor typo in FluentNumberField.razor.cs

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- src/Core/Components/Dialog/Services/DialogService-Dialog.cs
Before, if the developer forgot to set '<FluentDialogProvider />' this error occured.
`Object reference not set to an instance of an object.`
Now, this error will be displayed:
`<FluentDialogProvider /> needs to be added to the main layout of your application/site. (Parameter 'OnShowAsync')` 
To fix #826
> [FluentDialog] Error message updated when FluentDialogProvider is missing

- examples/Demo/Shared/Pages/InputFile/Examples/InputFileByCode.razor
- examples/Demo/Shared/Pages/InputFile/Examples/InputFileDefault.razor
Once I'd started using this component, I simply copied and pasted this first sample. My existing code that uses Stream and of course it didn't work straight away. But after some research I realized that the InputFileMode property is SaveToTemporaryFolder, by default and this attribute is not added. I think the documentation would be clearer if this parameter were specified in this samples
> docs: Update sample InputFileDefault.razor

- README.md
Just add a missing space.  - NO CODE CHANGED
No issue
Contributing for fun
N/A
> Fixing typo on  the readme.md

- examples/Demo/Shared/Components/SiteSettingsPanel.razor.cs
- examples/Demo/Shared/Shared/DemoMainLayout.razor.cs
- src/Core/DesignTokens/DesignToken.razor.cs
- src/Core/DesignTokens/IDesignToken.cs
FAST/FluentUI DesignTokens support setting a default value for a particular token as well as setting a (non-default) value for a particular container element (and its descendants). FluentUI-Blazor supports the latter, with DesignToken.SetValueFor, but WithDefault is currently not implemented.
When you truly want to set the value for a particular design token for all elements on the page (not just a subset), WithDefault is useful. It has the side benefit of not polluting the DOM with a large style attribute on whatever container element is used in SetValueFor.
Using WithDefault doesn't prevent you from using SetValueFor in other places in the page, as evidenced by the example pages for buttons and toolbars, and the design token page itself. 
This is technically a breaking change since it …
> fix!: Implement DesignToken.WithDefault and use in Demo site

- examples/Demo/Shared/Microsoft.Fast.Components.FluentUI.xml
- src/Core/Components/Divider/FluentDivider.razor.cs
- src/Core/Components/Divider/FluentDivider.razor.js
Until we have a solution from the FAST team, a `setDividerAriaOrientation` script is run each time a **FluentDivider** is rendered. This script removes any `aria-orientation` when the component has a `role='presentation'`.
```js
export function setDividerAriaOrientation() {
const elements = document.querySelectorAll("fluent-divider[role='presentation']");
if (!!elements) {
elements.forEach((element, i, array) => {
if (!!element && element.hasAttribute("aria-orientation")) {
element.removeAttribute("aria-orientation");
}
});
}
}
```
> [Accessibility] fix FluentDividerFix aria-orientation

- src/Core/wwwroot/Microsoft.FluentUI.AspNetCore.Components.lib.module.js
The new Blazor initializers for .NET 8 have some errors in them that cause runtime errors to show in the browser console, initialization to not succeed if the new initializers are called and some components that depend on those initializers to not work properly.
I just created the PR instead of creating an issue, in part because of GH's outage this morning when I was trying to file the issue.
It appears this was introduced in https://github.com/microsoft/fluentui-blazor/pull/909 as the initial set of initializers that were introduced to /dev in https://github.com/microsoft/fluentui-blazor/pull/879 had these in place.
> Fix .NET 8 initializers

- .vscode/settings.json
- src/Assets/FluentUI.Emojis/Emojis.cs
- src/Assets/FluentUI.Icons/Icons.cs
- src/Assets/Generator/Properties/launchSettings.json
- src/Extensions/DataGrid.EntityFrameworkAdapter/Properties/launchSettings.json
- src/Extensions/DesignToken.Generator/Properties/launchSettings.json
- src/Templates/Properties/launchSettings.json
- tests/Core/Properties/launchSettings.json
Remove last traces of **Microsoft.Fast.Components**
Replace all `Microsoft.Fast.Components.FluentUI` with `Microsoft.FluentUI.AspNetCore.Components`
> [Namespace update] Remove last traces of Microsoft.Fast.Components

- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipDelay.razor
Adapt label to what it actually does: Displaying tooltip at the top.
Before:
After:
> Tooltip at the top demo

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Splitter/Examples/SplitterCollapse.razor
- examples/Demo/Shared/Pages/Splitter/SplitterPage.razor
- src/Core/Components/Splitter/FluentSplitter.razor
- src/Core/Components/Splitter/FluentSplitter.razor.cs
- src/Core/Events/CollapsedChangedEventArgs.cs
- src/Core/Events/EventHandlers.cs
- src/Core/wwwroot/Microsoft.FluentUI.AspNetCore.Components.lib.module.js
- src/Core/wwwroot/js/SplitPanels.js
We have a use case for the FluentSplitter (effectively a Summary/Details view) where it'd be nice if the splitter bar and Panel2 could be hidden under certain conditions. Right now the best you can do is push the splitter bar all the way over to the side or bottom. 
This PR adds a Collapsed parameter (and a collapsed attribute on the underlying custom element) that can be used for this purpose. Setting `Collapsed="true"` on the blazor component (or simply adding the boolean `collapsed` attribute on the custom element) will trigger this mode, hiding the splitter bar and Panel2.
I also tweaked some of the setup of the splitter custom element, by pulling the styling out into a shared constructed stylesheet and adding it to the shadow root's adoptedStyleSheets property. It won't make a …
> feat: add collapsed state to splitter component

- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj
Update package references that are still using `Version="8.0.0-rc.2.*"` in the Web app template.
https://github.com/microsoft/fluentui-blazor/blob/abbbd2ff89c1074a2a602f294a5a6d48a9247841/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj#L22
> Update template references

- examples/Demo/Client/FluentUI.Demo.Client.csproj
- examples/Demo/Shared/Pages/Drag/DragDropPage.razor
- examples/Demo/Shared/Pages/Emoji/EmojiPage.razor
- examples/Demo/Shared/Pages/MessageBar/Examples/MessageBarTimed.razor
- examples/Demo/Shared/Pages/MessageBar/MessageBarPage.razor
- examples/Demo/Shared/Pages/MessageBox/MessageBoxPage.razor
- examples/Demo/Shared/Pages/SplashScreen/SplashScreenPage.razor
- examples/Demo/Shared/Pages/Splitter/SplitterPage.razor
Since we configured the Blazor Trimming option, some demo pages were no longer working properly.
These problems are due to Reflector calls that need to be informed in the Trimming parameters.
This is done with this code, added to the csproj
```xml
<ItemGroup>
<TrimmerRootAssembly Include="Microsoft.FluentUI.AspNetCore.Components" />
<TrimmerRootAssembly Include="FluentUI.Demo.Shared" />
</ItemGroup>
```
The part of code to "hack the compiler to include these classes in the final library" are removed.
> Fix the WASM Trimming issue

- examples/Demo/Shared/Pages/Label/Examples/LabelDefault.razor
While using the library to quickly develop, I found it odd to have demo code show non-applicable implementations. The foreach loop is fairly intuitive but in most cases these types of UI libraries provide a dev UX that allows for tasty copy-pasta. This PR simply unwinds the foreach loop for a better dev UX that quickly allows copying out code snippits in the Label page on the demo site.
None
This is a developer user experience improvement within the demo site that might be slightly subjective.
No tests affected
- [X ] I have tested my changes.
- [X ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.
> Update label demo code with explicit code snippits to improve dev ux

- WHATSNEW.md
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
Fix typo and format in Whatsnew.md files.
miscallaneous => miscellaneous
> Typo in What's new

- WHATSNEW.md
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
> Typos in What's new

- src/Core/Components/NumberField/FluentNumberField.razor
- src/Core/Components/NumberField/FluentNumberField.razor.cs
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_ReadOnlyParameter.verified.html
When the `readonly` attribute is used, the component can still be modified using the keyboard arrows.
This problem is due to a bug in the associated WebComponent.
It has been worked around by forcing the min/max values when the ReadOnly property is applied.
> [FluentNumberField] Fix the readonly attribute #v3

- examples/Demo/Shared/Pages/Dialog/DialogPage.razor
- src/Core/Components/Dialog/FluentDialogProvider.razor.cs
During the WASM DotNet Publication process, the unused classes are automatically removed from the final library. The Dialog razor file will be removed if no reference are set by your code. For example, if you call `var = await DialogService.ShowDialogAsync<SimpleDialog>(simplePerson, parameters);` the **SimpleDialog** will be removed by the WASM Publication process. You can configure this behavior by setting the [PublishTrimmed](https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/configure-trimmer) property in your project file or you can create a temporary instance `var temp1 = new SimpleDialog();` to force the Publication process to keep this class in the final library.
In this PR, this action has been taken for the **MessageBox** class, to solve #1057.
Another solution could …
> [MessageBox] Fix the MessageBox usage in WASM projects #v3

- examples/Demo/Shared/Pages/Dialog/Examples/DialogCustomizableExample.razor
- examples/Demo/Shared/Pages/Dialog/Examples/SimpleCustomizedDialog.razor
When a dialog box is opened, the data sent to this dialog is linked to the fields.
This means that the content of the linked properties are automatically modified by Blazor,
and it is very difficult to undo the changes.
This example uses a `record` that creates a new object instance to the dialog box.
This makes it easy to undo or undo not the user's modifications.
This answers question #1074
> [Dialogbox] Example using a Cancel button #v3

- examples/Demo/Shared/Pages/Checkbox/CheckboxPage.razor
- examples/Demo/Shared/Pages/Checkbox/Examples/CheckboxThreeStateList.razor
- src/Core/Components/Checkbox/FluentCheckbox.razor.cs
Sometimes, when a checkbox is placed in "intermediate" mode, the ThreeState property is indeed null, but the checkbox is not "semi-checked". Apparently, the "intermediate" class is not always applied correctly by the Web component.
This double check should correct this problem:
1. Using the `setFluentCheckBoxIndeterminate` javascript method= `item.indeterminate = indeterminate;`
2. Adding the "indeterminate" class: `.AddClass("indeterminate", when: ThreeState && CheckState is null )`
This problem should resolve this discussion:
https://github.com/dotnet/aspire/pull/1221#discussion_r1416804617
> [FluentCheckbox] Fix Three States List

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Checkbox/FluentCheckbox.razor.cs
- tests/Core/Checkbox/FluentCheckboxThreeStatesTests.razor
Add a `ThreeStateOrderUncheckToIntermediate` attribute indicating the order of the three CheckBox states.
- False (default), the order is Unchecked -> Checked -> Intermediate.
- True: the order is Unchecked -> Intermediate -> Checked.
1. ThreeStateOrderUncheckToIntermediate = False: `[ ] -> [x] -> [-]`
2. ThreeStateOrderUncheckToIntermediate = True: `[ ] -> [-] -> [x]`
Related to #1096
> [Checkbox] ThreeStateOrderUncheckToIntermediate

- src/Core/Components/Base/FluentInputBase.cs
See #1103 for the original issue. I don't think pulling in this change has any other consequenses
> Create FieldIdentifier when no ValueExpression set

- examples/Demo/Shared/Pages/Progress/Examples/ProgressStrokeExample.razor
- examples/Demo/Shared/Pages/Progress/ProgressPage.razor
- examples/Demo/Shared/Pages/ProgressRing/Examples/ProgressRingStroke.razor
- src/Core/Components/Progress/FluentProgress.razor
- src/Core/Components/Progress/FluentProgress.razor.cs
- src/Core/Components/Progress/FluentProgressRing.razor
- src/Core/Components/Progress/FluentProgressRing.razor.cs
- src/Core/Enums/ProgressStroke.cs
- tests/Core/Microsoft.FluentUI.AspNetCore.Components.Tests.csproj
- tests/Core/Progress/FluentProgressRingTests.razor
- tests/Core/Progress/FluentProgressTests.razor
As proposed by JamesNK, https://github.com/microsoft/fluentui-blazor/pull/1121#discussion_r1427371730
- `ProgressStrokes` was renamed to `ProgressStroke` (without `s`)
- `ProgressStrokes.Thin` was renamed to `ProgressStrokes.Small`. Values are `Small`, `Normal` and `Large`.
Updated and verified.
> [FluentProgress] Update Stroke enumeration - v4 & v3

- examples/Demo/Shared/Pages/Toast/Examples/ToastProgressToasts.razor
- src/Core/Components/Toast/ContentComponents/ProgressToast.razor
The current `ProgressToast` component renders a percent sign below the progress bar, regardless of whether the progress has a determinate or indeterminate state. This PR updates the `ProgressToast` component to only render the percent sign if the `ProgressToastContent.Progress` property is **not** null.
Current `ProgressToast` with indeterminate progress bar:
Proposed change to `ProgressToast` with indeterminate progress bar:
No issue has been opened for this UI bug.
The changes are viewable in the demo project--the indeterminate progress toast does not have a percent sign while the determinate progress toast still does.
Ad-hoc testing through the demo project.
(Note: there are currently no active tests for Toast components.)
> fix: Do not render percent sign for indeterminate ProgressToast

- Directory.Packages.props
- examples/Demo/AssetExplorer/Components/Controls/PreviewCard.razor
- examples/Demo/AssetExplorer/Components/Controls/PreviewCard.razor.cs
- examples/Demo/AssetExplorer/Components/Controls/PreviewCard.razor.css
- examples/Demo/AssetExplorer/Components/Pages/IconExplorer.razor
- examples/Demo/AssetExplorer/Components/Pages/IconExplorer.razor.cs
- examples/Demo/AssetExplorer/Models/IconSearchCriteria.cs
Updated the list of icon sizes to include an `[All]` item. This allows the user to search for all icons. In this case, a small "size" label is displayed at the top of the card.
> [Icons Explorer] search icons on all sizes

- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/FluentListbox.razor.cs
- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Components/List/ListComponentBase.cs
If an element is null, rendering fails with an unclear message.
The documentation has been updated and a clear message will be displayed, during the execution.
Error: System.NullReferenceException: 
Object reference not set to an instance of an object.
Error: System.NullReferenceException: 
You cannot use a null element as an option in the Items property.
> [List components] Each item must be instantiated (cannot be null).

- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
- src/Core/Components/Button/FluentButton.razor.css
```razor
<FluentButton Loading="@loading"
OnClick="@StartLoadingAsync" 
Appearance="Appearance.Accent">
Loading
</FluentButton>
<FluentButton Style="width: 70%"
Appearance="Appearance.Accent"
Loading="@loading"
OnClick="@StartLoadingAsync">
Load
</FluentButton>
```
> [FluentButton Loading] Fix button when style is applied

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Design/Examples/DesignThemeDefault.razor
- src/Core.Assets/src/index.ts
- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs
- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.js
Add an `OnLoaded` event raised when the component is rendered for the first time.
This event contains all properties initialized: `Mode`, `IsDark`, `CustomColor`, `OfficeColor`, `StorageName`, `Direction`.
Two new JavaScript properties are added: `Blazor.theme.isDarkMode()` and `Blazor.theme.isSystemDark()`
```razor
<FluentDesignTheme OnLoaded="@OnLoaded"
OnLuminanceChanged="@OnLuminanceChanged" />
@code
{
void OnLoaded(LoadedEventArgs e)
{
DemoLogger.WriteLine($"Loaded: {(e.Mode == DesignThemeModes.System ? "System" : "")} {(e.IsDark ? "Dark" : "Light")}");
}
void OnLuminanceChanged(LuminanceChangedEventArgs e)
{
DemoLogger.WriteLine($"Changed: {(e.Mode == DesignThemeModes.System ? "System" : "")} {(e.IsDark ? "Dark" : "Light")}");
}
}
```
> [FluentDesignTheme] Add OnLoaded event

- examples/Demo/Shared/Pages/Listbox/ListboxPage.razor
Hello. This PR fixes the outdated w3.org link to the [Listbox Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/).
> docs: fix outdated w3.org link

- src/Core/Components/NavMenu/FluentNavMenu.razor.js
- tests/TemplateValidation/SSR/Components/Layout/NavMenu.razor
Before this change:
1. Run the project.
2. Click the collapse button. -- it works now
3. Click a menu item Home or Weather.
4. Click the collapse button again -- it doesn't work.
For step 4 it actually did work, but the event was triggered twice, so a collapse was triggered which triggered an expand. For the naked eye nothing happened. With theis change the the adding of the eventlistener is moved to the `onLoad` function so it gets registered only once.
> Fix #1185: NavMenu Collapse button behavior in SRR only woks once

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Slider/FluentSliderLabel.razor
- src/Core/Components/Slider/FluentSliderLabel.razor.cs
- src/Core/Components/Slider/FluentSliderLabel.razor.js
- tests/Core/Slider/FluentSliderLaberTests.cs
To fix the issue #1204.
Added JS code to update the `max-width` **label included in the `fluent-slider-label**.
> [FluentSliderLabel] Update the sub-label MaxWidth style

- Microsoft.FluentUI.sln
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Button/FluentButton.razor.cs
- src/Core/Components/Button/FluentButton.razor.js
- src/Core/Components/Slider/FluentSliderLabel.razor.cs
- tests/Core/Button/FluentButtonTests.cs
Due to an error on the FAST side (https://github.com/microsoft/fast/issues/5675), a FluentButton oouside of a form generates an error when trying to submit. The suggested workaround from the referenced issue is implementend with this PR in a colloacted script. The form as described in #1205 can be submitted now with the FluentButton being outside of the form.
PR also includes  IAsyncDisposable implementaiton for previous Slider PR
> Fix #1205  FluentButton submit does not work outside the EditForm #v3

- src/Core/Components/Dialog/Services/DialogService.cs
Add this line to prevent the _Trimming_ process from deleting this class?
```csharp
_ = new DialogEventArgs() { Id = "0", Reason = "Unknown" };
```
> [DialogService] Add a fake instance of DialogEventArgs #280

- src/Core/Components/Tabs/FluentTabs.razor.cs
When `HandleOnTabChange` is being called with `TabChangeEventArgs` being `null`, the component should not rerender itself (as no actual tab change has taken place) 
In troduced a `bool` _shouldRender which is set to `false` when the above happens. The overridden `ShouldRender` base method now returns the value of  `_shouldRender` and effectively cancels the re-render whna no tab change has occured.
> Fix #1194 #v3

- src/Core.Assets/src/PageScript.ts
- src/Core/Components/PageScript.razor
When using a container with `display: flex; justify-content: space-between;` this result fails.
```xml
<div style="display: flex; justify-content: space-between;">
<div style="border: 1px solid red;">First</div>
<PageScript Src="." />
<div style="border: 1px solid Yellow;">Second</div>
<div style="border: 1px solid blue;">Last</div>
</div>
```
Adding this style `display: none;` the result is correct. This PR apply this style inside the web component.
The Unit Tests are now corrects
> [PageScript] Move script visibility inside the web component

- examples/Demo/Shared/Pages/ComponentBindings.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ExternalLogin.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ForgotPassword.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Login.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/LoginWith2fa.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/LoginWithRecoveryCode.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/ChangePassword.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/DeletePersonalData.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/Email.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/EnableAuthenticator.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/Index.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/SetPassword.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Register.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ResendEmailConfirmation.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/ResetPassword.razor
- Fix spelling mistake `FluentValidationMesssage` (3 x s)
- Replave `ValidationSummary` with `FluentValidationSummary`
> [Templates] Fix spelling and use `FluentValidationSummary`

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/BasicFormBlazorComponents.razor
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/Components/DateTime/FluentCalendar.razor.cs
- src/Core/Components/DateTime/FluentCalendarBase.cs
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
By deriving from InputBase, the components can hook into the validation process and respond to classes being added for modified/invalid/valid:
Before: invalid value is detected but input field does not get border added
After: invalid value is detected and input field gets border added
> Derive Calendar and DatePicker from InputBase (instead of ComponentBase)

- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/FluentCombobox.razor.css
Fix the #1274 issue without using a `!important` mark.
> Fix Combobox width without a important mark

- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Components/List/FluentSelect.razor.css
Fix the #1274 issue without using a `!important` mark... and for FluentCombobox **_and_** FluentSelect components.
> Fix Combobox and Select width property

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Splitter/Examples/SplitterBarHandle.razor
- examples/Demo/Shared/Pages/Splitter/SplitterPage.razor
- src/Core.Assets/src/SplitPanels.ts
- src/Core/Components/Splitter/FluentSplitter.razor
- src/Core/Components/Splitter/FluentSplitter.razor.cs
- tests/Core/Splitter/FluentSplitterTests.FluentSplitter_BarHandle.verified.razor.html
- tests/Core/Splitter/FluentSplitterTests.razor
Based on discussion in Aspire (https://github.com/dotnet/aspire/pull/1506) a `BarHandle` parameter has been added to the `FluentSplitter`. 
To not break any existing setups, the default for the parameter is set to 'true'.  So not specifying the parameter means the bar is (still) shown. 
An example of using this has been added to the documentation page
> [Spliiter]: Add parameter to hide/show bar handle

- src/Core/Components/List/FluentCombobox.razor.cs
In v4.3 we merged in a change to `SetParametersAsync` in `ListComponentBase` to sync `Selectedoption` with `Value`. This interferes with how a Combobox works. By adding its own overridden `SetParametersAsync` to `FluentComnbobox` this works again as it should.
> Fix #1305 by overriding SetParametersAsync for Combobox

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Button/FluentButton.razor.js
With earlier fixes, we made it possible to have submit button be outside of `EditForm`. This requires to have an `id` set on the `EditForm`. However, the `id` was now also required when the submit was placed inside the `EditForm`. This PR fixes that. It will also show a warning now in the browser console when submit is placed outside of `EditForm` and no `id` is supplied.
> Better fix for #1205 / #1225 which fixes #1294

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Tabs/FluentTabs.razor.cs
Add a `GoToTabAsync(stringTabId)` method to FluentTabs to fix issue #1314.
> [Tabs]: Add GoToTabAsync() method. Fixes #1314

- src/Core/Enums/JustifyContent.cs
Changes the `JustifyContent` enum description to better refer to what it is doing, instead of referring to emojis.
Hey folks, I noticed a small documentation error with the `JustifyContent` while I was developing a side project with the library. Currently it refers to emojis when it seems like it should be referring to what Justify Content is doing.
Did not find an open issue for this.
N/A
N/A
- [ X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fluentui-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.
Feel free to let me know if you would like me to make any changes to the description on the enum, or with the pull request in general.
Thank you all for your …
> Fix `JustifyContent` enum documentation description

- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
More fixes for issue 1323. Some other changes to bring code inline with other files/standards
> More checks and changes for fixing #1323

- WHATSNEW.md
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
- src/Core.Assets/src/FluentPageScript.ts
- src/Core.Assets/src/index.ts
- src/Core/Components/FluentPageScript.razor
- src/Core/Components/NavMenu/FluentNavMenu.razor
- src/Core/Components/PageScript.razor
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_Collapsible.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_CollapsibleCustomTitle.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_CustomTitle.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_Default.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_ExpanderContent.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_Margin.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_NotExpanded.verified.html
- tests/Core/NavMenu/FluentNavMenuTests.FluentNavMenu_Width.verified.html
- tests/Core/_ToDo/MainLayout/FluentMainLayoutTests.FluentMainLayout_Default.verified.html
As the title says. Decouple implementation for the learn docs supplied solution by using a more library bound name
> Fix #1335. Address feedback. Rename PageScript ->FluentPageScript

- examples/Demo/Shared/Shared/DemoNavMenu.razor
- src/Core/Components/List/FluentListbox.razor
- src/Core/Components/List/InternalListContext.cs
- src/Core/Components/List/ListComponentBase.cs
Adding functionality to make the keyboard selection work for listbox (when using the `Items` parameter to specify the list items). Fixes #1344. 
See below for how it works. First selection is done with click, then End, Home and arrows down/up:
Making it work with a list where the itmes are manually specified is a lot more (complicated) work.
Also grouped the list based gomponents together in one nav menu group
> [FluentListbox] Add keyboard navigation/selection

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/BasicFormFluentUIComponents.razor
- src/Core.Assets/src/index.ts
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
- tests/Core/DateTime/FluentDatePickerTests.cs
Because both `FluentDatePicker` and the contained `FluentTextField` derive from `FluentInputBase` the `ClassValue` is set twice and that in the end leads to inconsistent values for validation in the class attribute. 
To solve, I'm adding a `bool` parameter `Embedded` to `FluentInputBase` (defaults to false). If set to true, `ClassValue` will not include the `FieldCssClass` for that component. 
Because it is a parameter on `FluentInputBase`, we can apply this fix to all input components that have other embedded input components.
- Add `Embedded` parameter to `FluentInputBase`
- [DatePicker] Use `Embedded`
- [DatePicker] Use `CurrentValueAsString` and `FormatValueAsString` from base class
- [DatePicker] turn off `AutoComplete`
Fix #1311
> Fix problems with validation border color / validation classes

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridVirtualize.razor
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.css
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
This PR adds `Loading` (bool, default = false) and `LoadingContent` (RenderFragment?) parameters to the FluentDataGrid. 
By default, when `Loading` is set to true, the loading content will be a progress ring with the text 'Loading...'  shown besides it. You can replace that with your own content through this parameter.
To change the state of the `Loading` parameter at a later stage, use the `SetLoadingState(bool loading)` method on the `FluentDataGrid`. To be able to call this method from your code, you need to add a `@ref` to your grid
The loading content is rendered in a `FluentDataGridRow` with one `FluentDataGridCell` inside of it. The row height will be set to 100%. If no height is set for the grid this will be a normal row height. It a height is set for the grid, the row will take …
> [DataGrid] - Add Loading and LoadingContent parameters

- src/Core/Components/Grid/FluentGrid.razor.css
- src/Core/Components/Grid/FluentGrid.razor.js
- src/Core/Components/Wizard/FluentWizardStep.razor.css
I noticed that the `FluentGrid` component displayed grid items that were meant to be hidden at fractional pixel sizes.
For example, the `FluentCard` labeled 'xs="12" sm="6" Hidden="SmAndDown"' in following screenshot is hidden with a browser size '<= 599px' or '>= 600px and <= 959px' but not inbetween those values (i.e. 599.33px):
To fix this, I added .98px to the max-width breakpoints, as explained under following link:
https://stackoverflow.com/questions/54596219/why-do-some-max-width-media-queries-use-a-98px
> [Grid] Fix breakpoints not working with fractional pixels

- examples/Demo/Shared/Pages/Dialog/DialogPage.razor
- examples/Demo/Shared/Pages/Dialog/Examples/DialogEditableExample.razor
- examples/Demo/Shared/Pages/Dialog/Examples/SimpleEditDialog.razor
```razor
@using System.ComponentModel.DataAnnotations
@implements IDialogContentComponent<SimpleEditDialog.RegisterContent>
<FluentDialogHeader ShowDismiss="true">
<FluentStack VerticalAlignment="VerticalAlignment.Center">
<FluentIcon Value="@(new Icons.Regular.Size24.WindowApps())" />
<FluentLabel Typo="Typography.PaneHeader">
@Dialog.Instance.Parameters.Title
</FluentLabel>
</FluentStack>
</FluentDialogHeader>
<FluentDialogBody>
<EditForm EditContext="@_editContext" FormName="simple_register">
<DataAnnotationsValidator />
<FluentLabel Style="margin-bottom: 16px;">
Your name must be between 3 and 20 characters long,
and your age between 1 and 99.
</FluentLabel>
<FluentTextField Name="register_name"
@bind-Value="@Content.Name"
Label="Name"
Required />
<FluentNumberField …
```
> [Sample] Add an example of an editable and validatable dialog box

- src/Core/Components/Checkbox/FluentCheckbox.razor.cs
- tests/Core/Checkbox/FluentCheckboxTests.FluentCheckbox_DisabledParameter.verified.html
[Checkbox] Fix missing Checkbox "disabled" class
After updating the value of a disabled component checkbox, the disabled checkbox displays the current HTML code.
Note the absence of class="disabled".
```html
<fluent-checkbox disabled="" role="checkbox" aria-checked="false" aria-required="false" aria-disabled="true">Disabled</fluent-checkbox>
```
This PR adapts the class by adding `disabled` when the control is disabled.
> [Checkbox] Fix missing Checkbox "disabled" class [v3]

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/InputFile/Examples/InputFileDisabled.razor
- examples/Demo/Shared/Pages/InputFile/InputFilePage.razor
- src/Core/Components/InputFile/FluentInputFile.razor
- src/Core/Components/InputFile/FluentInputFile.razor.cs
- src/Core/Components/InputFile/FluentInputFile.razor.css
- tests/Core/InputFile/FluentInputFileTests.FluentInputFile_Disabled.verified.razor.html
- tests/Core/InputFile/FluentInputFileTests.razor
- tests/Core/Microsoft.FluentUI.AspNetCore.Components.Tests.csproj
I'm using the FluentFileInput component in a project. I have a requirement to _disable_ the file upload field under certain conditions. 
All HTML input components, including the native `input type=file`, support a disabled attribute. 
This pull request adds a `disabled` property to the `FluentFileInput` component.  When this attribute is set, a CSS class is applied to the container making it appear more translucent / lighter, as well as disabling cursor events on the component, and setting the embedded `input type=file` component to be disabled. 
This PR also includes updated unit tests to cover the new property.
This PR also updates the demo project to add an example of this component in the disabled state.
I considered trying to add all the other missing standard input component …
> [FluentFileInput] adds a "disabled" property to the FluentFileInput component

- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Shared/ExternalLoginPicker.razor
Temporary fix for #1391 by adding a hidden input with name and value because when these are set on the FluentButton the web component posts the name and value **twice**, which leads to issues in the `PerformExternalLogin` handler.
Issue has been reported to the Fluent team. Once fixed there, this workaround can/shoud be undone.
> Temporary fix #1391

- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.js
Like describe in this issue: #1182
this error may occur when the user changes Theme using FluentDesignTheme
SteveSandersonMS replied with [this anwser](https://github.com/dotnet/aspnetcore/issues/26809).
> What's happening here is that your JS code is trying to call back into .NET during the middle of applying a renderbatch 
> to the DOM. This isn't safe to do, because if .NET code runs at this time, it might modify the contents of .NET memory 
> and invalidate the renderbatch that's still being processed.
> 
> To avoid this problem, when performing JS interop calls that can occur while applying a renderbatch, be sure to defer 
> the call. For example, update your code as follows:
>
> ```js
>    window.document.addEventListener("focusout", function (e) {
>        console.log("focus out: " …
```
>  [FluentDesignTheme] Assertion failed "heap is currently locked when changing theme"

- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- tests/TemplateValidation/IndividualAccounts/B-Server/PerPage/FluentUI.TemplateValidation.csproj
- tests/TemplateValidation/IndividualAccounts/C-Wasm/Global/FluentUI.TemplateValidation/FluentUI.TemplateValidation.csproj
- Override ShouldRender to prevent double rendering
- Remove superfluous @ChildContent call
> Fix #1421 

- examples/Demo/Shared/Pages/BasicFormFluentUIComponents.razor
- examples/Demo/Shared/SampleData/Starship.cs
- src/Core/Components/Switch/FluentSwitch.razor
Initial changes for fixing FluentSwitch
> Switch changes

- src/Core/Components/NumberField/FluentNumberField.razor
In Blazor Server, holding down `Space`, `ArrowUp`, or `ArrowDown` leads to a loop in value changes.
This issue has been reproduced in both the dev branch and v4.3.1.
Both fluent-switch and fluent-number-field have `value` and `current-value` properties.
The difference between them is that `current-value` represents the real-time value displayed in the UI.
This means that `current-value` and `value` can differ, especially with rapid inputs.
Since setting either `current-value` or `value` triggers a change in value, under certain conditions, this can cause a loop in value changes.
This PR resolves the issue by not setting `current-value`.
```mermaid
flowchart TD
subgraph fluent-ui web-component
current-value
value
onchange
end
subgraph blazor-server
SetCurrentValueAsync
StateHasChanged
end …
```
> Not setting `current-value` for fluent-number-field

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteDefault.razor
- src/Core/Components/Accessibility/FluentKeyCodeEventArgs.cs
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
Fixes these Autocomplete problems:
1. Prevents the `Enter` key from selecting a deactivated item.
2. Prevents selection of disabled items when navigating with the `Up` and `Down` arrows.
3. Re-enables the ability to click on an element to select / deselect it.
> [Autocomplete] Fix Disabled item using keyboard and re-enables the ability to click on an element

- examples/Demo/Shared/Components/NotificationCenterPanel.razor
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/MessageBar/FluentMessageBar.razor
- src/Core/Components/MessageBar/FluentMessageBar.razor.cs
In the FluentMessageBar some @onclick event bindings were broken since version 4.4.0, I replaced them with the new OnClick. If a Target was specified in the Link of a notification, it was not used in the FluentMessageBar and always fell back to _blank.
1. Fix: When opening the FluentMessageBar, it would create the unhandledexception "Unhandled exception rendering component: Unable to set property 'onclick' on object of type 'Microsoft.FluentUI.AspNetCore.Components.FluentAnchor'. The error was: Arg_InvalidCastException", this has been fixed by replacing the @onclick with OnClick
2. If the Link in the Message would contain a target, this target was not used (hardcoded to _blank). Now it user the target in the link or _blank in case no target has been specified.
Add messages to the …
> fix: FluentMessageBar onclick bug and not using Link?.Target

- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs
When a `FluentThemeDesign` is used without parameters, a random color was selected.
It polished the next updates, mainly after a processing time.
This random color processing should be done outside the Fluent components, only in the Demo site :-)
Issue #1455
> [FluentDesignTheme] Fix the Random color annoys other fillers

- src/Templates/README.md
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/MainLayout.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/NavMenu.razor
Minor clean up of things while testing templates.
- extra end of paragraph tag in template readme
- extra lines found in razor files, removed to make cleaner in appearance
Only suggestions 🙂
> Minor clean up

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DateTimes/DateTimesPage.razor
- examples/Demo/Shared/Pages/DateTimes/Examples/DateTimeConversionExample.razor
- src/Core/Extensions/DateTimeExtensions.cs
- tests/Core/DateTime/ToDateTimeExtensionsTests.cs
To simplify the use of `DateTime`, `DateOnly` and `TimeOnly`, these extension methods could be used like in the following example.
- `DateTime DateOnly.ToDateTime()`
- `DateTime? DateOnly.ToDateTimeNullable()`
- `DateOnly DateTime.ToDateOnly()`
- `DateOnly? DateTime.ToDateOnlyNullable()`
- `DateTime TimeOnly.ToDateTime()`
- `DateTime? TimeOnly.ToDateTimeNullable()`
- `TimeOnly DateTime.ToTimeOnly()`
- `TimeOnly? DateTime.ToTimeOnlyNullable()`
If your variable is of type `Nullable<DateTime>`, you can continue to use `@bind-Value`.
For other types, you must use the syntax `value="..." ValueChanged="..."`
```razor
<FluentDatePicker @bind-Value="@MyDate0" />
<FluentDatePicker Value="@MyDate1" ValueChanged="@(e => MyDate1 = e.ToDateTime())" />
<FluentDatePicker …
```
> # [DatePicker] Add DateOnly and TimeOnly extensions 

- src/Core/Components/Pagination/FluentPaginator.razor.css
The navigation child element of the `FluentPaginator` has a background color set.
This seems to be off, as it looks like this when placing it on a `FluentCard` for example:
By removing the background color, it simply inherits the background color of the element it is placed on:
> Remove background color for FluentPaginator nav

- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
Use a specific SetParametersAsync for Combobox so initial/programmetic selection can be made.
New behavior can be tested with '/IssueTester'. Needs to be cleared after approval/before merging.
> Fix 1485 by overriding SetPatrametersAsync

- src/Core/Components/Icons/FluentIcon.razor.cs
- tests/Core/Icons/FluentIconTests.razor
This fix, which was discovered in `FluentNavLink` via this issue #1535, checks to see if `ColorWith` and `CustomColor` are used together.
- Including this fix
```csharp
if (Color == AspNetCore.Components.Color.Custom && !string.IsNullOrEmpty(_icon.Color))
{
return _icon.Color;
}
```
- Adding associated unit test
> [Icon] Fix Icon color using `ColorWith` and a `CustomColor` attribute

- src/Core/Components/List/FluentAutocomplete.razor
The Required property from the FluentAutoComplete was not passed on to its label, making it not look required.
a small fix, that took a full 2min to fix :p
autocomplete didn't look like it was required, while it was set
didn't find any tests to test this with, does autocomplete have any tests/html it compares to that i might have missed?
I added Required to the storyboard's country autocomplete and got a nice '*' to indicate required now
none required :)
> fix: add 'required' binding to the autocomplete label

- src/Core.Assets/src/SplitPanels.ts
- src/Core.Assets/src/index.ts
`document.adoptedStyleSheets` is frozen in earlier versions. `Array.push` not working.
Such as `Microsoft.AspNetCore.Components.WebView.Maui` `8.0.3`
> Fix adoptedStyleSheets is frozen in earlier versions

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/SplashScreen/Examples/DialogSplashScreenDefault.razor.cs
- src/Core/Components/Dialog/ContentComponents/FluentSplashScreen.razor.cs
- src/Core/Components/Dialog/Parameters/SplashScreenContent.cs
Adding two new properties to allow SplashScreen customization during the loading process:
- `SplashScreenContent.DisplayTime`: Gets or sets the delay to wait before to close the dialog. Default is 4000 milliseconds.
- `SplashScreenContent.UpdateLabels(loadingText, message)`: Updates the labels of the splash screen.
```csharp
DialogParameters<SplashScreenContent> parameters = new()
{
Content = new()
{
DisplayTime = 0,    // // <============== See Task.Delay below
Title = "Core components",
SubTitle = "Microsoft Fluent UI Blazor library",
LoadingText = "Loading...",
Message = (MarkupString)"some <i>extra</i> text <strong>here</strong>",
}
};
_dialog = await DialogService.ShowSplashScreenAsync(parameters);
var splashScreen = (SplashScreenContent)_dialog.Instance.Content;
// Simulate a first …
```
> [FluentSplashScreen] Add WaitingMilliseconds and UpdateLabels

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipDelay.razor
- examples/Demo/Shared/Pages/Tooltip/TooltipPage.razor
- src/Core/Components/Tooltip/FluentTooltip.razor.cs
- src/Core/Components/Tooltip/FluentTooltip.razor.js
- src/Core/Infrastructure/LibraryConfiguration.cs
- tests/Core/Tooltip/FluentTooltipTests.cs
Following request #1564, we have added a `HideTooltipOnCursorLeave` attribute to **FluentTooltip** components and also for global configuration. 
```csharp
builder.Services.AddFluentUIComponents(configuration =>
{
configuration.HideTooltipOnCursorLeave = true;
});
```
This allows you to keep the default behavior
But also to activate a new behavior.
> [FluentTooltip] Add the HideTooltipOnCursorLeave property

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
Following this discussion #1563, we added 2 new attributes to the Autocomplete component.
> [FluentAutocomplete] Add IconDismiss adn IconSearch

- src/Core/Components/NumberField/FluentNumberField.razor
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameters.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Filled.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Outline.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AutoFocusParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_ClassParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_DataListParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_Default.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_DisabledParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_HideStepParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_IdParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_Label.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_LabelTemplate.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MaxLengthParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MaxParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MinLengthParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MinParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_NameParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_PlaceholderParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_ReadOnlyParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_RequiredParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_SizeParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_StepParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_StyleParameter.verified.html
- Fix #1531 by using web components current-value instead of value. Confirmed this is correct by looking at Fluent UI web component and FAST Explorer markup (both show no `value` attribute being used.
- Also updated verified files for tests
> Fix #1531 by using web components current-value instead of value.

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Menu/Examples/MenuNested.razor
- src/Core/Components/Menu/FluentMenu.razor
- src/Core/Components/Menu/FluentMenu.razor.cs
- Fix visual inconsistency with the FluentMenu by adding a border radius to the anchored region surrounding the menu
- Fix context menu cannot be closed without selecting a menu option by adding an overlay
> FluentMenu fixes

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Tabs/Examples/TabsDefault.razor
- examples/Demo/Shared/Pages/Tabs/TabsPage.razor
- src/Core/Components/Tabs/FluentTab.razor
- src/Core/Components/Tabs/FluentTab.razor.cs
If not specified, a default `FluentProgress` component will be displayed when `DeferredLoading=true` (this is the same as in currrent situation)
> Add LoadingContent parameter to FluentTab

- examples/Demo/Shared/Infrastructure/ServiceCollectionExtensions.cs
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- examples/Demo/Shared/Shared/DemoNavMenu.razor
- examples/Demo/Shared/Shared/DemoNavMenuItem.razor
- examples/Demo/Shared/Shared/DemoNavProvider.cs
- examples/Demo/Shared/Shared/DemoSearch.razor
- examples/Demo/Shared/Shared/DemoSearch.razor.cs
- examples/Demo/Shared/Shared/NavItem.cs
- examples/Demo/Shared/wwwroot/css/site.css
from
to
Example when typing valid content:
Note: Hides on mobile - future work could make it nice & responsive. Probably an Icon only button that pops up a fullscreen overlay
Fixes #1578 
Manually test the nav menu looks the same (I tested each item 1 by 1 & saw no difference).
Test that the search bar behaves as a nice UX.
~~- [ ] I have added tests for my changes.~~
Not done - No tests in Demo site
> feat: Add global search bar

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
- tests/Core/Button/FluentButtonTests.FluentButton_BackgroundColor.verified.razor.html
- tests/Core/Button/FluentButtonTests.FluentButton_BackgroundColorColor.verified.razor.html
- tests/Core/Button/FluentButtonTests.FluentButton_Color.verified.razor.html
- tests/Core/Button/FluentButtonTests.razor
1. Remove the `custom-id` attribute to use the default `id` attribute (if not set, a default value is assigned).
2. Use the `InlineStyleBuilder' utility to create an inline custom style like this.
```razor
<FluentButton BackgroundColor="#ff0000" Color="#00ff00">My button</FluentButton>
```
will generate...
```html
<style>
#f7e40a894::part(control) { background: padding-box linear-gradient(#ff0000, #ff0000), border-box #ff0000; color: #00ff00; }
#f7e40a894::part(control):hover { opacity: 0.8; }
</style>
<fluent-button type="button" id="f7e40a894">My button</fluent-button>
```
> [FluentButton] Update the Button custom style for BackgroundColor and Color properties

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAccentColor.razor
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAppearance.razor
- examples/Demo/Shared/Pages/MenuButton/MenuButtonPage.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor.cs
This PR fixes #1593 and #1594 by:
- adding a FluentOverlay so clicking outside the menu closes it
- Adding a `ButtonAppearance` parameter to make changing the button appearance possible
An example has been added to the deom to show this.
Example of the ovverlay:
Also, source comments have been added and a documentation section is added to the menu button page.
> MenuButton changes and additions

- examples/Demo/Shared/Pages/Card/CardPage.razor
- examples/Demo/Shared/Pages/Card/Examples/CardMinimalStyle.razor
- src/Core/Components/Card/FluentCard.razor
- src/Core/Components/Card/FluentCard.razor.cs
- src/Core/Components/Card/FluentCard.razor.css
- tests/Core/Card/FluentCardTests.FluentCard_MinimalStyle.verified.html
- tests/Core/Card/FluentCardTests.cs
By default the **FluentCard** component is a visual container and design system provider. Cards are snapshots of content that are typically used in a group to present collections of related information. Thus, by design, the **FluentCard** component includes all the styles required for a good representation of the other components included in it. This adds a large number of styles such as `justify-content; align-items; gap; width;` and **over 80 CSS variables**. The code generated can therefore become very important, especially if you use this component several times, for example in a list or during a foreach.
To avoid this, you can use the **MinimalStyle** property. This will remove all the default styles from the **FluentCard** component. This will allow you to use the **FluentCard** …
> [FluentCard] Add MinimalStyle property

- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.js
- src/Core/Components/Pagination/PaginationState.cs
Fix #1596: Pagination state is not updating in the UI when filtering returns less pages of results than the current page index using a FluentDataGrid with ItemsProvider in FluentPaginator
- Add .resizable class to header cell when ResizableColumns is true
- Call enableColumnResizing when finished collecting columns
- Make enableColumnResizing callable from c# side
- Change SetTotalItemsCount to do both SetCurrentPageIndexAsync (if criteria met) and do regular work
> Fix #1596 (very long title, see description)

- src/Core/Components/List/FluentCombobox.razor.cs
in #1485 it was made possible to set the selected value from code by implementing the OnParameterAsync for the FluentCombobox, however there was a small bug that prevented it from being cleared by code, and when null was set it would just revert back to the previous selection. 
this fix allows it to be cleared by code when needed 
Our use case was when we were clearing the form after a submit or pressing the reset button (which set the form to a new instance)
#1485 
this can be tested by adding these buttons to `ComboboxWithOptionTemplate.razor` : 
```
<FluentButton OnClick=@(() => {Person = null!; StateHasChanged();})>Reset</FluentButton>
<FluentButton OnClick=@(() => {Person = Data.People.Last(); StateHasChanged();})>Set</FluentButton> 
```
my test scenario was : 
* select person
* …
> fix: allow FluentCombobox to be cleared from code

- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/FluentCombobox.razor.js
Fix #1618 by re-using FluentTextField script to set autocomplete attribute to oiff for a FluentCombobox
> Re-use/re-purpose FluentTextField script for FluentCombobox

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Menu/Examples/SimpleMenuExample.razor
- src/Core/Components/Menu/FluentMenu.razor
- src/Core/Components/Menu/FluentMenu.razor.cs
To reply to this issue https://github.com/microsoft/fluentui-blazor/issues/1640, we need to add two attributes: VerticalThreshold and HorizontalThreshold (was already present.
In this way, you can set limit margins to automatically reposition the Menu component.
> [Menu] Add Threshold attributes

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteManyItems.razor
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
This PR implements the virtualization feature for FluentAutocomplete discussed here #1638 
For me the implementation works fine and greatly improves the initial rendering performance and the reactivity when a search is done on that list. The improvement can be checked by changing the Virtualize Parameter in the Autocomplete with Many Items Demo example.
Additionally, if the MaximumOptionsSearch is set to a value smaller than 0, it is disabled. With this change the OnOptionsSearch implementer can decide on their own how many items should be displayed. E.g. when a search text is active the displayed items can be reduced to n results. But when e.g. no Search text is active all items can be shown by default.
This is a breaking change:
Before: MaximumOptionsSearch < 0 --> empty list is …
> Virtualization for FluentAutocomplete

- examples/Demo/Shared/Components/TableOfContents.razor.cs
- src/Core/Components/Anchor/FluentAnchor.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/Divider/FluentDivider.razor.cs
- src/Core/Components/HorizontalScroll/FluentHorizontalScroll.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
- src/Core/Components/Overflow/FluentOverflow.razor.cs
- src/Core/DesignTokens/DesignToken.razor.cs
- src/Core/Utilities/JSModule.cs
Replace 
```
catch (JSDisconnectedException)
```
with
```
catch (Exception ex) when (ex is JSDisconnectedException ||
ex is OperationCanceledException)
```
> [Misc] Fix #1652 by also checking for OperationCanceledException

- src/Core/Components/InputFile/FluentInputFile.razor.cs
As the title says. Fixes #1656 by not calling into JS when it is not yet available.
> [InputFile] Replace OnInitializedAsync with OnAfterRenderAsync

- examples/Demo/Shared/Pages/InputFile/InputFilePage.razor
FluentInputFile does not work with serverside blazor in conjuction with Autofac IoC.
This PR contains a code snippet in the demo site for the workaround. -> https://www.fluentui-blazor.net/InputFile
The following root issue is documented below
[aspnetcore#38842](https://github.com/dotnet/aspnetcore/issues/38842#issuecomment-1342540950)
> Demo site - Added InputFile 'known issues' section

- CONTRIBUTING.md
- examples/Demo/Shared/Shared/DemoNavProvider.cs
Corrections and additions to **CONTRIBUTING.md**. 
- requirement for NodeJS is not noted
- there was still a reference to FAST-Blazor
- error in cloning with SSH
> Minor corrections to CONTRIBUTING.md

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/AppBar/AppBarPage.razor
- examples/Demo/Shared/Pages/AppBar/Examples/AppBarClick.razor
- src/Core/Components/AppBar/FluentAppBarItem.razor
- src/Core/Components/AppBar/FluentAppBarItem.razor.cs
And also add an example of using this:
Fix #1696
> Add OnClick to AppBarItem

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Persona/Examples/PersonaNoImage.razor
- src/Core/Components/List/FluentPersona.razor
- src/Core/Components/List/FluentPersona.razor.cs
- src/Core/Components/List/FluentPersona.razor.css
- tests/Core/List/FluentPersonaTests.FluentPersona_Initials-NoName.verified.html
Manage the empty `Name=""` to display a **Persona** without other properties.
- Adding `@attributes`. 
- Adding `OnClick` event.
- Adding `String.IsNullOrEmpty(Name)` to not generate the code if content of name is empty.
```xml
<FluentPersona Name="Lydia Bauer"
ImageSize="50px"
Status="PresenceStatus.Busy"
StatusSize="PresenceBadgeSize.Small">
</FluentPersona>
<FluentPersona Initials="LB" ImageSize="50px" />
<FluentPersona ImageSize="50px" />
```
Unit tests updated and verified.
> [FluentPersona] Manage the empty Name

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Pagination/FluentPaginator.razor
- src/Core/Components/Pagination/FluentPaginator.razor.cs
Adding in the ability to disable the pagination buttons on the Pagination control.
There are scenarios where a user can click the pagination navigation buttons faster than the navigation can complete (e.g. dynamically loading content).  In these scenarios, it is useful to be able to disable the pagination navigation buttons until the navigation has completed.
This pull request adds to the Pagination component:
* Disabled
* None
* None
No pagination tests exist to update.
> feat(pagination): Adding in Disabled parameter to Pagination component

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
Fix #1707 by:
- If no content, move ProgressRing to content part (like icon) 
- Make Progress ring a bit smaller then icon to not make button bigger in Loading state
> Avoid padding loading icon on button when no text 

- examples/Demo/Shared/Components/MarkdownSection.razor
- examples/Demo/Shared/Components/MarkdownSection.razor.css
Fixes issue where markdown tables are not showing borders.
[Design tokens page](https://www.fluentui-blazor.net/DesignTokens) on demo site shows
Default styling does not provide borders
How are the aesthetics - border width and padding?
> [MarkdownSection] fixes border not showing in markdown tables

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeExample.razor
- src/Core/Components/KeyCode/FluentKeyCode.razor
- src/Core/Components/KeyCode/FluentKeyCode.razor.cs
- src/Core/Components/KeyCode/FluentKeyCode.razor.js
- src/Core/Components/KeyCode/FluentKeyCodeProvider.razor
- tests/Core/KeyCodeProvider/FluentKeyCodeTests.razor
Adding a `ChildContent` property and a ´ElementReference` to apply the KeyCode engine to the **FluentKeyCode** content.
If the `ChildContent` is filled, the `Anchor` attribute is no longer used (and is ignored).
A new `GlobalDocument` property defines the component as global to the page, using the DOM object `document`.
Example:
```xml
<FluentKeyCode OnKeyDown="@KeyDownHandler">
Hello World
</FluentKeyCode>
```
The HTML result will be:
```html
<span>Hello World</span>
```
No
Updated
> [FluentKeyCode] Allow content to avoid using the Anchor property

- examples/Demo/Shared/Components/MarkdownSection.razor.css
- examples/Demo/Shared/Components/MarkdownSectionPreCodeExtension.cs
- examples/Demo/Shared/Components/MarkdownSectionPreCodeRenderer.cs
- examples/Demo/Shared/Components/MarkdownSectionPreCodeRendererOptions.cs
- examples/Demo/Shared/wwwroot/docs/DesignTokens.md
- Fixes edge case where the code block is preceded with markdig generic attributes in source markdown document. Pipeline sets _OutputAttributesOnPre_ to true.
- adds an options class for renderer
- addtional attributes are specified in markdig generic attributes format for addtional flexibility
- corrects minor format issue in DesignTokens.md
- Edge case not handled.
I made the default indentation to about 4 charcters. Subjectively thinks it looks better.
> [MarkdownSection] Fixes and enhancements

- examples/Demo/Shared/Pages/Wizard/WizardPage.razor
Looks like I forgot to update the documentation when we changed the architecture and introduced the `FluentEditForm` component for validating an edit form in the `FluentWizardComponent`.  See #1663
> Fix documentation error.

- examples/Demo/Shared/Pages/Footer/Examples/FooterDefault.razor
- src/Core/Components/Footer/FluentFooter.razor.css
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/MainLayout.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css
- src/Templates/content/ComponentsWebAssembly-CSharp/Layout/MainLayout.Auth.razor
- src/Templates/content/ComponentsWebAssembly-CSharp/Layout/MainLayout.NoAuth.razor
- src/Templates/content/ComponentsWebAssembly-CSharp/wwwroot/css/app.css
Footer styling comes with a bad design decission made in the past.  It uses a `display: grid;` together with `flex-direction: column;` which does not make any sense.
We are even overriding it in the demo site ourselves:
With this change we will change it to more sane defaults. Technically it might be considered a breaking change (albeit a small one for sure) but it be will changed in the next release to:
```
.footer {
display: flex;
z-index: 10;
flex-direction: row;
font-family: var(--body-font);
font-weight: normal;
font-size: var(--type-ramp-minus-1-font-size);
line-height: var(--type-ramp-minus-1-line-height);
}
```
For the templates this means that a `FluentSpacer` is added to the footer so the texts will still align left an right. It also allows to remove some then redundant CSS for …
> Fix footer styling. Addresses  #1777

- eng/pipelines/build-core-lib.yml
- eng/pipelines/compute-version-variables.ps1
Adding a script `compute-version-variables.ps1` to compute **AssemblyVersion** and **PackageVersion**.
➡️ `.\compute-version-variables -branchName "users\dvoituron\stuff" -buildNumber "4.6.1.24123.3"`
```
Compute AssemblyVersion and PackageVersion.
##vso[task.setvariable variable=AssemblyVersion]4.6.1.24123
##vso[task.setvariable variable=PackageVersion]4.6.1-preview.24123.3
##vso[task.setvariable variable=ShouldTest]false
-----------------------------------------------
-  Branch                 = PR
-  BuildNumber            = 4.6.1.24123.3
-  PackageSuffix          =
-----------------------------------------------
-> AssemblyVersion        = 4.6.1.24123
-> PackageVersion         = 4.6.1-preview.24123.3
-> ShouldTest             = false
-----------------------------------------------
``` …
> [Pipelines] Add compute-version-variables.ps1 to update the YAML file

- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/wwwroot/app.css
- src/Templates/content/ComponentsWebAssembly-CSharp/wwwroot/css/app.css
[The issue #1806](https://github.com/microsoft/fluentui-blazor/issues/1806) will be solved
I've also auto indented CSS files
And I removed the empty CSS rule in site.css
```
nav ul li {
}
```
> Css files improvements

- WHATSNEW.md
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.js
- src/Core/Components/DataGrid/FluentDataGridCell.razor.css
- src/Core/Components/DataGrid/Infrastructure/InternalGridContext.cs
- src/Core/Components/Dialog/Services/DialogService-Dialog.cs
Previosly when a sort was executed on a DataGrid, (by clicking on a column header button or pressing enter when the column header button is focused), there was no option to undo that. 
With this PR it is now possible to right click on the sorted colum header button to clear the sort and restore it to the default/start situation. **updated: or use Ctrl+Enter to remove the sorting when the column header button is focused** 
When a grid has not sort specified, it just goes back to its initial state. When thare was a defaut sort specified, it will be restored:
Based on discussion in #283
> [DataGrid] Add remove sort capability

- examples/Demo/Shared/Pages/Progress/Examples/ProgressStrokeExample.razor
- examples/Demo/Shared/Pages/ProgressRing/Examples/ProgressRingStroke.razor
Adjusted dropdown widths as values were getting cutoff.
Increased dropdown widths so values would not get cut off, and aligned dropdown width for Progress and Progress ring stroke examples (made them the same).
**Before:**
**After:**
Visually tested.
> [Docs] Update Progress stroke examples dropdowns

- examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeGlobalExample.razor.css
The key text was hard to read in dark mode, changed CSS so text looks good in both modes.
Just made text color black so the key text was more readable in both modes.
**Before:**
(Hard to read)
**After:**
Visually tested. open to other solutions.
> [Docs] Update KeyCodeGlobalExample.razor.css to fix dark mode visuals

- examples/Demo/Shared/Pages/Highlighter/Examples/HighlighterDefault.razor
Replaced input with FluentTextField in Highlighter example.
The input had a white background and I was in dark mode so the non-fluent component stood out. Just replaced with equivalent fluent component.
**Before:**
**After:**
Visually tested and tested by hand.
> [Docs] Update Highlighter example to use FluentTextField instead of input

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Base/FluentInputBaseHandlers.cs
Fix #1830 by adding a check to see if NotifyFieldChanged has already been called.
```
protected virtual async Task ChangeHandlerAsync(ChangeEventArgs e)
{
var _notifyCalled = false; //<--👈added
var isValid = TryParseValueFromString(e.Value?.ToString(), out TValue? result, out var validationErrorMessage);
if (isValid)
{
await SetCurrentValueAsync(result ?? default);
_notifyCalled = true; //<--👈added
}
else
{
if (FieldBound && CascadedEditContext != null)
{
_parsingValidationMessages ??= new ValidationMessageStore(CascadedEditContext);
_parsingValidationMessages.Clear();
_parsingValidationMessages.Add(FieldIdentifier, validationErrorMessage ?? "Unknown parsing error");
}
}
if (FieldBound && !_notifyCalled)  //<--👈changed
{
CascadedEditContext?.NotifyFieldChanged(FieldIdentifier);
}
}
```
> [Input] NotifyFieldChanged is called twice for all FluentInputBase derived components

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAccentColor.razor
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAppearance.razor
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonManual.razor
- examples/Demo/Shared/Pages/MenuButton/MenuButtonPage.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor.cs
Based on issue #1847 I've added a `ChildContent` parameter to MenuButton. This allows for manually supplying the `FluentMenuItem` children and thereby use all it's parameters (like Disabled)
An example has been added
> [MenuButton] Add ChildContent so items can be supplied manually

- examples/Demo/Shared/Infrastructure/AppVersionService.cs
- examples/Demo/Shared/Infrastructure/CacheStorageAccessor.cs
- examples/Demo/Shared/Infrastructure/HttpBasedStaticAssetService.cs
- examples/Demo/Shared/Infrastructure/IAppVersionService.cs
- examples/Demo/Shared/Infrastructure/ServiceCollectionExtensions.cs
- examples/Demo/Shared/Shared/DemoMainLayout.razor.cs
Clears the browser cache when the demo site is started. 
Old versions of the markdown are retained between sessions. So when a new version of the site is released, new markdown content will not be downloaded if an older version is cached.
For example, the WhatsNew page continues to render previous version.
I've made the CacheStorageAccessor a singleton and provided a flag to check if the cache has been previously cleared.
I would have preferred being to _tag_ the cache but was not sure if the extra effort was necessary. That way, the cache would only be cleared if there is a new version or build.  Thoughts?
> [Demo & docs] Clears demo site cache on startup if new version

- src/Core/Components/Slider/FluentSlider.razor.cs
- src/Core/Components/Slider/FluentSlider.razor.js
[FluentSlider] Fixes thumb redraw issues (Fix for #1836)
- thumb not being redrawn when min or max is changed as per #1836 
- unable to programmtically change thumb value
Part of this fix is dependent on the implementation of the underlying [fast slider](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/slider/slider.ts) component. It calls the `setThumbPositionForOrientation` function which is marked as private.
https://github.com/microsoft/fast/blob/5b2b801208a86c1d342feff49961f5c490ad247e/packages/web-components/fast-foundation/src/slider/slider.ts#L338-L355
> [FluentSlider] Fixes thumb redraw issues (Fix for #1836)

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRankSort.razor
- src/Core/Components/DataGrid/Columns/GridSort.cs
- tests/Core/DataGrid/GridSortTests.cs
This PR extends missing GridSort overloads including an IComparer
1. GridSort<TGridItem> ByDescending<U>(Expression<Func<TGridItem, U>> expression, IComparer<U> comparer)
2. GridSort<TGridItem> ThenAscending<U>(Expression<Func<TGridItem, U>> expression, IComparer<U> comparer)
3. GridSort<TGridItem> ThenDescending<U>(Expression<Func<TGridItem, U>> expression, IComparer<U> comparer)
---
Additionally add methods to sort for a second column that is not affected by the sort direction
1. GridSort<TGridItem> ThenAlwaysAscending<U>(Expression<Func<TGridItem, U>> expression)
2. GridSort<TGridItem> ThenAlwaysAscending<U>(Expression<Func<TGridItem, U>> expression, IComparer<U> comparer)
3. GridSort<TGridItem> ThenAlwaysDescending<U>(Expression<Func<TGridItem, U>> expression)
4. public …
> Extend GridSort possibilities

- src/Core/Components/AppBar/FluentAppBar.razor
- src/Core/Components/AppBar/FluentAppBar.razor.css
- src/Core/Components/AppBar/FluentAppBarItem.razor
- src/Core/Components/AppBar/FluentAppBarItem.razor.css
- tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_ChildContent.verified.razor.html
- tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_Default.verified.razor.html
- tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_IconActive.verified.razor.html
- tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_NoText.verified.razor.html
- tests/Core/AppBar/FluentAppBarItemTests.FluentAppBarItem_Tooltip.verified.razor.html
- tests/Core/AppBar/FluentAppBarTests.FluentAppBar_ChildContent.verified.razor.html
- tests/Core/AppBar/FluentAppBarTests.FluentAppBar_NoPopoverSearch.verified.razor.html
- tests/Core/AppBar/FluentAppBarTests.FluentAppBar_Overflow.verified.razor.html
Fixing https://github.com/dotnet/aspire/issues/3397 by applying `role="navigation"` for AppBar and removing any roles for AppBarItems
Fix #1864
> [AppBar] Apply role requirements 

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRankSort.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
As mentioned here #1860, the PropertyColumn does not support the SortBy parameter although it is listed in the documentation.
This PR keeps the default behaviour of the PropertyColumn by providing a default sorting configuration but additionally adds the possibility to set a custom SortBy implementation.
> [DataGrid] Add SortBy parameter support for PropertyColumn

- examples/Demo/Shared/Components/SiteSettingsPanel.razor
- src/Core/Components/Popover/FluentPopover.razor
- src/Core/Components/Popover/FluentPopover.razor.cs
Adds `FixedPlacement` parameter to `FluentPopover`  component.
Fixes #1879 
I just copied the same summary information from the `FluentAnchoredRegion` `FixedPlacement` parameter. It seemed appropriate.
> [FluentPopover] adds FixedPlacement parameter

- src/Core/Components/List/ListComponentBase.razor.cs
Fix #1703 by only returning a value from `GetOptionDisabled` if an actual lambda is supplied. In previous situation the value of `Disabled` (from the Select itself) would be returned which effectively disabled every option if Disabled was set to true and thereby making them not setable
> [FluentSelect] Allow value to be set when component is disabled

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Grid/Examples/GridDefault.razor
- examples/Demo/Shared/Pages/Grid/GridPage.razor
- src/Core/Components/Grid/FluentGrid.razor
- src/Core/Components/Grid/FluentGrid.razor.cs
- src/Core/Components/Grid/FluentGridItem.razor
- src/Core/Components/Grid/FluentGridItem.razor.cs
- tests/Core/Grid/FluentGridTests.razor
**AdaptiveRendering** allows you not to generate the HTML code of the **FluentGridItem** that respects the `HiddenWhen`. In other words, when `AdaptiveRendering=false` (default), the content of the **FluentGridItem** is simply hidden by CSS styles, whereas if `AdaptiveRendering=true`, the content of the **FluentGridItem** is not rendered by Blazor. In certain cases where this content is important, it may be more efficient not to generate the HTML code instead of simply hiding it.
```xml
<FluentGrid AdaptiveRendering="true">
...
</FluentGrid> 
```
> [FluentGrid] Add AdaptiveRendering property

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridDynamicColumns.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Based on #1901. You can now do:
```
<FluentDataGrid Items="@Data.People" Style="width: 500px;">
<PropertyColumn Title="ID" Property="@(c => c.PersonId)" Sortable="true" Width="100px" />
@if (showName)
{
<TemplateColumn Title="Name" Width="200px">
<strong>@context.LastName</strong>, @context.FirstName
</TemplateColumn>
}
@if (showBirthDate)
{
<PropertyColumn Title="Birth date"
Property="@(c => c.BirthDate)"
Format="yyyy-MM-dd"
Sortable="true"
Width="200px"/>
}
</FluentDataGrid>
```
instead of using `GridTemplateColumns`
> [FluentDataGrid] Add column Width parameter

- src/Core/Components/Wizard/FluentWizardStep.razor.css
This PR fixes the `.fluent-wizard-icon-number` style to center the **Bullet Number** when no default style (Reboot) styles are defined.
> [FluentWizard] Fix the Wizard bullet number style

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DateTimes/Examples/DatePickerDefault.razor
- src/Core/Components/DateTime/CalendarTitles.cs
- src/Core/Components/DateTime/FluentCalendar.razor.cs
- src/Core/Components/DateTime/FluentCalendarBase.cs
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
- tests/Core/DateTime/FluentDatePickerTests.cs
Enhancement for selecting a different view, month or year, and a custom DateTimeFormat
FluentDatePicker is missing the possibility to select view like month or year which is available in FluentCalendar. 
Create a FluentDatePicker, set view to desired choice of Month or Year. Possibility to add custom DateTimeFormat
> [Fluent DatePicker] Enhance for month /year selection 

- examples/Demo/Shared/Pages/ProfileMenu/Examples/ProfileMenuCustomized.razor
- examples/Demo/Shared/Pages/ProfileMenu/Examples/ProfileMenuDefault.razor
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- examples/Demo/Shared/wwwroot/css/site.css
This PR removes the ProfileMenu for the demo site header because it gives the impression that your are logged in with someone elses account. 
It also changes the samples to show the profile image/initials at the end of the container so the menu can be seen in full on a small screen device as well.
> [ProfileMenu] Remove ProfileMenu from demo site header and change examples

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Tabs/FluentTabs.razor
- src/Core/Components/Tabs/FluentTabs.razor.cs
Tiny PR. Title says it all.
Probably never been caught before because we don't have good unit tests fo this one yet...
> [FluentTabs] Not using ClassValue and StyleValue when rendering

- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridCustomPaging.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Fix #1954 and change custom paging example to show scrollable grid on a smaller screen.
With the new `Width` parameter, the grid-template-colums value gets genareted based on what widths are supplied. In case nothingis pecified we used `auto`. This can lead to undesired effects where column cells have different widths per row (for the same column) With this PR we change the default value to `1fr`
> [DataGrid] Change column width when using generated value 

- src/Core/Components/NavMenu/FluentNavGroup.razor
- src/Core/Components/NavMenu/FluentNavGroup.razor.cs
- src/Core/Components/NavMenu/FluentNavGroup.razor.css
- src/Core/Components/NavMenu/FluentNavLink.razor
- src/Core/Components/NavMenu/FluentNavMenu.razor
- src/Core/Components/NavMenu/FluentNavMenu.razor.css
- tests/Core/NavMenu/FluentNavGroupTests.FluentNavGroup_Disabled.verified.html
Based on PR #1730, this PR fixes keyboard navigation in the `FluentNavMenu` component.
The nav menu can be opened and closed with keys again when collapsible.
Disabled `FluentNavMenuGroup`s and `FluentNavMenuItem`s can't be focused using keyboard navigation anymore. 
The `FluentNavGroup_Disabled` test was affected by this PR as it seems to have allowed focusing a disabled nav menu group.
> [NavMenu] Fix keyboard navigation

- src/Core/Components/List/ListComponentBase.razor.cs
In `OnSelectedItemChangedHandlerAsync` the SelectedOption was set based on the item selected. The Value and InternalValue were however not set at that time which lead to code being called twice and overwritting the selected value with the earlier value.
> [Lists] Also set Value (and InternalValue) when SelectedOption is set

- examples/Demo/Shared/Pages/AppBar/Examples/AppBarClick.razor
- src/Core/Components/AppBar/FluentAppBar.razor
- src/Core/Components/AppBar/FluentAppBar.razor.css
- src/Core/Components/AppBar/FluentAppBarItem.razor.cs
Changes for fixing #1974 
We have changed the `Href` parameter on the AppBarItem to allow for `null` valure and make it not-`[EditorRequired]` anymore.
In the AppBarItem we now check if `Href` is null. If so, we'll add a class to the AppBarItem indicating it is a local link. We use `NavLink` internally, so an `a` is still rendered and an `active` class is still added. Based on that local class being added, we will remove the CSS that gets applied for 'active' state (i.e remove the accent colored bar)
> [AppBar] Allow for omitting Href on AppBarItems and don't show active status when Href is null or not specified

- src/Core/Components/MessageBar/Message.cs
Fix #1986 by supplying a default value for `MessageOptions.Intent` (with value `MessageIntent.Info`) when invoking ShowMessageBar method with the MessageOptions variant.
> [MessageBar] Supply a default value for the message intent when using MessageOptions

- src/Core/Components/Tabs/FluentTabs.razor.cs
Prevent the error by using `TryAdd` instead of just `Add`
> [Tabs] Prevent error 'An item with the same key has already been added.'

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Icons/FluentIcon.razor
- src/Core/Components/Icons/FluentIcon.razor.cs
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/FluentAutocomplete.razor.js
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_AutofocusAttribute.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClearWithOverlayHiddenOnEmpty_HasNoOverlay.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClear_ShowOverlay.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText_Clears.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.html
[Autocomplete] Accessibility
Solve the issue #2002: In Fluent Autocomplete control, From keyboard, On tab key, it doesn't go to the close button.
> [Autocomplete] Accessibility: Tab key to go to the Close Button

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/ProfileMenu/Examples/ProfileMenuCustomized.razor
- examples/Demo/Shared/Pages/ProfileMenu/Examples/ProfileMenuDefault.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.cs
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.css
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_Customized.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_Default.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_StartEndTemplate.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.razor
Add `StartTemplate` and `EndTemplate` properties to have the possibility to write custom code before/after the button.
The CSS variable `--fluent-profile-menu-hover` can be used to defined the hover background color (overridable).
```xml
<FluentProfileMenu Initials="BG" Style="--fluent-profile-menu-hover: var(--neutral-stroke-focus); padding: 4px;">
<StartTemplate>
Bill Gates
</StartTemplate>
...
</FluentProfileMenu>
```
Updated
> [ProfileMenu] 

- examples/Demo/Shared/Pages/Toast/Examples/ToastConfirmationToasts.razor
Fix #2023 
The problem comes from an invalid `TimeOut` value defined in the example. You must use `10_000` milliseconds.
```csharp
ToastService.ShowInfo("Info confirmation custom settings.", timeout: 10_000)
```
> [Toast Examples] TimeOut setting in milliseconds

- src/Core/Components/List/FluentAutocomplete.razor.cs
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.html
Each time an item is selected from the AutoComplete suggestion list, NVDA displays the item number from the total number of items displayed.
> At the end of the list, if the user continues to press the down arrow, NVDA will continue to announce the contents of the text box. This seems to be a built-in feature of the `fluent-text-field` web component we use, and we can't change it.
Example
https://github.com/microsoft/fluentui-blazor/assets/8350694/ecc09264-0827-4b27-a9fa-74728a92c3ac
> [FluentAutocomplete] Accessibility - Add "1 of 3" aria-label when item is selected

- examples/Demo/Shared/Components/MarkdownSection.razor.css
Adds border around code snippets in markdown document.
There were no borders around code snippets in the markdown document. So appearance was inconsistent with that rendering generated by the `DemoSection` component.
Change is purely aesthetic.
> [MarddownSection] Adds border around code snippets

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DateTime/FluentCalendar.razor.cs
- src/Core/Components/DateTime/FluentCalendarBase.cs
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
When using a FluentDatePicker or FluentCalender inside an EditContext, there are issues with selecting a new value in the Year-view of the calendar. My diagnosis suggests that this comes down to a race condition-like issue between invoking ValueChanged and also notifying the EditContext about changes which will propagate the "old" value to the component through the parameters being updated.
The changes I propose changes the approach for updating value of the FluentCalendar (and thus FluentDatePicker) by utilizing `SetCurrentValueAsync` available on `FluentInputBase`. This approach is similar to other components where `SetCurrentValueAsync` is called as part of `ChangeHandlerAsync`.
The changes proposed fixes the issue.
https://github.com/microsoft/fluentui-blazor/issues/2046
I tested all …
> Fix DatePicker/Calendar not updating under EditContext

- examples/Demo/Shared/Pages/Search/Examples/SearchImmediate.razor
- examples/Demo/Shared/Pages/Search/SearchPage.razor
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/Components/Base/FluentInputBaseHandlers.cs
This pull request applies the use of the internal [`Debouncer`](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Utilities/Debouncer.cs) instead of the `PeriodicTimer` to debounce values. A live demonstration has also been added to the `FluentSearch` page to show how `Immediate` can be used, as opposed to the `oninput` method.
#2030: Using the `FluentSearch` input box, but likely any debounce with `ImmediateDelay`, you can reliably force it to throw an exception, by firing the debounce while the `PeriodicTimer` is resetting itself. The exception shows that the `CancellationToken` used to reset the timer is set to cancelled, as the timer tries to tick.
The only code-flow change I've had to make is to push the invocation of the `ValueChanged` handler back to the Dispatcher, …
> [FluentInputBase] Use `Debouncer` instead of `PeriodicTimer` for debouncing `ValueChanged` handler with `ImmediateDelay`.

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteManyItems.razor
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
Fix #1951 
Add an `ImmediateDelay parameter. Idea was to pass this parameter through to the internal TextField but this proved not to be necessary. Kept the same name though for consistency.
An `Immediate` parameter has not been added because the default behavior on the internal text filed is already to respond to oninput (onchange is not implemented in this component)
> [FluentAutocomplete] Add `ImmediateDelay` parameter

- examples/Demo/Shared/Pages/List/Combobox/Examples/ComboboxFromListOfOptions.razor
- examples/Demo/Shared/Pages/List/Listbox/Examples/ListboxFromListOfOptions.razor
- examples/Demo/Shared/Pages/List/Select/Examples/SelectFromListOfOptions.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.css
- src/Core/Components/List/Option.cs
See linked Discussion for more details.
This PR includes the following changes:
1. **Type Update:**
- Modified the type from [TType?] to [string?] 
2. **Demos Update:**
- Updated all relevant demos to reflect the type change.
#2062 
There were no tests effected.  My manual testing was to run the demo and insure it still worked.  I ran dotnet test.
> Change Option<TType>.Text to `string?`

- examples/Demo/Shared/Pages/Design/DesignTokensPage.razor
- examples/Demo/Shared/Pages/Design/OfficeColorTable.razor
- examples/Demo/Shared/wwwroot/docs/DesignTokens.md
A table at the end of  the [design tokens](https://www.fluentui-blazor.net/DesignTokens) page appears to have been accidentally deleted. 
[Edit] [See comment](https://github.com/microsoft/fluentui-blazor/pull/2073#discussion_r1605828137) Original delete intentional.
[Edit] Added new table based on review comments
- missing table?
- Was the table deletion intentional? If so, the text above it should be changed.
- The text above the table also mentions _accent colors for 17 different Office applications_. I find it confusing and am unsure what it is trying to convey to the reader.
> [Doc] Adds office color table to Design Tokens page

- docs/using-latest-daily.md
- eng/pipelines/build-core-lib.yml
> Inspiration from [Aspire documentation](https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md)
These instructions will get you set up with the latest build of **FluentUI-Blazor**.
Each time a commit is pushed into the `main` ou `dev`, the **Core** package is published on a special NuGet repository.
Install the latest [Visual Studio 2022 Preview version](https://visualstudio.microsoft.com/vs/preview/) for the tooling.
**This package is a preliminary version and are not intended for production use.
It is intended to be used to test the latest feature and bug fix.** 
If you just want the last final release of **FluentUI-Blazor**, the packages are on [NuGet.org](https://www.nuget.org/packages/Microsoft.FluentUI.AspNetCore.Components).
The latest builds are pushed to a …
> [Pipeline] Add a task to publish the preview package in a special feed

- src/Core/Components/Dialog/Services/DialogService.cs
When WASM is published `dotnet publish -c Release`, some classes are not marked as exceptions to avoid a runtime exception.
When calling this command, the following exception occurred.
```csharp
var dialog = await DialogService.ShowConfirmationAsync("Do you want ...");
```
No error occurred.
> [DialogService] Add missing classes to avoid Trimming exceptions

- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTableScrollbars.razor
Added new DataGrid demo to show how to use "Table mode" on `FluentDataGrid` based on discussion #57820
> [Demo ] Add DataGridTableScroll demo

- src/Core/Components/List/FluentCombobox.razor.cs
Checks the object by using the `OptionSelected` parameter when this parameter is set.
Fixes:  #2101
> [ComboBox] bind-SelectedOption is null when using bind-SelectedOption:after 

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- src/Core/Components/DataGrid/Columns/SelectColumn.cs
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Customized_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.razor
Using this **SelectColumn**, you can customize the checkboxes by using `ChildContent` to define the contents of the selection for each row of the grid; or `SelectAllTemplate `to customize the header of this column.
If you don't want the user to be able to interact (click and change) on the **SelectAll** header, you can set the `SelectAllDisabled="true"` attribute.
Fix #2090
```razor
<SelectAllTemplate>
@(context.AllSelected == true ? "✅" : context.AllSelected == null ? "➖" : "⬜")
</SelectAllTemplate>
<ChildContent>
@(SelectedItems.Contains(context) ? "✅" : " ") @* Using SelectedItems         *@
@(context.Selected ? "✅" : " ")                @* Using Property and OnSelect *@
</ChildContent>
```
Updated and verified (no breaking change).
> [DataGrid SelectColum] Allow customization of SelectAll header

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteDefault.razor
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- tests/Core/List/FluentAutocompleteTests.razor
By activating the `SelectValueOnTab` option, the user can select an item from the list using the `Enter` key (as usual), but also the `Tab` key. If the component is "closed", the `Tab` key come back to its usual function of navigating to the next HTML element.
See the request #1435
Unit test added.
> [FluentAutocomplete] Add SelectValueOnTab attribute

- src/Core/Components/Base/FluentInputBase.cs
This PR adds a new parameter ```Field``` (of type ```FieldIdentifier```) to ```FluentInputBase```. I'm working on a system that allows users to create their own dynamic forms, this means my model contains a list of fields and each of those has a base class where the value is stored as an ```object?``` and inheriting classes override this with a specific type. When passing to input components the ```Value``` parameter gets cast to the correct type, but the ```FluentValidationMessage``` component can only be passed the ```object?``` version due to ```FieldIdentifiers``` not supporting the ```UnaryExpression``` that is created by casting. This means that the ```FluentInputBase``` has a different internal ```FieldIdentifier``` due to the unboxing, and means the validation message shows …
> Adds FieldIdentifier parameter to FluentInputBase

- src/Core/Components/Progress/FluentProgress.razor.cs
Add CultureInfo.InvariantCulture to ToString("0.00") in FluentProgress component
As described in #2107 this PR fixes the call to ToString("0.00") adding CultureInfo.InvariantCulture:
https://github.com/microsoft/fluentui-blazor/blob/758dce12b21e91021d67d05d7ddc0268f4266191/src/Core/Components/Progress/FluentProgress.razor.cs#L93
Without this fix --stroke-width couldn't be set correctly for cultures other than the US.
#2107
> [Progress] Fix height in Indeterminate mode by using InvariantCulture

- Directory.Packages.props
- src/Core/Components/Layout/FluentLayout.razor
- tests/Core/Layout/FluentLayoutTests.FluentLayout_Id.verified.razor.html
- tests/Core/Layout/FluentLayoutTests.razor
The Id property was not being set on FluentLayout
Was trying to scope css using Id and noticed it was missing on this component.
Oh yea I fixed the version warning.
```
microsoft\fluentui-blazor\tests\Core\Microsoft.FluentUI.AspNetCore.Components.Tests.csproj : warning NU1603: Microsoft.FluentUI.AspNetCore.Components.Tests depends on FluentAssertions (>= 7.0.0-
tags-7.0.0-tags-7-0-0-alpha-3.1) but FluentAssertions 7.0.0-tags-7.0.0-tags-7-0-0-alpha-3.1 was not found. An approximate best match of FluentAssertions 7.0.0-tags-7-0-0-alpha-3.1 was resolved.
```
Added FluentLayout_Id Test to ensure Id attribute renders
> [Layout] Add Id to the container div

- src/Core/Components/NavMenu/FluentNavGroup.razor.cs
Fix error behavior by changing the toggle logic based on prerendering being true/false
> [NavMenu] Fix double click needed for expanding/collapsing child elements when prerendering is turned off

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/DesignTokens/DesignToken.razor.cs
When working with colors, the Design Token methods work with the `.ToSwatch()` extension to convert a string to a swatch. This does not work in the case of the `.WithDefault` method. To solve this, a string based `.WithDefault` overload has been added.
Fix #2158. Code from that issue has been used to verify the change.
> [DesignToken] Add WithDefault overload

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Descending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Descending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.razor
The publicly exposed method of programmatically setting a DataGrid's sort order requires the user to have a reference to the `ColumnBase<TGridItem>` which the API does not expose. In order to restore the state of a DataGrid, the sort order needs to be settable.
[#2148](https://github.com/microsoft/fluentui-blazor/issues/2148) - DataGrid: add access to columns
I added 2 logical methods that one would sort by. I did find another `internal` method that could have been used but decided to just add these. I think it would be OK to mark `SortByColumnAsync`, 'RemoveSortByColumnAsync', and `ShowColumnOptionsAsync` as `internal` as it is necessary to have a `ColumnBase<TGridItem>` reference in order to execute those methods, which is something that's not exposed outside of the library.
I added new …
> [DataGrid] Allow programmatic sorting of columns by name or index

- src/Core/Components/DataGrid/Columns/SelectColumn.cs
Fix #2163 by adding a `ClearSelection` method to `SelectColumn`
When defining grid like this:
```
<FluentDataGrid TGridItem="CollectionWrapper" Items="@FilteredItems" Pagination="@pagination">
<SelectColumn @ref="selectColumn" TGridItem="CollectionWrapper" SelectMode="DataGridSelectMode.Multiple" @bind-SelectedItems="@SelectedItems" />
```
Method can be called like this:
```
private async Task DeleteCollectionsAsync(MouseEventArgs mouseEventArgs)
{
var itemstodelete = this.SelectedItems
.Select(x => x.designCollectionDTO.DesignCollectionUUID)
.ToArray();
await this.CollectionService.RemoveDesignCollectionsAsync(itemstodelete, CancellationToken.None);
this.selectColumn.ClearSelection();
}
```
Prevents BL0005 warning.
> [DataGrid] Add ClearSelection method to SelectColumn

- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
Fix #2187 (regression) cell height style should not be applied if loading=true
> [DataGrid] Fix LoadingContent height when Virtualize is true

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Splitter/Examples/MultiSplitterDefault.razor
- examples/Demo/Shared/Pages/Splitter/MultSplitterPage.razor
- examples/Demo/Shared/Shared/DemoNavProvider.cs
- src/Core/Components/Splitter/FluentMultiSplitter.razor.cs
- src/Core/Components/Splitter/FluentMultiSplitterPane.razor.cs
- tests/Core/Splitter/FluentMultiSplitterTests.FluentMultiSplitter_Size_Fixed.verified.razor.html
- tests/Core/Splitter/FluentMultiSplitterTests.razor
[FluentMultiSplitter] Fixed panel size
Fixed this issue.
> With a simple `FluentMultiSplitter` having 2 panes, the left pane with no size specified, the right pane with a fixed size.
> The right pane will not have the correct size. 
> 
> See #2175
> [FluentMultiSplitter] Fixed panel size

- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteCustomized.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/FluentAutocomplete.razor.js
Fix the issue #2220, adding a script to display the "selectable" item.
Script added:
```javascript
export function scrollToFirstSelectable(idPopup, goDown) {
const popup = document.getElementById(idPopup);
const item = popup?.querySelector("fluent-option[selectable]")
const next = goDown ? item?.nextElementSibling : item?.previousElementSibling;
if (!!next) {
next.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'start' });
}
}
```
> [Autocomplete] Accessibility: Scrolling not working with keyboard

- examples/Demo/Shared/Pages/Dialog/DialogPage.razor
- examples/Demo/Shared/Pages/MessageBar/MessageBarPage.razor
- examples/Demo/Shared/Pages/MessageServicePage.razor
- examples/Demo/Shared/Pages/Toast/ToastPage.razor
- examples/Demo/Shared/Pages/Tooltip/TooltipPage.razor
Fix same typo in 5 places
Change "provider itself of the component"
to "provider itself or the component"
-->
> [Typo] Fix same typo 5 places

- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
This PR is about adding a section to the [CodeSetup](https://www.fluentui-blazor.net/CodeSetup) page of the documentation containing information to guide users to configure FluentUI for Right-to-Left languages.
#2121
> [Docs] Added RTL section to CodeSetup.md

- src/Core/Components/DateTime/FluentDatePicker.razor.cs
Proposed Fix 2237
Issue when trying to select a date using FluentDatePicker when the Value is null, the selected date does not update the Value. Probable due to the fact that the FluentCalendar is being closed prematurely.
https://github.com/microsoft/fluentui-blazor/issues/2237
Tested while debugging.
> [DatePicker] Fix unable to set when value is null

- src/Core/Components/Splitter/FluentMultiSplitter.razor.css
- src/Core/Components/Splitter/FluentMultiSplitter.razor.js
- src/Core/Components/Splitter/FluentMultiSplitterPane.razor.cs
- tests/Core/Splitter/FluentMultiSplitterTests.FluentMultiSplitter_Size_Fixed.verified.razor.html
By specifying a fixed Panel size and a variable size, the fixed-size panel has the wrong width.
Examples from #2204
> [Multisplitter] Fix width panels

- examples/Demo/Shared/Shared/DemoNavProvider.cs
this PR removes the fragment from the demo navigation for the `/DateTime` link.
> [Demo] Fixes link for Time picker in demo projects

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridMultiSelect.razor
- src/Core/Components/DataGrid/Columns/SelectColumn.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGridCell.razor
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
- tests/Core/DataGrid/FluentDataGridColumSelectTests.razor
Add an `OnCellClick` event and allows restricting the selection of rows to the checkboxes of the select column.
This PR replaces #2160 and fixes #2130 and [#1952 comment](https://github.com/microsoft/fluentui-blazor/pull/1952#issuecomment-2150964551).
```xml
<FluentDataGrid Items="@People" TGridItem="Person">
<SelectColumn TGridItem="Person"
SelectMode="..."
SelectFromEntireRow="@SelectFromEntireRow"    // 👈 New property
@bind-SelectedItems="@SelectedItems" />
<PropertyColumn Width="100px" Property="@(p => p.PersonId)" />
<PropertyColumn Width="300px" Property="@(p => p.Name)" />
<PropertyColumn Width="150px" Property="@(p => p.BirthDate)" />
</FluentDataGrid>
```
Verified and added
> [DataGrid] Add OnCellClick event and SelectColumn.SelectFromEntireRow property

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
- src/Core/Infrastructure/LibraryConfiguration.cs
- src/Core/Utilities/CssBuilder.cs
- tests/Core/Utilities/CssBuilderTests.cs
The styles used by FluentUI are included in the package.
You don't need to do anything to include them in your project.
You can always add your own styles, using the `class` or `style` attribute on the components.
By default, the classes are organised and checked by the component itself (in particular by checking that the class names are valid).
Some frameworks, such as **Tailwind CSS**, add exceptions to class names (e.g. `min-h-[16px]` or `bg-[#ff0000]`).
In this case, you need to disable class name validation by adding this code to your `Program.cs` file:
```csharp
builder.Services.AddFluentUIComponents(options =>
{
options.ValidateClassNames = false;
});
```
> [CssBuilder] Add CssBuilder.ValidateClassNames 

- src/Core/Components/DateTime/FluentTimePicker.razor.cs
- tests/Core/DateTime/FluentTimePickerTests.cs
This PR adds a null check for the `FluentTimePicker` which converts empty strings to `DateTime?`.
* #2230
I've added a new UNIT Test `FluentTimePicker_EmptyStringToNull` to verfiy the results.
> [TimePicker] Add null check for empty string

- examples/Demo/Shared/Components/ApiDocumentation.razor
- examples/Demo/Shared/Components/ApiDocumentation.razor.cs
Show default value for string and Icon
> [Docs] Improve API documentation by showing default icon and string values

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Badge/FluentBadge.razor
- src/Core/Components/Icons/FluentIcon.razor
- src/Core/Components/Icons/FluentIcon.razor.cs
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_MaxAutoHeight_Opened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.razor.html
At the request of the Accessibility team, the **Dismiss** buttons on the selected elements must be focusable. 
To achieve this, we need to add a `Focusable` property to the `FluentIcon` component, which is itself used by the `FluentBadge` component.
https://github.com/microsoft/fluentui-blazor/assets/8350694/5aea9fb2-e3b2-4efe-abb9-8b5106b3f0d1
Updates
> [AutoComplete] Allow focusable Badge dismiss buttons (accessibility)

- examples/Demo/Shared/Pages/Toolbar/Examples/ToolbarDefault.razor
- tests/Core/Dialog/FluentDialogServiceTests.FluentDialogService_Default.verified.razor.html
- tests/Core/Dialog/FluentDialogServiceTests.FluentDialogService_HeightUnset.verified.razor.html
- tests/Core/Dialog/FluentDialogServiceTests.FluentDialog_RenderFragment.verified.razor.html
- tests/Core/Dialog/FluentDialogServiceTests.razor
- tests/Core/Dialog/FluentDialogTests.FluentDialog_Default.verified.razor.html
- tests/Core/Dialog/FluentDialogTests.FluentDialog_HeaderFooter.verified.razor.html
- tests/Core/Dialog/FluentDialogTests.razor
After merging in the v3 DialogHeader changes, the Dialog tests were failing. This PR rectifies that,
> Fix failing Dialog tests

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Slider/FluentSlider.razor
- src/Core/Components/Slider/FluentSlider.razor.cs
There was still a situation in which the slider could get stuck. This PR fixes that and with that fix the javascript workaround we had before is no longer needed.
Image shows the test we used originally with the new code. Tested both on Server and WebAssembly
As I am needing this to finsih another PR, I'm taking the liberty to self-approve this
> [Slider] Refactor code after PR #2265

- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
The properties `Disabled` and `ReadOnly` was not correctly verified.
No change - Validated
> [Autocomplete] Fix ReadOnly and Disable properties

- examples/Demo/Shared/Shared/DemoNavMenuItem.razor
- examples/Demo/Shared/Shared/NavItem.cs
- src/Core/Components/NavMenu/FluentNavGroup.razor.cs
- src/Core/Components/NavMenu/FluentNavMenu.razor
We made a change to the NavMenu to accommodate working with prerendering set to false. See #2097 and PR #2133. With this PR we are reverting that change. It lead to a couple of other unwanted (side) effects.
What happens when prerendering is false is that the page script component gets triggered and expanding/collapsing is actually being done by the script instead of by the interactive code. This is not desired so we need to tell the menu to **not** use the page script when in interactive server rendermode. Fortunately this can easily be done by setting the `Data` parameter of the `FluentNavMenu` to a not null value, so something like:
```
Data="@("no-pagescript")
```
Data is of type `object` so you cannot set a string value to it directly.
> [NavMenu] Revert fix for when prerender set to false

- src/Core/Components/List/FluentPersona.razor.cs
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_Default.verified.razor.html
This PR adds the initials to the **FluentPersona** used in the popup panel, based on the `FullName` property.
See #2286
```xml
<FluentProfileMenu FullName="First Last" />
```
Updated
> [ProfileMenu] Fix the initials inner the popup panel

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
- src/Core/Components/DataGrid/Columns/SelectColumn.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGridCell.razor
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
Add these overloadable methods to the `ColumnBase` class.
- `OnRowClickAsync` is triggered when the user clicks on a row.
- `OnRowKeyDownAsync` is triggered when the user presses a key on a row.
- `OnCellClickAsync` is triggered when the user clicks on a cell of this column.
- `OnCellKeyDownAsync` is triggered when the user presses a key on a cell of this column.
This code was moved to the `SelectColumn` class.
```csharp
protected internal override Task OnRowClickAsync(FluentDataGridRow<TGridItem> row)
{
if (SelectFromEntireRow == true && row.RowType == DataGridRowType.Default)
{
return AddOrRemoveSelectedItemAsync(row.Item);
}
return Task.CompletedTask;
}
protected internal override Task OnRowKeyDownAsync(FluentDataGridRow<TGridItem> row, KeyboardEventArgs args)
{
if (SelectFromEntireRow …
```
> [DataGrid] Refactoring ColumnBase events

- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
- src/Core/Extensions/EnumExtensions.cs
When a `PropertyColumn` in a data grid defines an expression, it always returns a string value. In case on an enum it just returns the string representation of that value. By using `DisplayAttribute` it is possible to define a display friendly name for that value. With this PR that defined value will be used, if specified.
So using the following example code:
```
@using System.ComponentModel.DataAnnotations
<FluentDataGrid Items="@employees.AsQueryable()" >
<PropertyColumn Property="@(e => e.Id)" />
<PropertyColumn Property="@(e => e.FullName)" />
<PropertyColumn Property="@(e => e.Subdivision)" />
<PropertyColumn Property="@(e => e.Position)" />
</FluentDataGrid>
@code {
public enum Positions
{
employee,
[Display(Name = "HR Manager (DA)")]
HrManager,
[Display(Name = "Project Manager …
```
> [DataGrid] Make `PropertyColumn` use `DisplayAttribute` value for enum

- src/Core/Components/List/FluentCombobox.razor.cs
- tests/Core/List/FluentComboboxTests.FluentCombobox_ClearSelection.verified.html
- tests/Core/List/FluentComboboxTests.cs
this fixes #2302 , but is uncertain if it breaks anything again as the null coalesce might have been removed for a reason?
#2302
@vnbaaij , this is the fix i was talking about. Ive also added a unit test while i was at it
Unit tests were added, but can also be tested by adding the code specified in the issue
N/A
> [Combobox] Set value if selection is cleared

- src/Core/Components/Dialog/FluentDialogProvider.razor
- src/Core/Components/Dialog/FluentDialogProvider.razor.cs
- src/Core/Components/Dialog/Services/DialogInstance.cs
- src/Core/Components/Dialog/Services/DialogReference.cs
- tests/Core/Dialog/FluentDialogServiceTests.razor
Update the `UpdateDialogAsync` to refresh all data: parameters (title, buttons, ...) and the content.
See #2040 for an example.
```csharp
var dialog = await dialogService.ShowDialogAsync<TestDialogHeaderFooter>(myUser, parameters);
parameters.Title = "My new title";
parameters.PrimaryAction = "Oh yes";
parameters.Content = new() { Id = 2, Name = "Vincent" };
await dialogService.UpdateDialogAsync(dialog.Id, parameters);
```
One unit test added to verify this case.
> [DialogService] Fix UpdateDialogAsync to refresh parameters and content

- examples/Demo/Shared/Pages/List/Combobox/Examples/ComboboxDefault.razor
- examples/Demo/Shared/Pages/List/Select/Examples/SelectDefault.razor
- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Components/List/ListComponentBase.razor
- tests/Core/List/FluentSelectTests.FluentSelect_Placeholder.verified.razor.html
- tests/Core/List/FluentSelectTests.razor
This PR modifies the `FluentSelect` component to correctly handle the `Placeholder` attribute. 
Initially, this attribute is not available for the webcomponent `fluent-select`. But following the #2301 discussion, a workaround is possible by adding a "fake" invisible first element. This allows it to be displayed when the user opens the form for the first time. only. It then disappears when the user selects an item, and is not present in the list displayed on the screen.
Thanks @gotmoo for this tip :-)
```xml
<FluentSelect TOption="Person"
Label="Select a person"
Placeholder="Make a selection..."
... />
```
A unit test has been added to validate this functionality.
> [Combobox, Select] Fix the Placeholder attribute

- WHATSNEW.md
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
- src/Core/Components/AppBar/FluentAppBar.razor.css
The selected AppBarItem icon was not showing in the accent color anymore
> [AppBar] Fix regression with icon active color

- .github/workflows/build-core-lib.yml
- Directory.Packages.props
- Microsoft.FluentUI.sln
- examples/Demo/Shared/Pages/BlazorHybrid.razor
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/Home/Examples/HomeSimpleExample.razor
- examples/Demo/Shared/Pages/Home/Home.razor
- examples/Demo/Shared/Pages/Home/Videos.razor
- examples/Demo/Shared/Pages/RebootPage.razor
- examples/Demo/Shared/Pages/TemplatesPage.razor
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- examples/Demo/Shared/Shared/DemoNavProvider.cs
- examples/Demo/Shared/wwwroot/css/site.css
- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
A fresh coat of paint for the homepage. Plus some updates to the general doc pages.
Less content, better layout, more links to other docs pages. See https://black-pebble-0dc79cb03-2324.westeurope.3.azurestaticapps.net/
> [Docs] Update homepage

- examples/Demo/Shared/Pages/Splitter/Examples/MultiSplitterDefault.razor
- src/Core/Components/Splitter/FluentMultiSplitter.razor.js
See #2321
It seems the `OnResize` event callback of `MultiSplitter` is called each time a mouse click on the "resize bar" is performed - even if the panes / "resize bar" is not moved / resized at all.
Detection of the `mousemove` when the `mouseup` is raised.
> [Multi Splitter] Fix the Splitter OnMouseMove

- examples/Demo/AssetExplorer/Components/Pages/IconExplorer.razor
- examples/Demo/AssetExplorer/Components/Pages/IconExplorer.razor.cs
Update the Variant selector to accept **Light** icons (now, only for 32 pixels)
Site already published.
> [Icon Explorer] Update the Variant selector

- examples/Demo/Shared/Pages/DateTimes/DateTimesPage.razor
- examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
- examples/Demo/Shared/Shared/DemoNavMenuItem.razor
- examples/Demo/Shared/Shared/DemoNavProvider.cs
EDIT: Autocomplete is in the List section.
> [Demo] Date and Autocomplete components to Forms section

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/NumberField/NumberFieldPage.razor
- src/Core/Components/Tabs/FluentTabs.razor
- src/Core/Components/Tabs/FluentTabs.razor.cs
Wrong JS method was being called after refactor/restructuring
Also added note to NumberField page about component being broken
> [Docs] Fix Tabs Dynamic example 

- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
> [DataGrid] Make `Grid` in `ColumnBase` public again

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
- src/Core/Extensions/EnumExtensions.cs
- The Grid property of the `ColumnBase` should not be `public` but `protected`
- The enum extension for getting the display attribute should use the `GetName()` method instead of using `Name` (following C# guidelines)
- When using the new display attribute to use an enum for property value in a column, this should also work for nullable enums. Added a check for that
> [DataGrid] Several issues addressed

- src/Core/Components/Splitter/FluentMultiSplitter.razor.css
- src/Core/Components/Splitter/FluentMultiSplitter.razor.js
As described in issue #2351, the splitter movement was inverted when the RTL direction was applied.
This PR fixes this issue.
No change
> [MultiSplitter] Fix RTL direction

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Wizard/Examples/WizardCustomized.razor
- src/Core/Components/Wizard/FluentWizard.razor.cs
- src/Core/Components/Wizard/FluentWizardStep.razor.cs
When the `ButtonTemplate` property is set, as the documentation states, "Custom Wizard buttons do not trigger the component OnChange and OnFinish events.
In some development projects, it may be simpler to use `WizardStep.OnChange` events. This makes it easier to organize the code.
To trigger this `OnChange` event, we've added a `GoToStepAsync` method that positions the user on the specified step and triggers this event.
Navigate to the specified step, with or without validate the current EditContexts.
- `step` Index number of the step to display
- `validateEditContexts` Validate the EditContext. Default is false.
```razor
<ButtonTemplate>
@{
var index = context;
var lastStepIndex = 3;
<div>
@if (index > 0)
{
<FluentButton OnClick="@(() => MyWizard.GoToStepAsync(0))">Go to first …
```
> [Wizard] Add GoToStepAsync method

- src/Core/Components/Wizard/FluentWizard.razor.cs
- tests/Core/Wizard/FluentWizardTests.razor
Update the Wizard component to honor the FluentFormEdit validation components when @bind-Value is set.
When @bind-Value is set on the Wizard Component the next button will work even if there is a FluentFormEdit component within the FluentWizardStep component and the model is invalid for that WizardStep component.
1. Update a test for FluentWizard_EditForm_EditContextIsInValid_OnNext a @bind-Value to an integer, assert this value will not change to a new value once the next button is clicked.
2. Run the test; expect failure.
3. Update the component to only run the ValueChanged event for Value when it is valid and not cancelled.
4. Run the text; expect success.
> Fix validation when @bind-Value is set for FluentWizard component

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/SplashScreen/Examples/CustomSplashScreen.razor
- examples/Demo/Shared/Pages/SplashScreen/Examples/DialogSplashScreenCustom.razor.cs
- examples/Demo/Shared/Pages/SplashScreen/Examples/DialogSplashScreenDefault.razor.cs
- src/Core/Components/Dialog/Services/DialogService-SplashScreen.cs
Fix #2367 by passing through `parameters.Modal`
Also adjust the samples to show these behaviors
> [SplashScreen] Pass parameters.Modal to `ShowSplashScreen...` methods

- src/Core/Components/DataGrid/FluentDataGrid.razor.js
I've seen that the problem behind the strange resizing effect, is due to the JS method being initialized too many times. 
I've not investigated a lot why but the method `FinishCollectingColumns` in `FluentDataGrid.razor.cs` is being executed each times a user click somewhere in the table. This will always re-execute the js method `enableColumnResizing`. 
I've fixed the strange behavior by editing the js file in order to not re-initialize if the same grid was already initialized. 
Fix #2381
> [DataGrid] Avoid excessive calling of reinitialize method in JavaScript 

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Overflow/Examples/OverflowDefaultExample.razor
- src/Core/Components/Overflow/FluentOverflow.razor.css
- src/Core/Components/Overflow/FluentOverflowItem.razor
- src/Core/Components/Overflow/FluentOverflowItem.razor.cs
- src/Core/Enums/OverflowItemFixed.cs
- Update the PR #2393
- Fix #2390 by moving logic inside popover close code
- Fix #2391 by adding `Fixed` parameter to `FluentOverflowItem`
Update the `fixed` attribute:
- `None`: (Default) If the item is out of the display, it disappears.
- `Fixed`: The element is always visible
- `Ellipsis`: The element is always visible, but its width can be reduced to display "...".
In the second example (After), the first element will always be displayed (fixed), but an ellipse (...)
will be added when the container size is too small.
Note: the element must be able to display this ellipse, which is the case for text (like below) but not for the FluentBadge.
```xml
<FluentOverflow Style="width: 100%;">
<FluentOverflowItem Fixed="OverflowItemFixed.Ellipsis">Aspire;</FluentOverflowItem> …
```
> [Overflow] Add Fixed enumeration

- src/Core/Components/TreeView/FluentTreeItem.razor.cs
In the "unlimited items" example, the first sub-item of an item is never selected.
All other items will update `SelectedItem`, but never the first.
No change
> [TreeView] Fix the first item never selected

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Search/Examples/SearchDefault.razor
- examples/Demo/Shared/Pages/Search/SearchPage.razor
- src/Core/Components/Search/FluentSearch.razor.cs
- src/Core/Components/Search/FluentSearch.razor.js
Follows the same method as used in TextField. Result:
Fix #2394
> [Search] Add AutoComplete parameter

- src/Core/Components/Accordion/FluentAccordion.razor
> [FluentAccordion] Add Id

- src/Core/DesignTokens/DesignToken.razor.cs
- src/Extensions/DesignToken.Generator/DesignTokenGenerator.cs
This issue occurs exclusively in version 4.9.2, downgrading to 4.9.1 resolves the issue.
When injecting any design token and calling `.SetValue()` with any element reference, the `DesignToken` class fails to inject the registered `LibraryConfiguration` causing an `Object reference not set to an instance of an object`  exception to be thrown inside `UrlFormatterExtensions.cs`.
Fix for #2425
```csharp
@using Microsoft.FluentUI.AspNetCore.Components.DesignTokens
<div class="container">
<FluentTextField @ref="Test" @bind-Value=Title></FluentTextField>
</div>
@code {
[Parameter, EditorRequired]
public string Title { get; set; } = null!;
FluentTextField Test;
[Inject]
private Density _density { get; set; } = default!;
protected override async Task OnAfterRenderAsync(bool firstRender)
{
if …
```
> [General] Inject LibraryConfiguring into DesignToken

- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/GenerateRecoveryCodes.razor
- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/Pages/Manage/ResetAuthenticator.razor
There were a couple of `FluentButton` occurrences that used a wrong value for Appearance. This PR corrects that
> [Templates] Replace faulty `Appearance.Filled` with `Appearance.Accent` for buttons

- src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Program.cs
To avoid an error like `Cannot provide a value for property 'LibraryConfiguration'` the services must be included in the Client project.
> [Templates] Fix Template.Client services injection

- src/Core/Components/Wizard/FluentWizard.razor
- src/Core/Components/Wizard/FluentWizard.razor.cs
- tests/Core/Wizard/FluentWizardTests.razor
If the last step is disabled, the component could continue to display this step.
The display of the [Done] button has been revised to show only if there is at least one Enabled step afterwards.
Fix #2497
Added
> [FluenWizard] Fix Done button when last step is disabled

- src/Core/Components/Toast/FluentToast.razor.css
When I set `ToastTopCTAType.Timestamp`, the timestamp width is incorrect, casuing the string to wrap.  As shown below:
https://github.com/microsoft/fluentui-blazor/blob/7b747797a865ff46ee0f7a41771eef21520eb750/examples/Demo/Shared/Pages/Toast/Examples/ToastCommunicationToasts.razor#L33
This PR fixes a width issue where the layout breaks when displayed in an i18n context. The previous implementation used a fixed width, which caused display problems due to varying text lengths in different languages. The changes ensure that the width is flexible and adapts to the content, providing a consistent user experience across all supported languages. Please review the changes and let me know if any adjustments are needed.
> fix: FluentToast width issue when using timestamp in i18n

- src/Core/Components/Base/FluentComponentBase.cs
- src/Core/Components/Layout/FluentLayout.razor
- tests/Core/Components/Base/ComponentBaseTests.cs
- tests/Core/Components/Button/FluentButtonTests.razor
- tests/Core/Components/Icons/FluentIconTests.razor
- tests/Core/Samples/Icons.cs
A global test will verify that all components that inherits from `FluentComponentBase` correctly implement the `Id`, `Class`, `Style` and `AdditionalAttributes` properties.
If not, the following message will be raised.
```
"FluentButton" does not use the "Id" property/attribute (missing HTML attribute id="My-Specific-ID").
```
> [ComponentBase] Add unit tests to validate use of all default attributes (Id, Class, Style, AdditionalAttributes)

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Drag/Examples/DragDropBasic.razor
- src/Core/Components/Drag/FluentDragContainer.razor.cs
- src/Core/Components/Drag/FluentDropZone.razor
- src/Core/Components/Drag/FluentDropZone.razor.cs
- tests/Core/Drag/FluentDragTests.cs
In order to respond to certain situations, such as the possibility of detecting that the user has dropped an item outside the processing zone, we have added the `OnDragEnd` event. This event matches the [dragend event ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragend_event) of the HTML Drag and Drop API
See #2494
> [DragContainer] Add an event "onDragEnd"

- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
> [Docs] Fix a typo

- src/Core/Components/NumberField/FluentNumberField.razor.cs
Copied code from TextField to set a value for AutoComplete. Also re-uses the TextField script..
Fix #2516
> [NumberField] Add AutoComplete parameter 

- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fix #2517 
Previously, we were not storing the initialColumnsWidth value for each DataGrid. With this PR that is changed.
As we only pass a simple `ElementReference` from C# to JS, we don't have any object uniquely identifying each grid. This is solved by setting the `Id` parameter in the `FluentDataGrid` constructor (and rendering it in the `fluent-data-grid` tag which was _not_ being done yet!). The `Id` is then used as the key for the 'dictionary' on the JS side.
> [DataGrid] Fix resizing to initial column widths issue

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Dialog/FluentDialog.razor.cs
- src/Core/Components/Dialog/FluentDialogProvider.razor
- src/Core/Components/Dialog/Parameters/DialogParameters.cs
- src/Core/Components/Dialog/Parameters/IDialogParameters.cs
- src/Core/Components/Dialog/Services/DialogReference.cs
Fix #2542 by
- Adding `Visible` (bool, default = true) to IDialogParameters and DialogParameters
- Set its value in `FluentDialog` Show()/Hide() methods
- In provider, only process dialogreferences where Instance.Parameters.Visible is true
I verified with the following code the the original solution provided with #2310 still works (and tests still pass):
```
@page "/issue-tester"
@using FluentUI.Demo.Shared.Pages.Dialog.Examples
@inject IDialogService DialogService
<FluentButton Appearance="Appearance.Accent" @onclick="OpenDialogAsync">Open Dialog</FluentButton>
@code {
public SimplePerson simplePerson = new() { Firstname = "Jane", Lastname = "Doe", Age = 30 };
private async Task OpenDialogAsync()
{
DialogParameters<SimplePerson> parameters = new()
{
Title = $"Hello …
```
> [Dialog] Fix regression, see #2542 for details

- src/Core/DesignTokens/DesignToken.razor.cs
Because then it will be included twice and that does funky stuff. Like causing issue #2546
Fix #2546
> [Javascript Caching] Do not add version number to lib.module.js file

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DateTimes/Examples/DatePickerDefault.razor
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
- tests/Core/DateTime/FluentDatePickerTests.cs
1. Added `OnDoubleClick` event to DatePicker component.
2. Added `DoubleClickToDate` parameter to DatePicker component.
3. Updated DatePickerDefault page in demo site to add `DoubleClickToDate` option
The PR was related to
1. The discussion #2524 How can I extend FluentDatePicker to support double-click event on its text field?
2. The PR #2563 [DatePicker] Added OnDoubleClick event and DoubleClickToToday parameter.
This is the first PR of the 2 separated PRs asked by @dvoituron which implemented the `DoubleClickToDate` feature only.
This PR kept the `FluentOverlay` as-is, so it's very difficult to trigger the double-click event on the text field of the date picker, thus difficult to see this feature works. Commenting out the `FluentOverlay` temporarily could help a lot during the manual …
> [DatePicker] Added OnDoubleClick event and DoubleClickToDate parameter

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
Fix #2540 by invoking `OnRowClick` in `HandleOnRowKeyDownAsync`
> [DataGrid] Trigger OnRowClick on keyboard enter in DataGrid row

- .github/workflows/build-core-lib.yml
- .github/workflows/cicd_publish.yml
- .github/workflows/deploy_preview.yml
- Directory.Build.props
- Directory.Packages.props
- docs/contributing.md
- docs/using-latest-daily.md
- eng/pipelines/version.yml
- examples/Demo/AssetExplorer/FluentUI.Demo.AssetExplorer.csproj
- examples/Demo/Client/FluentUI.Demo.Client.csproj
- examples/Demo/Server/FluentUI.Demo.Server.csproj
- examples/Demo/Shared/FluentUI.Demo.Shared.csproj
- src/Core.Assets/Microsoft.FluentUI.AspNetCore.Components.Assets.esproj
- src/Core.Assets/esbuild.config.mjs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
- src/Extensions/DataGrid.EntityFrameworkAdapter/Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter.csproj
- tests/Core/Microsoft.FluentUI.AspNetCore.Components.Tests.csproj
Also:
- Update NuGet packages / .NET SDK
- Update `contributing.md` and `using-lates-daily.md`
- Update publish workflows to get .NET 9 version deployed
> [General] Add .net9.0 as targeted framework

- .github/workflows/build-core-lib.yml
- examples/Tools/FluentUI.Demo.DocViewer.Tests/FluentUI.Demo.DocViewer.Tests.csproj
- examples/Tools/FluentUI.Demo.DocViewer.Tests/_StartCodeCoverage.cmd
- tests/Core/Microsoft.FluentUI.AspNetCore.Components.Tests.csproj
Use only `net9` for Unit Tests to avoid multiplication of "same" tests.
> [dev-v5] Update Unit Tests Framework

- src/Core/Components/Base/FluentInputBase.cs
Change notification call to use InvokeAsync to bring back the EditContext into the same thread as the dispatcher.
More details here: https://github.com/microsoft/fluentui-blazor/issues/2466#issuecomment-2332021231
Fix #2466: Dispatcher Exception in Debouncer 4.8.x+
> [FluentInputBase] Force `EditContext` to be re-associated with the Dispatcher

- examples/Demo/Shared/Pages/Anchor/Examples/AnchorIcons.razor
- src/Core/Components/Anchor/FluentAnchor.razor.css
When using the `Appearance=Appearance.Hypertext` style, an icon in end or start slot would get displayed incorrectly:
Adding some CSS to fix that for this specific case and make it look better. We are not changing anything on the current design for any of the other appearances
```
fluent-anchor[appearance="hypertext"]::part(control) {
display: inline-flex !important;
}
fluent-anchor[appearance="hypertext"]::part(start) {
margin-inline-end: calc(var(--design-unit) * 1px);
}
fluent-anchor[appearance="hypertext"]::part(end) {
margin-inline-start: calc(var(--design-unit) * 1px);
}
```
and you'll get this:
Fixes #2611
> [Anchor] Fix hypertext appearance with icon in start/end slot

- examples/Demo/Shared/Shared/DemoSearch.razor
Fixes displaying of HTML as title in the DemoSearch component within the docs.
Before:
After:
> [Docs] Add MarkupString to DemoSearch

- examples/Demo/Shared/Pages/ProfileMenu/ProfileMenuPage.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.css
Due to a previous change (#2010), the style defined for `TopCorner=“ true”` was not applied.
This code corrects this problem.
See #2621
> [ProfileMenu] Fix the `TopCorner` style

- src/Core.Assets/src/SplitPanels.ts
There was a chatty `console.log` left in code. This PR removes that (plus another commented code line)
Fix #2634
> [SplitPanel] Remove console logging

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Counter/CounterPage.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Counter/Samples/MyCounter.razor.css
- examples/Demo/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
- examples/Demo/FluentUI.Demo.Client/Infrastructure/ServiceCollectionExtensions.cs
- examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor
- examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.cs
- examples/Tools/FluentUI.Demo.DocViewer/Models/Section.cs
- examples/Tools/FluentUI.Demo.DocViewer/Services/DocViewerOptions.cs
With this PR, we can add many additional files to the Source Code component, replacing the default Code tab.
The files attribute is a list of `[TabName]:[FileName]` items.
```
{{ MyCounter Files=Razor:MyCounter.razor;Source:MyCounter.razor.js;CSS:MyCounter.razor.css;404:MyCounter.not.found }}
```
> [dev-v5] Add Extra Files to the Source Code component

- .github/workflows/build-core-lib.yml
`actions/upload-artifact` v1, v2 and v3 are deprectated.
> [Github]Update the actions/upload-artifact to v4

- eng/pipelines/build-all-lib.yml
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Slider/FluentSlider.razor.cs
Fixes two way binding issue.
- setting value does not cause the slider thumbnail to redraw
- see comments in #2609 and #2612
> [Slider] Fix FluentSlider two-way binding issue [#2609}

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- Fix #2669 
- Make Reset and set width methods public
With implementing the `HeaderCellAsButtonWithMenu` a couple of things got mixed up and that is why issue #2669 happened. This PR fixes that.
We added the option to do resize within the same popup as the filter earlier. When using the new `HeaderCellAsButtonWithMenu` parameter set to `true`, the different column action will be shown with a menu. If `false`, the resize action (either discrete or exact and the filter action will show in the same popup:
> [DataGrid] Fix column options popup being blank

- src/Core/Utilities/InternalDebounce/DebounceAction.cs
- src/Core/Utilities/InternalDebounce/DebounceTask.cs
- src/Core/Utilities/InternalDebounce/DispatcherTimerExtensions.cs
- tests/Core/Utilities/DebounceActionTests.cs
- tests/Core/Utilities/DebounceTaskTests.cs
Add an async method to simplify the asynchronous calls 
```csharp
await debounce.RunAsync(50, async () => ...);
```
Update TimerDispatcher to cancel the previous call when a new call is initiated.
Updated
> [dev-v5] Add Debounce.RunAsync method

- tests/Core/Utilities/DebounceActionTests.cs
Use the same Async Unit Tests for Actions and Tasks
> [Debounce] Fix Unit Test

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Utilities/Debounce.cs
- src/Core/Utilities/InternalDebounce/DebounceAction.cs
- src/Core/Utilities/InternalDebounce/DebounceTask.cs
- tests/Core/Utilities/DebounceActionTests.cs
- tests/Core/Utilities/DebounceTaskTests.cs
> [Debounce] Fix Unit Tests

- examples/Demo/Shared/Pages/List/Combobox/Examples/ComboboxDefault.razor
- src/Core.Assets/src/index.ts
- src/Core/Components/Base/FluentInputBaseHandlers.cs
- src/Core/Components/List/FluentCombobox.razor
- src/Core/Events/EventHandlers.cs
The `Immediate` and `ImmediateDelay` works.
```razor
<h4>Select the best song from the list or type your own</h4>
<p>
Selected hit: @hit
</p>
<FluentCombobox Placeholder="Make a selection..." 
Label="Best song" 
Items="@Data.Hits" 
@bind-Value="@hit" 
Immediate="true" 
ImmediateDelay="100" />
```
> [Combobox] Add Combobox Immediate property

- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.css
Fixes #2684 
A button was hard-coded to use full width for the underlying web component: 
```
<fluent-button @ref=Element
class="@(LoadingOverlay ? string.Empty : Class)"
style="@(LoadingOverlay ? "width: 100%;" : Style)"
```
This was causing issues as described in #2684. This PR fixes that by:
- Using the same style for both button as the 'overlay' (span)
- Making sure the overlay has the correct initial height and display styles
Overriding the button height by applying the `Style` parameter still works. The overlay will use that same style (which overrules the initial height set by the class). See the left button in the image below. The right button does not have any specific styling applied.
> [Button] Remove style override when in loading state

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DateTime/FluentCalendar.razor
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Components/DateTime/KeyDown.cs
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Default.verified.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Maximum_View-days.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Maximum_View-months.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Maximum_View-years.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Minimum_View-days.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Minimum_View-months.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_Minimum_View-years.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_TitleClick-days.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_TitleClick-months.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.FluentCalendar_TitleClick-years.verified.razor.html
- tests/Core/DateTime/FluentCalendarTests.cs
- tests/Core/DateTime/FluentDatePickerTests.FluentCalendar_DisabledDate.verified.html
The user can navigate, using keyboard (`Tab` and `Enter`), into the Calendar or DatePicker components.
But not yet the arrows to navigate from day to day (or month to month).
Updated
> [DateTime] Accessibility - Add `role`, `tabindex` and catch Enter/Space

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/MenuButton/Examples/MenuButtonAppearance.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor.cs
- tests/Core/_ToDo/MenuButton/FluentMenuButtonTests.FluentMenuButton_Default.verified.html
- tests/Core/_ToDo/MenuButton/FluentMenuButtonTests.cs
This is a small PR to add the ability to add an icon to the start of a FluentMenuButton.
N/A
This is a pretty small change, and I've added an example to the Demo site. The result is as seen in this screenshot:
Added to the existing FluentMenuButton unit test.
N/A
> [MenuButton] Add an optional start icon 

- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Adds public override variants for the following methods:
- RemoveSortByColumnAsync
- ShowColumnOptionsAsync
- ShowColumnResizeAsync
Useful for simplified DataGrid column control.
> [DataGrid] Public method override additions

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/MessageBar/FluentMessageBar.razor
- src/Core/Components/MessageBar/FluentMessageBar.razor.cs
- src/Core/Components/MessageBar/FluentMessageBar.razor.css
- tests/Core/MessageBar/FluentMessageBarTests.FluentMessageBar_AllowDismiss.verified.html
- tests/Core/MessageBar/FluentMessageBarTests.FluentMessageBar_Default.verified.html
- tests/Core/MessageBar/FluentMessageBarTests.FluentMessageBar_WithId.verified.html
- tests/Core/MessageBar/MessageServiceTests.FluentMessageBarService_AllowDismissAsync1.verified.razor.html
- tests/Core/MessageBar/MessageServiceTests.FluentMessageBarService_AllowDismissAsync2.verified.razor.html
- tests/Core/MessageBar/MessageServiceTests.FluentMessageBarService_AllowDismissAsync3.verified.razor.html
Updated the was the animation is applied to the `MessageBar` component. 
As discussed in #2716
> [MessageBar] Update way animation is applied to the MessageBar

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Tooltip/FluentTooltip.razor
- tests/Core/Dialog/FluentDialogTests.FluentDialog_HeaderFooter.verified.razor.html
- tests/Core/Tooltip/FluentTooltipTests.FluentTooltip_AllAttributes.verified.html
- tests/Core/Tooltip/FluentTooltipTests.FluentTooltip_Default.verified.html
Add `role=tooltip` to the web component. This makes a screen reader (tested with NVDA) announce the tooltip content.
> [Tooltip] Add role so screen reader can announce tooltip text

- src/Core/Components/NavMenu/FluentNavLink.razor
Fixed FluentNavLink not working correctly when Href was empty
So simple PR
Verify that clicking on a FluentNavLink correctly navigates to the root page when the Href of the FluentNavLink is empty.
> fix: [FluentNavLink] An issue where empty strings were not allowed in Href

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
- tests/Core/Button/FluentButtonTests.razor
Adds `StopPropagation` parameter to `FluentButton` top prevent click for bubbling up to parent elements.
2 tests added to confirm it works as expected
> [Button] Add StopPropagation + UnitTests

- src/Core/Components/Button/FluentButton.razor
- src/Core/Components/Button/FluentButton.razor.cs
- tests/Core/Components/Button/FluentButtonTests.razor
Same as PR #2732 but now for V5
> [Button] Add StopPropagation parameter + UnitTests

- examples/Demo/Shared/Components/ApiDocumentation.razor.cs
Fixes issue where member description missing from components inheriting from `ListComponentBase<>`.
I added a private function that recursively searches for a possible description in one of the base classes.
Visually checked.
> [Docs] Components inheriting ListComponentBase missing member descriptions 

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.cs
- tests/Core/ProfileMenu/FluentProfileMenuTests.razor
In certain situations, the developer may wish to open or close the profile menu. 
This can be done by adding the `Open` attribute.
See #2737
> [ProfileMenu] Add `Open` attribute

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentSelect.razor.cs
- src/Core/Components/Radio/FluentRadio.razor.cs
- src/Core/Components/Radio/FluentRadioGroup.razor
- src/Core/Components/Radio/FluentRadioGroup.razor.cs
- tests/Core/_ToDo/Radio/FluentRadioGroupTests.FluentRadioGroup_Default.verified.html
Fix #2740 by adding value to fluent-radio-group and prevent handling a change when the arg value is empty.
Note: Changed to use `OnParametersSet` instead of `OnInitialized` based on [ASP.NET Core source](https://github.com/dotnet/aspnetcore/blob/fe0fbff040c9f129ba3f5ee8cf15c8f6d96fb50e/src/Components/Web/src/Forms/InputRadioGroup.cs#L33)
> [FluentRadioGroup] Fix binding error

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Menu/FluentMenuProvider.razor.cs
- src/Core/Components/Tooltip/FluentTooltipProvider.razor
- src/Core/Components/Tooltip/FluentTooltipProvider.razor.cs
Sometimes (see #2736) the `FluentMenuProvider` or the `FluentTooltipProvider` can create an HTML tag which interferes with the body's scrollbars. This PR solves this problem.
> [Providers] To prevent the menu and tooltip from displaying a scrollbar in body

- Directory.Packages.props
- examples/Demo/Shared/FluentUI.Demo.Shared.csproj
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData.razor
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- examples/Demo/Shared/Pages/Lab/IssueTesterPage.razor
- examples/Demo/Shared/Pages/Lab/LabOverviewPage.razor
- examples/Demo/Shared/Shared/DemoNavProvider.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- Fix #2734
- Create separate page for testing issues
- Update version of Core and Icons packages in `Directory.Packages.props `
> [DataGrid] changes related to loading behavior

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/Overlay/FluentOverlay.razor.js
A problem seems occured with the current way of detecting when a user clicks in a FluentOverlay exclusion zone: 
- Currently, when the user clicks on an element, we calculate the `isExcludeElement` variable based on `event.target`. 
`const isExcludeElement = excludeElement && excludeElement.contains(event.target);`
However, Blazor WASM refreshes HTML DOM faster than Blazor Server, making `target` invalid in this test.
- We correct this problem by calculating `isInsideExcludedElement` using the coordinates of the mouse click.
`const isInsideExcludedElement = !!document.getElementById(id) && isClickInsideContainer(event, document.getElementById(id));`
> [Overlay] Fix the detection of ExcludedElement for WASM

- examples/Demo/Shared/ReflectionExtensions.cs
API documentation did not always show nullable type for parameters or method return.
- Only the underlying type shown even though it was declared nullable. It does not match the [source code](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/Grid/FluentGridItem.razor.cs).
Changes were made to the `ToTypeNameString` extensions instead of `APIDocumentation`. Only concern I have is that the original extensions were sourced from https://github.com/loxsmoke/DocXml.
- I manually checked many of the components.
> [Docs] Fix - Nullable reference types not always shown in API documentation

- src/Core/Utilities/InternalDebounce/DispatcherTimerExtensions.cs
- tests/Core/Utilities/DebounceActionTests.cs
When the action being executed is asynchronous, `Debounce` can sometimes return a value without waiting for the task to finish.
This PR fixes that.
See #2751
> [Debounce] Fix the Debounce class with async methods

- src/Core/Components/TreeView/FluentTreeItem.razor.css
Fix #2766 by adding RTL CSS changes to the Tree View component. Result:
> [TreeView] Improve RTL support

- examples/Demo/DocGenerator/CodeCommentsGenerator.cs
- examples/Demo/Shared/Components/ApiDocumentation.razor.cs
Descriptions for methods on some APIs are mssing.
The information is in the generated `CodeComments` file. The `key` is not being generated correctly because the method is either `static` or one of the parameters is an `EventCallback<T>`.
I manually checked several components.
> [Docs] Fixes missing method descriptions for APIs

- src/Core/Components/NavMenu/FluentNavGroup.razor
Fix #2765 by not using the `MenuService` for the `NavMenu` sub-menu. Result:
> [NavMenu] Make submenu in collapsed state work again

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
Until now, it was not possible to set a custom tooltip on a column header. We have now solved this by adding a new `HeaderTooltip` parameter to the column:
```
<TemplateColumn Tooltip="true" HeaderTooltip="Flag of each team" TooltipText="@(c => "Flag of " + c.Name)" Title="Rank"...
```
> [DataGrid] Add `HeaderTootip` to columns to allow for custom header tooltip text

- src/Core/Components/Menu/FluentMenuProvider.razor.cs
- src/Core/Components/TreeView/FluentTreeView.razor
- src/Core/Components/TreeView/FluentTreeView.razor.cs
- tests/Core/TreeView/FluentTreeViewItemsTests.FluentTreeViewItems_SelectedItem_Change.verified.razor.html
- tests/Core/TreeView/FluentTreeViewItemsTests.razor
Change HandleCurrentSelectedChangeAsync to non-async to prevent runtime errors
> [TreeView] prevent runtime errors in change handeling

- src/Extensions/DataGrid.EntityFrameworkAdapter/EntityFrameworkAsyncQueryExecutor.cs
Fix for reported issue #2769
[FIX: Semphore slim disposed object access error in EntityFrameworkAdapter and FluentDataGrid](https://github.com/microsoft/fluentui-blazor/issues/2769)
Use the scenario described in issue #2769 to manually test.
> [DataGrid] Fix disposed object access error in EntityFrameworkAdapter [#2769]

- src/Core/Components/MenuButton/FluentMenuButton.razor.cs
When the FluentMenuButton does not contain an `OnMenuChanged` event, clicking on the `FluentMenuItem` is not activated. This is because `OnMenuChanged` is executed anyway and renders the menu invisible, hiding the OnClick event.
This PR checks the presence of OnMenuChanged to use it or leave OnClick in other cases.
Doc updated.
> [MenuButton] Fix the MenuItem OnClick used with MenuButton

- examples/Demo/Shared/Pages/Menu/MenuPage.razor
- examples/Demo/Shared/Pages/MenuButton/MenuButtonPage.razor
And also add it to the MenuButton page (where it can't be disabled)
> [Docs] Make MenuProvider message more prominent 

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Menu/FluentMenu.razor.cs
- src/Core/Components/Menu/FluentMenuProvider.razor.cs
- src/Core/Components/Menu/Services/IMenuService.cs
- src/Core/Components/Menu/Services/MenuService.cs
We've added a new `FluentMenuProvider` to manage menus more simply.
By default, it is used but requires the presence of `<FluentMenuProvider />` in the **MainLayout**. 
If this is not the case and the developer does not explicitly request `UseMenuService=‘false’`, an error is triggered.
> [MenuProvider] Check whether the FluentMenuProvider is included

- examples/Demo/Shared/Pages/TreeView/TreeViewPage.razor
- src/Core/Components/NumberField/FluentNumberField.razor
- src/Core/Components/NumberField/FluentNumberField.razor.cs
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AdditionalParameters.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Filled.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AppearanceParameter-Outline.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_AutoFocusParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_ClassParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_DataListParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_Default.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_DisabledParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_HideStepParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_IdParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_Label.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_LabelTemplate.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MaxLengthParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MaxParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MinLengthParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_MinParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_NameParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_PlaceholderParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_ReadOnlyParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_RequiredParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_SizeParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_StepParameter.verified.html
- tests/Core/NumberField/FluentNumberFieldTests.FluentNumberField_StyleParameter.verified.html
- tests/Core/Wizard/FluentWizardTests.FluentWizard_EditForm_EditContextIsInValid_OnFinish.verified.razor.html
- tests/Core/Wizard/FluentWizardTests.FluentWizard_EditForm_EditContextIsInValid_OnNext.verified.razor.html
- tests/Core/Wizard/FluentWizardTests.FluentWizard_EditForm_EditContextIsValid.verified.razor.html
Fix #2803 by using `value` instead of `current-value` in web component tag. Tests have been updated. No other side effects have been observed.
> [NumberField] Fix looping error

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/MessageBox/Examples/DialogMessageBoxAsyncCustomPrimary.razor
- examples/Demo/Shared/Pages/MessageBox/MessageBoxPage.razor
- examples/Demo/Shared/Pages/TreeView/TreeViewPage.razor
- src/Core/Components/Dialog/Services/DialogService-MessageBox.cs
- src/Core/Components/Dialog/Services/IDialogService-MessageBox.cs
Fix #2805 by adding primary action parameter to message box shortcut methods. Changed existing examples to use default value. Added new examples for new parameter.
The new parameter has been added as the last (nullable) parameter in the method calls to not break current implementations
> [MessageBox] Add settable primary action text for Show... methods

- src/Core/Components/Dialog/Parameters/DialogParameters.cs
- src/Core/Components/Stack/FluentStack.razor.cs
- src/Core/Enums/HorizontalAlignement.cs
- tests/Core/Dialog/FluentDialogServiceTests.razor
Introduced a new horizontal alignment option, `Stretch`, to the `FluentStack` component. Updated the `HorizontalAlignment` enum in `HorizontalAlignment.cs` to include the `Stretch` value with a summary comment. Modified the `GetHorizontalAlignment` method in `FluentStack.razor.cs` to map `HorizontalAlignment.Stretch`  to the string "stretch".
While using the FluentStack in vertical mode I found that I was unable to set the underlying flexbox "align-items"  style to "stretch" as this option was missing from the HorizontalAlignment enum. Therefore I have added "Stretch" to the enum and implemented the option in the GetHorizontalAlignment method of the FluentStack component.
I don't believe this is a breaking change as the default option is still "start".
To view the change in action visit …
> [Stack] Added 'Stretch' horizontal alignment option

- src/Core/Components/TreeView/FluentTreeItem.razor.cs
Set a `FluentTreeItem`'s `Selected` value before calling `FluentTreeView.ItemSelectedChangeAsync`. Fixes #2810
> [TreeView] Fix OnSelectedChange when using Items

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentAutocomplete.razor.cs
When a slow connection is used and the search takes a long time, some side effects may occur.
This PR blocks rendering during the search process.
> [Autocomplete] Fix the Autocomplete search rendering on slow connections

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteCustomized.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
Currently, when the user selects an item, the popup closes automatically and the user has to reopen it to select a new item.
To avoid this, it is now possible to use a `KeepOpen =‘true’` attribute which keeps the popup open as long as possible: as long as the maximum number of selected items has not been reached (`MaximumSelectedOptions`) 
And as long as the selection is made with the mouse (not the keyboard).
For compatibility reasons, this attribute is set to `false' by default.
See #2819
> [AutoComplete] Add KeepOpen property

- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.js
- src/Core/wwwroot/css/reboot.css
This pull request includes changes to improve theme management in the `FluentDesignTheme` component and updates to the CSS to support these changes. 
A new data attribute (`data-theme`) is added to body and updated every time theme changes.
In `reboot.css` this attribute is used to control the value of `color-scheme`: this ensure all browser-managed components (like scrollbars) matches theme in use.
Before:
After:
> [General] Apply global color-scheme to reflect theme in use

- src/Core/Components/Menu/FluentMenuItem.razor.cs
A feature that adds the option to keep the menu item open after it has been selected. This allows render fragments, such as `FluentSwitch` or simply the `MenuItemRadio`, to be changed without needing to re-click. By default, this option will be set to `false` to avoid any breaking changes.
Below you can see the effect of the feature:
I want to note that currently the test for the `FluentMenuItem`  component are being skipped with the comment: "Need to figure out how to do this test". 
Below is the code I used for testing the feature that you can see in the video:
```razor
<FluentSwitch @bind-Value="@_open">Show Default</FluentSwitch>
<FluentMenu @bind-Open="@_open" Anchored="false">
<FluentMenuItem>Menu item 1</FluentMenuItem>
<FluentMenuItem>Menu item 2</FluentMenuItem> …
```
> [MenuItem] Add KeepOpen parameter

- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core.Assets/src/index.ts
- src/Core/Components/List/FluentCombobox.razor
- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Events/EventHandlers.cs
Fix #2851 by not calling `base.ChangeHandlerAsync` when no item selected. This could happen if the  Value and the Text of an option differed.
See original issue for before output. Now all test situations render as expected.
> [ComboBox] Fix OnValueChanged being called multiple times

- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor
- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor.cs
- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor.css
- examples/Demo/FluentUI.Demo.Client/Layout/DemoNavMenu.razor
- examples/Tools/FluentUI.Demo.DocViewer/Extensions/ReflectionExtensions.cs
- src/Core/Utilities/InternalDebounce/DispatcherTimerExtensions.cs
- Fix the Code Analyzer
- Update the HomePage design (2 columns)
- Update the Navigation order, based on the Routes
> [dev-v5] Fix last cherry-pick

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Counter/CounterPage.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/MigrationVersion5.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/ReleaseNotes.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Home.md
- examples/Demo/FluentUI.Demo.Client/Layout/DemoNavMenu.razor
- examples/Demo/FluentUI.Demo.Client/Layout/DemoNavMenu.razor.cs
- examples/Demo/FluentUI.Demo.Client/Layout/DemoNavMenu.razor.css
- examples/Tools/FluentUI.Demo.DocViewer.Tests/PageTests.cs
- examples/Tools/FluentUI.Demo.DocViewer/Models/Page.cs
- examples/Tools/FluentUI.Demo.DocViewer/ReadMe.md
Update the Markdown headers to classify pages into categories using the `category` attribute.
This allows you to present the navigation structure with these categories, possibly sorted on the basis of the key
(to avoid alphabetical classification). Similarly, pages can be classified using the `order` parameter.
```markdown
---
category: 10|Getting Started
title: Button
order: 20
route: /Button
---
```
Temporary update of the `DemoNavMenu.razor` to have an acceptable result for the DotNetConf demo.
(Waiting the future NavMenu element)
> [dev-v5] Add Categories and Pages Order

- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fixes #2868. When `StateHasChanged()` is called in the data refresh logic, the script would detect that it is running for the same grid and then return. In some cases however re-running the script code is actually necessary.
> [DataGrid] Remove optimalization check as it can break in certain scenarios

- README.md
- examples/Demo/Shared/Pages/BlazorHybrid.razor
The mentioned workaround is no longer needed for .NET 9. In fact, for .NET 9 this workaround will actually break the working of your Blazor Hybrid project. This PR adds a note to the README to inform users of this change.
> [Docs] Update README with Blazor Hybrid workaround note

- src/Core/Components/DateTime/FluentCalendar.razor.css
```css
[dir="rtl"] .fluent-calendar ::deep .day[disabled]::before {
transform: translate(4px, 0px) rotate(45deg);
}
```
See #2897
> [Calendar] Fix the Calendar disabled day in RTL direction

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeExample.razor
- examples/Demo/Shared/Pages/KeyCode/Examples/KeyCodeGlobalExample.razor
- src/Core/Components/KeyCode/FluentKeyCode.razor.cs
- src/Core/Components/KeyCode/FluentKeyCode.razor.js
- src/Core/Components/KeyCode/FluentKeyCodeEventArgs.cs
- tests/Core/KeyCodeProvider/FluentKeyCodeTests.razor
- tests/Core/List/FluentAutocompleteTests.razor
When this property is set to `True`, the user can continue to press the keyboard.
https://github.com/user-attachments/assets/ed700d6b-3313-4dab-b428-ac1da41de658
Request #2881
Updated
> [KeyCode] Add a new `StopRepeat` property

- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/ListComponentBase.razor.cs
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_AutofocusAttribute.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_MaxAutoHeight_Opened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Name.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClearWithOverlayHiddenOnEmpty_HasNoOverlay.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClear_ShowOverlay.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText_Clears.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.razor.html
The Clear button is no longer works in AutoComplete.
@vnbaaij Do you remember why you added that `if` in [this PR](https://github.com/microsoft/fluentui-blazor/pull/2840/files#diff-f0f5ed08133cfc76e94fd32d1df468eead9bcf5cd931b5012eac001a86a1303aR539) ?
Fix #2903
> [Autocomplete] Fix the Autocomplete Clear button

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/Columns/SelectColumn.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/KeyCode/FluentKeyCode.razor.cs
- tests/Core/DataGrid/FluentDataGridColumSelectTests.razor
- tests/Core/Utilities/DebounceActionTests.cs
The **Select All** checkbox for a `SelectColumn` stops working after reloading data for a data grid, when the `Virtualize` parameter is set.
See #2913
> [DataGrid] Fix `SelectAll` after reloading data  when the `Virtualize` is set

- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/TreeView/FluentTreeItem.razor
- src/Core/Components/TreeView/FluentTreeItem.razor.cs
Fixes #2911 
When using 
```
<fluent-tree-item @ref=Element
:
selected="@Selected"
:
```
and using a tree item collection, setting `Selected` leads to a looping situation where the value keeps flipping form true to false. To fix this I've changed this to only set `selected` to the `InitiallySelected` value. Selecting an item still works as expected as it will be handled by the web component and the event handler sets the state on the Blazor side.
Do not auto merge this. Need to clear issue tester first!
> [TreeItem] Only pass initially selected state to the web component

- .github/workflows/build-core-lib.yml
- Directory.Packages.props
- examples/Demo/FluentUI.Demo.Client/FluentUI.Demo.Client.csproj
- examples/Demo/FluentUI.Demo/FluentUI.Demo.csproj
- examples/Demo/FluentUI.Demo/Program.cs
- examples/Tools/FluentUI.Demo.DocViewer/FluentUI.Demo.DocViewer.csproj
- examples/Tools/FluentUI.Demo.SampleApi/FluentUI.Demo.SampleApi.csproj
- examples/Tools/FluentUI.Demo.SampleData/FluentUI.Demo.SampleData.csproj
- src/Core/Components/Base/IFluentComponentBase.cs
- src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
- tests/Core/Utilities/DebounceTests.cs
Remove .NET 8 packages. settings, etc
> [dev-v5] Change to .NET 9 GA version all the way. 

- examples/Demo/Shared/Pages/InputFile/Examples/InputFileLoading.razor
- examples/Demo/Shared/Pages/InputFile/InputFilePage.razor
- src/Core/Components/InputFile/FluentInputFile.razor.cs
- src/Core/Components/InputFile/FluentInputFile.razor.js
When a `FluentButton` is being used as an anchor to trigger a `FluentInputFile` in combination with the property `Loading` then the registered event will be lost once the button renders again to display the loading style. This PR fixes this by reattaching the event when it's necessary.
* #2754
Perhaps you might want to add a test-case for this. I sadly don't know how to do this but I will take a look on it when you add one to learn from it! 😀
> [InputFile] Make it work icw a loading Button

- src/Core/Components/List/ListComponentBase.razor.cs
Passing an empty `SelectedOptions` to **FluentAutocomplete** doesn't update the internal `_selectedOptions` variable.
See #2943
Passed
> [Autocomplete] Fix the internal array when SelectedOptions is empty

- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.js
After updating the package from version 4.10.1 to version 4.10.3 or if the StorageName is not defined in the FluentDesignTheme, this error may be displayed. This is a non-blocking error, but it is annoying for the Console logs.
See #2952 and in the [DotNetConf 2024 Demo](https://github.com/dvoituron/dotnetconf-2024-fluentui-blazor)
> [DesignThemen] Fix the DesignTheme with no Storage

- src/Core/Components/Button/FluentButton.razor.cs
> [Button] Fix showing hover on disabled button

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Rating/Examples/RatingDefault.razor
- src/Core/Components/Rating/FluentRating.razor
- src/Core/Components/Rating/FluentRating.razor.cs
- tests/Core/Rating/FluentRatingTests.FluentRating_Label.verified.razor.html
Fix #2976. Based on the comments in that issue, I changed it to be like this:
`<div role="radiogroup"` gets the aria-label from the component's Label property if the AriaLabel is not specified, removed aria-label from the individual radio buttons in favor of the radio group as a whole.
> [Rating] Improve a11y support

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Fixed #2839
Paging or sorting for a data grid will now save the state in the url, if the developer opt-ed in for this on that grid. It also supports a prefix, in case you would have multiple grids on a single page.
* #2839
> [DataGrid] Save paging state in URL

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/Tabs/FluentTab.razor
Fix #2988. See the issue for more context. Gist is that with this PR you can now use both `Header` and `Label` at the same time while only `Header` will be rendered. `Label` can be used in overflow menu
> [Tabs] Only render Label if Header is null

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DateTimes/Examples/DatePickerDefault.razor
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Components/DateTime/FluentDatePicker.razor.cs
There is a situation where the developer would like to "force" the horizontal position of the displayed popup.
See #3000
using the new `PopupHorizontalPosition="@HorizontalPosition.Left"` attribute.
> [DatePicker] Add `PopupHorizontalPosition` property

- src/Templates/Microsoft.FluentUI.AspNetCore.Templates.csproj
- src/Templates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.Web/Aspire-StarterApplication.1.Web.csproj
- src/Templates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.Web/Components/Pages/Weather.razor
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.AppHost/Aspire-StarterApplication.1.AppHost.csproj
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.ServiceDefaults/Aspire-StarterApplication.1.ServiceDefaults.csproj
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.Web/Aspire-StarterApplication.1.Web.csproj
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.Web/Components/Pages/Weather.razor
- src/Templates/templates/blazorweb-csharp/BlazorWeb-CSharp.Client/BlazorWeb-CSharp.Client.csproj
- src/Templates/templates/blazorweb-csharp/BlazorWeb-CSharp/BlazorWeb-CSharp.csproj
- src/Templates/templates/blazorweb-csharp/BlazorWeb-CSharp/Components/_Imports.razor
- src/Templates/templates/componentswebassembly-csharp/ComponentsWebAssembly-CSharp.csproj
- src/Templates/templates/maui-blazor-solution/MauiApp.1.Shared/MauiApp.1.Shared.csproj
- src/Templates/templates/maui-blazor-solution/MauiApp.1.Web.Client/MauiApp.1.Web.Client.csproj
- src/Templates/templates/maui-blazor-solution/MauiApp.1.Web/MauiApp.1.Web.csproj
- Make `PackageReference`s use PackageVersion
Now all projects will always reference same version as being built
- Fix `PackageReference`s for Aspire version
Aspire 9 projects were using library's package version in generated solution
- Use InteractiveServer for Weather page in Aspire starter
The grid needs interactivity to make sorting work
> [Templates] More templates work

- src/Core/Components/AnchoredRegion/FluentAnchoredRegion.razor.js
Sometime, the `goToNextFocusableElement` JS method can receive an obsolete element.
This test verifies if this element is still there or not (in the DOM)
Will fix #3012
> [Popover] Go to the next focusable Element

- examples/Demo/AssetExplorer/Components/Controls/PreviewCard.razor.cs
- examples/Demo/AssetExplorer/Components/Pages/EmojiExplorer.razor.cs
- src/Core/Components/Emojis/EmojiExtensions.cs
- src/Core/Components/Icons/IconsExtensions.cs
After updating the icon and emoji libraries, the extension methods should also be updated.
The **Explorer** has been adapted to use the new namespaces.
> [Icons and Emojis] Update `AllIcons` and `AllEmojis` extension methods

- examples/Demo/Shared/Components/NotificationCenter.razor
- examples/Demo/Shared/Pages/Badge/CounterBadge/Examples/CounterBadgeAppearances.razor
- examples/Demo/Shared/Pages/NavMenuTree/Examples/NavMenuTreeCollapsible.razor
- examples/Demo/Shared/Pages/NavMenuTree/Examples/NavMenuTreeCustomActions.razor
- examples/Demo/Shared/Pages/NavMenuTree/Examples/NavMenuTreeDataBound.razor
- examples/Demo/Shared/Pages/NavMenuTree/Examples/NavMenuTreeDefault.razor
- examples/Demo/Shared/Pages/NavMenuTree/NavMenuTreePage.razor
> [Fundamentals] Remove obsolete warnings

- tests/Core/_StartCodeCoverage.cmd
Previously the `_StartCodeCoverage.cmd` did not find the generated xml file.
This is now fixed.
> [Unit Tests] Fix the CodeCoverage script, using .NET9 only

- src/Core/Components/InputFile/FluentInputFile.razor.cs
- src/Core/Components/InputFile/FluentInputFileEventArgs.cs
- tests/Core/InputFile/FluentInputFileTests.razor
Making the property LastModified from the IBrowserFile available on the the FluentInputEventArgs object, so it can be accessed.
> [FluentInput] Set last modified date

- examples/Demo/Shared/Components/CodeSnippet.razor.js
- src/Core/Components/InputFile/FluentInputFile.razor.js
This PR adds a null check to `FluentInputFile.razor.js` to prevent a crash which happens when the user leaves the page before the `FluentInputFile` has been fully initialized. Without this null check the app might eventually crash.
In addition this PR also adds a `try/catch` for the `CodeSnippet` component for the demo sites. Which has the same problem on fast navigations. Here a null check is not possible because `hljs` is not null and the javascript which is being executed is a third party library.
Fixes #3061
> [FluentInputFile] [Docs] Add null check on initialization

- src/Core/Components/Wizard/FluentWizard.razor.cs
- src/Core/Components/Wizard/FluentWizardStep.razor.cs
This PR fixes the EditForms functionality within the `FluentWizardStep` component when the DeferredLoading parameter is set to `true`.
The `DeferredLoading` parameter causes the component to create a new instance of all `EditForm` components within it each time the component is rendered. These `EditForm` instances are subsequently registered and invoked. This PR ensures that these `EditForm` instances are cleared when the user navigates away from the current step within the wizard.
#3014
> [Wizard] Unregister EditForms in FluentWizardStep when DeferredLoading is enabled

- Directory.Packages.props
- src/Templates/templates/blazorweb-csharp/BlazorWeb-CSharp/Components/Pages/Weather.razor
- src/Templates/templates/maui-blazor-solution/MauiApp.1.Shared/Pages/Weather.razor
Fix #3068.
`IQueryable` does not work great in combination with `StreamRendering` (see also https://github.com/dotnet/aspnetcore/issues/51749)
Our DataGrid (which is based on QuickGrid and mentioned in the other issue) needs an `IQueryable` to work. I tried the suggested fix from the other issue but it did not lead to the loading text being shown. This has to do with the fact that the DataGrid has it's own loading state as well. 
With the code below, we can use this internal loading state to show the Loading in the grid itself instead of using the if..else construct from the standard template. This PR changes the template to use this code (only in the situations where the error occurred).
After the change:
You can see the `StreamRendering` is actually working as when you set it to false, …
> [Templates] Fix StreamRender error occurring in certain situations

- examples/Demo/Shared/Pages/Rating/Examples/RatingDefault.razor
- src/Core/Components/Rating/FluentRating.razor
- src/Core/Components/Rating/FluentRating.razor.cs
Fix #3069 by adding a reset by spacebar to Rating
> [Rating] Add reset by keyboard option 

- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fix #3087
The DataGrid script was too eager in processing arrow keys. This lead to unexpected/unwanted behavior in other components like when having to TextFields next to each other with focus in text field 1, arrow right would move focus from 1st text field to the second instead of moving through the letters in the text field.
> [DataGrid] Fix script being to eager on processing arrow keys

- examples/Demo/Shared/Pages/Accordion/Examples/AccordionDefault.razor
- src/Core/Components/Accordion/FluentAccordion.razor.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fix #3086
In `HandleOnAccordionChangedAsync(AccordionChangeEventArgs args)` arg contains the expanded state of the active Id. This value was not being used by the found `AccordionItem` used in the invocation of `OnAccordionItemChange`
After this change Expanded shows state of the changed item:
> [Accordion] Fix Expanded state not being set in OnAccordionItemChange

- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTemplateColumns2.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGridCell.razor
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- src/Core/Components/DataGrid/FluentDataGridRow.razor
- src/Core/Components/DataGrid/FluentDataGridRow.razor.cs
With the change to html table rendering, the DataGrid lost the `OnRowFocus` and `OnCellFocus` event callbacks. This PR restores them. (We added `OnRowClick` and `OnCellClick` event callbacks btw)
There is however one issue: rows are now `tr` elements with a `display: contents;` style. Currently, browser do not support setting focus to such elements but work is underway to add this. See also https://chromestatus.com/feature/6237396851228672 for more information.
This fixes #3096
> [DataGrid] Restore OnRowFocus and OnCellFocus

- src/Core/Components/List/ListComponentBase.razor.cs
Fix 3029, Combobox no longer causes the page to become unresponsive.
https://github.com/microsoft/fluentui-blazor/issues/3029#issuecomment-2563476494
#3029 
The displayed value of the combobox is not consistent with its value. I have no idea how to solve this.
> [ListComponentBase] Fix #3029 invoke `ValueChanged` when initially selecting an option

- src/Core/Components/NumberField/FluentNumberField.razor.cs
- src/Core/Components/Slider/FluentSlider.razor.cs
- src/Core/Components/TextField/FluentTextField.razor.js
- tests/Core/NumberField/FluentNumberFieldTests.cs
- tests/Core/Wizard/FluentWizardTests.razor
Fixes issues reported in #2948. Two issue reported both related to changing the value of the control programatically.
The underlying issue is that the web components being wrapped were designed to have there states only changed interactively.  `bind-value` does not behave as expected. Inward binding works only on for initialization. Outward binding works as expected.
This gives the appearance of a *sync* issue.
`FluentSlider` - #2665 did not fully fix #2609. The original fix was to prevent the [flickering when the slider was moved rapidly](https://github.com/microsoft/fluentui-blazor/issues/2609#issuecomment-2326339496) originally reported. I was not able to reproduce this problem with the current implementation of `FluentDataGrid`. I did end up adding debouncing with the …
> [FluentSlider] [FluentNumberField] Fix #2948

- src/Core/Components/List/ListComponentBase.razor.cs
Fix #3111 
`InternalValue` was being set in `OnParametersSet` even when `Value` was an empty string. This led to the `RaiseChangedEventsAsync` event being invoked twice in.
> [ListComponentsBase] Fix SelectedOptionsChanged being Invoked twice

- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Descending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Descending.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Customized_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_SingleSelect_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridTests.FluentDataGrid_Default.verified.razor.html
Fix #3110 
Header needs display: flex in certain scenarios.
multiline-text class must not be added to header
> [DataGrid] - Header needs display: flex in certain scenarios, multiline-text class must not be added to header

- examples/Demo/Shared/Pages/Anchor/Examples/AnchorIcons.razor
- src/Core/Components/Anchor/FluentAnchor.razor.css
Fix #3130 by not applying inline margin for hypertext by default.
A note is shown in the example code of how the margin between an icon and hypertext can be adjusted
> [Anchor] Do not apply inline margin for hypertext by default.

- .editorconfig
- WHATSNEW.md
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- examples/Demo/Shared/wwwroot/docs/WhatsNew.md
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Descending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Descending.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Customized_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_MultiSelect_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_SingleSelect_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridColumSelectTests.FluentDataGrid_ColumSelect_SingleStickySelect_Rendering.verified.razor.html
- tests/Core/DataGrid/FluentDataGridTests.FluentDataGrid_Default.verified.razor.html
Fix #3151, #3152
DataGrid hotfixes for issues introduced with 4.11.1.
- `display: flex` was being applied to liberal. This PR fixes that
- When using DisplayMode with DataGridDisplayMode.Table, the table did not render correctly in some cases.
Extra optimization: only render `col-sort-asc` or `col-sort-desc` for active sort column. Before this was added to every column header class.
> [DataGrid] Tweak `display: flex` and DataGridDisplayMode.Table

- src/Core/Components/Tabs/FluentTab.razor.cs
The height of the `FluentTab` is derived from the height of the `FluentTabs` component. This is done by subtracting 40px from the height of `FluentTabs`. The 40px is the height of the fluent tabs list. This is not necessary as the `FluentTab` is rendered inside the `tabpanel` part of the `fluent-tabs` web component which already accounts for this. (`fluent-tabs` is a grid with `tablist` taking the first row and `tabpanel` taking the rest.)
> [Tabs] Remove height compensation

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/FluentCombobox.razor.js
Set `EnableClickToClose` to `true` to enable dismissing the `FluentCombobox` dropdown list by clicking the dropdown button.
Addresses an issue with the web components `fluent-combobox` where the dropdown list cannot be closed by clicking the arrow indicator.
Tried to create a test but the shadowRoot was empty and I'm not sure how to pre-load the required JavaScript handlers into the tests.
> [FluentCombobox] Add EnableClickToClose

- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
Fix #3181 
`RowSize` was not applied when using `ItemsProvider`  without `Virtualize`. This PR fixes that.
> [DataGrid] Fix height not being set in specific situation

- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
Fix #3185 by not adding class multiline-text to a cell when the grid is empty (both `Items` and `ItemsProvider` are null). This change ensures that the 'No Data to Show!' message is displayed correctly in the DataGrid when in multiline mode. Also ensures any `LoadingContent` would be shown in the correct position
> [DataGrid] Not displaying EmptyContent/LoadingContent at correct position when in multiline mode.

- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Fix #3178
The value of GridTemplateColumns was only being set if it had not been set before. This PR fixes that and always re-evaluates that value after collecting columns when using displaymode grid. This means it now correctly responds to hiding or showing columns.
> [DataGrid] Always re-evaluate GridTemplateColumns after collecting columns

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Toolbar/FluentToolbar.razor.cs
- src/Core/Components/Toolbar/FluentToolbar.razor.js
- tests/Core/_ToDo/Toolbar/FluentToolbarTests.cs
Added a new parameter to `FluentToolbar` (`EnableArrowKeyTextNavigation`) which enables arrow key navigation within text fields. This resolves an issue where the right and left arrow keys incorrectly shifted focus to the next or previous control in the tab order
Fix #3169
Is that parameter name okay?
> [Toolbar] Allow arrow keys to move cursor inside input fields

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/InputFile/FluentInputFile.razor.cs
Add event callback to handle cases where the uploaded file count exceeds the specified maximum limit.
Fix #3204
Is the name OnFileCountExceeded acceptable, or would you prefer a different one?
> [InputFile] Add OnFileCountExceeded callback

- examples/Demo/Shared/wwwroot/docs/DesignTokens.md
- src/Core/Components/AppBar/FluentAppBar.razor
- src/Core/Components/AppBar/FluentAppBar.razor.css
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Fix #3212 by setting FluentComponentBase.Element to a correct value. Also do this for AppBar
> [DataGrid] [AppBar] Set `FluentComponentBase.Element` to a correct value

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/ListComponentBase.razor.cs
Fix #3257 by adding `ChangeOnEnterOnly` parameter to list base class. This allows for the option having focus to change without immediately selecting the option.
Default value for the parameter is false so earlier behavior is not changed
> [Lists] Add `ChangeOnEnterOnly` parameter to allow option focus change without selection

- examples/Demo/Shared/Pages/DataGrid/Pages/DataGridAutoItemsPerPagePage.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Fix #3261 3261 by fine tunning a change that was made in PR #3064 which only took `ItemsProvider` into account
+ a small fix in a datagrid example
> [DataGrid] Small optimization to the number of times data needs to be refreshed

- src/Core/Components/Tabs/FluentTab.razor.css
Fixes missing bold highlighting for the active tab in Mozilla Firefox.
Before:
After:
Discussion: #3276
> [Tabs] Fix missing bold highlighting in Firefox #3276

- src/Core/Components/DataGrid/FluentDataGridCell.razor.css
Fix #3273 by removing padding for first column in css. See the issue for explanation.
> [DataGrid] Remove padding for first column header

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
- examples/Demo/Shared/SampleData/Starship.cs
- src/Core/Components/List/ListComponentBase.razor.cs
autocomplete doesnt trigger the fieldchanged as the default ChangeHandler, which handles the validation/fieldchanged event of the editform, this was fixed by always triggering the event on selection changes for both single and multiple mode.
i also noticed that the list base didnt implement the binding expression property, so the fieldidentifier was always wrong.
Fix #3115 
this was tested using the form page from the demo project. i am currently going through the tests to check out if i missed anything
none, i dont see how to put this in a test without adding a binding the bunit test and rendering a validator at the same time. not sure if its worth it?
N/A
> [Lists] Trigger field changed when in multiple mode

- src/Core/Components/Tabs/FluentTabs.razor.cs
Fix #3325. Size was always being compared to TabSize.Small.
> [Tabs] Use correct enum values when comparing size

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridAutoItemsPerPage.razor
- examples/Demo/Shared/Pages/Dialog/DialogPage.razor
- examples/Demo/Shared/Pages/Dialog/Examples/DialogEditableExample.razor
- src/Core/Components/Dialog/Services/DialogHelper.cs
- src/Core/Components/Dialog/Services/DialogService-Dialog.cs
- src/Core/Components/Dialog/Services/IDialogService-Dialog.cs
Fix #3327 
`IDialogService` has 2 overloads that are partial type safe:
```csharp
Task<IDialogReference> ShowDialogAsync<TData>(Type dialogComponent, TData data, DialogParameters parameters)
where TData : class;
Task<IDialogReference> ShowDialogAsync<TDialog>(object data, DialogParameters parameters)
where TDialog : IDialogContentComponent;
```
however, the TDialog implementation already knows the type of its own data if implementing the  `IDialogContentComponent<TContent>`
Let say we have this a dialog `MyDialog.razor`:
```razor
@implements IDialogContentComponent<(int, int, int, bool, object)>
Hello world!
@code {
public (int, int, int, bool, object) Content { get; set; }
}
```
This PR makes it possible to then get compile time type checks of dialogs if they implement the typed …
> [Dialog] Add type safe way of working with IDialogContentComponent

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DateTime/FluentCalendar.razor
- src/Core/Components/DateTime/FluentCalendar.razor.cs
- src/Core/Components/DateTime/FluentCalendarBase.cs
- src/Core/Components/DateTime/FluentCalendarMonth.cs
- src/Core/Components/DateTime/FluentCalendarYear.cs
- src/Core/Components/DateTime/FluentDatePicker.razor
- src/Core/Extensions/DateTimeExtensions.cs
By default, the `FluentCalendar` and `FluentDateTime` components have a `DisabledDateFunc` attribute which is called with the **day** (Day view) or the **first day** of the month (Month) or the **first day** of the year (Year view).
A new `DisabledCheckAllDaysOfMonthYear` option asks the calendar to check whether **ALL the days** of the month or year are disabled, in order to grey out the month or year.
This parameter forces the component to execute the `DisabledDateFunc` method 31 times or 365 times, which can be costly in terms of performance. The default setting is therefore `DisabledCheckAllDaysOfMonthYear = False`.
See #3348
Validated
> [Calendar] Add DisabledCheckAllDaysOfMonthYear

- Directory.Build.props
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- src/Core/Components/Button/FluentButton.razor.cs
- src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
- Do not warn on directory mismatches
- Clarified `FormId` property documentation in XML.
- Updated copyright year in `DemoMainLayout.razor`.
- Added MIT License comment in `FluentButton.razor.cs`.
- Modified `NoWarn` property in project file to append warnings.
> [General] Some miscellaneous changes

- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- src/Core/Components/Search/FluentSearch.razor.cs
- src/Core/Components/Search/FluentSearch.razor.js
Fix #3349 by adding script function that attaches datalist to the component
> [Search] Fix non working datalist

- src/Core/Components/List/FluentAutocomplete.razor.cs
> When using backspace within the FluentAutocomplete component the method bound to OnOptionsSearch will be executed twice.
This PR fixes this issue.
> [Autocomplete] Fix the second unnecessary call

- examples/Demo/Shared/Pages/Home/Videos.razor
- examples/Demo/Shared/wwwroot/css/site.css
Solving several issues like stated in the issue #3345:
- Pages now are printed on a new page for each H2 (except the first H2) found. 
- The videos page does not have video's in the printed version, but a link to each video.
- Hiding certain UI elements that are not relevant when printing a single page like the header, nav menu, footer and aside.
- Hiding interactive elements like buttons.
- Whenever a FluentTabs element is used, all the content for each tab will be placed below eachother, instead of only 1 tab showing in the printed version.
#3345
If you find any more issues on pages please let me know, it was really hard to go about each page and find elements that are not correctly printed yet, so i might have missed some!
Run the Demo website locally and try to print the pages in …
> [Demo] Fix (most) printing issues when trying to print the page

- src/Core/Components/Progress/FluentProgressBar.razor.cs
- src/Core/Migration/FluentProgress.cs
- tests/Core/Components/Progress/FluentProgressBarTests.razor
`<FluentProgress />` and `<FluentProgressBar />` are identical, but `FluentProgress` is tagged `Obsolete`.
> [dev-v5] Add an obsolete FluentProgress component

- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
When finished collecting the columns, the `GridTemplateColumns` value is re-evaluated. The logic was not taking the original `GridTemplateColumns` value into account.
> [DataGrid] Fix error in handling GridTemplateColumns

- src/Core.Assets/src/index.ts
applies the error css to the autocomplete when invalid
#3407
can be tested with the form example and putting in a country & disabling it again
- x ] I have validated the [Unit Tests](https://github.com/Microsoft/fluentui-blazor/blob/master/unit-tests.md) for an existing component
N/A
> [Autocomplete]: Apply invalid css to autocomplete #3407

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarActive.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarColorful.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarExample.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarIcon.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarImage.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/Examples/FluentAvatarName.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Avatar/FluentAvatar.md
- spelling.dic
- src/Core/Components/Avatar/FluentAvatar.razor
- src/Core/Components/Avatar/FluentAvatar.razor.cs
- src/Core/Components/Icons/Icon.cs
- src/Core/Enums/AvatarActiveAppearance.cs
- src/Core/Enums/AvatarColor.cs
- src/Core/Enums/AvatarShape.cs
- src/Core/Enums/AvatarSize.cs
- tests/Core/Components/Avatar/FluentAvatarTests.FluentAvatar_Default.verified.razor.html
- tests/Core/Components/Avatar/FluentAvatarTests.FluentAvatar_DefaultWithOnClick.verified.razor.html
- tests/Core/Components/Avatar/FluentAvatarTests.FluentAvatar_Icon.verified.razor.html
- tests/Core/Components/Avatar/FluentAvatarTests.FluentAvatar_Icon_WithSize.verified.razor.html
- tests/Core/Components/Avatar/FluentAvatarTests.razor
The `Avatar` component is used to represent a user or entity. It can display an image, initials, or an icon.
You can provide a name prop to display initials. The name prop will be used to generate the initials displayed in the Avatar.
You can provide an icon prop to replace the default icon in the Avatar when the initials or name is not provided .
Since the fluent-badge is not available in the dev-v5 branch, the component needs to be reviewed with these features to include the feature of status badge
- Appearance : Defines all appearance mode available
- Contents : Defines the way to control the content of the avatar 
- Name and initials 
- Image
- Default icon
> [dev-v5] Add FluentAvatar component

- examples/Demo/Shared/Pages/Anchor/Examples/AnchorIcons.razor
Fix typo in Anchor documentation.
Appearane => Appearance
Stat => Start
> Anchor docs

- src/Core/Components/DataGrid/Columns/SelectColumn.cs
Fix #3447 
Add extra check when selecting all items so only items that are actually selectable get selected.
> [DataGrid] Only add Selectable items when using Select All

- src/Core/Components/List/FluentCombobox.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
- tests/Core/List/FluentComboboxTests.FluentCombobox_ClearSelection.verified.html
as described in  #3416, the parameters in the list controls can no longer be updated from outside the control at the moment (selected option(s) being the one we use). this was done to fix #3297 but the boolean checks seem to not be needed?
#3416 #3297 
ive taken the example from the original issue and expanded it with the buttons to set or clear the combobox.
Im setting this as a Draft because i have no idea if this is actually a good fix and like to get some feedback if possible.
~~also FluentCombobox_ClearSelection test is failing now, which i find weird since it should now be able to clear :/~~
nvm, test was broken
```
@page "/FluentComboBox"
@using System.Linq.Expressions
<Form Model="modelTest" EnableFluentValidation=true>
<FluentCombobox
SelectedOptionChanged="@((selectedOption) => …
```
> [Lists]: don't make parameters only be set once

- src/Core/Components/CounterBadge/FluentCounterBadge.razor.cs
- tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_DotWithPositioning.verified.html
- tests/Core/CounterBadge/FluentCounterBadgeTests.FluentCounterBadge_WithPositioning.verified.html
- tests/Core/CounterBadge/FluentCounterBadgeTests.cs
- tests/Core/Search/FluentSearchTests.cs
Fix #3489. As described in the issue, the `CounterBadge` component was not using a provided `HorizontalPosition` and `VerticalPosition` but always used the default value of 60. This PR fixes that (and adds tests to verify).
Before:
After:
> [CounterBadge] Fix `HorizontalPosition`/`VerticalPosition` not being used

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridTypical.razor
- examples/Demo/Shared/Pages/DataGrid/Pages/DataGridTypicalPage.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
This PR adds a new method to the `FluentDataGrid` component that allows closing the column options UI programmatically. The new method, `CloseColumnOptionsAsync`, closes the UI that was previously displayed for a column.
The 'Typical Grid Usage' page has been updated to include the new method and handle the `Enter` key press event to close the column options UI.
_This is a copy of the method that was added to the QuickGrid component in .NET 10 (preview 2)_
> [DataGrid] Add method to close column options programmatically

- examples/Demo/Client/wwwroot/index.html
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/DataGrid/DataGridPage.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridRemoteData2.razor
- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridVirtualize.razor
- examples/Demo/Shared/wwwroot/css/site.css
- src/Core/Components/DataGrid/FluentDataGrid.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
When using `Virtualize` on a `FluentDataGrid`, the 'DisplayMode=DataGridDisplayMode.Table` should be used. 
Several fixes in styling have been applied to address the changes needed when using this `DisplayMode`.
Fixes #3485
> [DataGrid] Fix styling when using `Virtualize` with `DataGridDisplayMode.Table`

- examples/Demo/Client/Program.cs
- examples/Demo/Client/wwwroot/index.html
- examples/Demo/Server/FluentUI.Demo.Server.csproj
- examples/Demo/Server/Program.cs
- examples/Demo/Shared/Components/Cookies/CookieConsent.razor
- examples/Demo/Shared/Components/Cookies/CookieConsent.razor.cs
- examples/Demo/Shared/Components/Cookies/CookieConsent.razor.css
- examples/Demo/Shared/Components/Cookies/CookieConsent.razor.js
- examples/Demo/Shared/Components/Cookies/CookieConsentService.cs
- examples/Demo/Shared/Components/Cookies/CookieState.cs
- examples/Demo/Shared/Components/Cookies/ManageCookies.razor
- examples/Demo/Shared/Components/Cookies/ManageCookies.razor.css
- examples/Demo/Shared/Components/SiteSettingsPanel.razor
- examples/Demo/Shared/Components/SiteSettingsPanel.razor.cs
- examples/Demo/Shared/FluentUI.Demo.Shared.csproj
- examples/Demo/Shared/Infrastructure/HttpBasedStaticAssetService.cs
- examples/Demo/Shared/Infrastructure/ServiceCollectionExtensions.cs
- examples/Demo/Shared/Shared/DemoMainLayout.razor
- examples/Demo/Shared/Shared/DemoMainLayout.razor.cs
- src/Core/Utilities/JSModule.cs
This PR adds a cookie consent banner and functionality to the Demo & Documentation site, both for the (live) Wasm site and for the Server version of the site. The content and options are according to the Microsoft guidelines. 
There are three categories that can be consented to: analytic cookies, social media cookies and advertising cookies (as per the Microsoft standard) The settings following the choices made will be put in local storage. When consent is provided for analytics, the Google Analytics and Microsoft Clarity scripts will be added to the page and cookies will be written. Currently, we do not do anything with the social media and advertising consent.
`Accept` gives consent for all three categories. `Reject` does not provide consent  to any of the categories. `Manage cookies` …
> [Docs] Add cookie consent 

- src/Core.Assets/src/DesignTheme.ts
Example using 
```css
@media (prefers-color-scheme: dark) {
body:not([data-theme="light"]) {
background-color: pink;
}
}
```
A “flash” occurs during reload in “light mode”.
See #3502
> [DesignTheme] Fix the document.body.dataset.theme from the web component

- examples/Demo/Shared/Pages/Design/DesignTokensPage.razor
- examples/Demo/Shared/Pages/Design/Examples/DesignTokensDefault.razor
- examples/Demo/Shared/Pages/Lab/IssueTester.razor
- examples/Demo/Shared/wwwroot/docs/DesignTokens.md
- src/Core.Assets/src/Design/ColorsUtils.ts
- src/Core.Assets/src/DesignTheme.ts
- src/Core.Assets/src/index.ts
- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs
- src/Core/DesignTokens/DesignToken.razor.cs
- src/Core/DesignTokens/DesignTokenHelpers.cs
Fix #3511, Fix #2158
Both `AccentBaseColor` and `NeutralBaseColor` require some special handling to make it possible to assign a new color value with the `WithDefault` method. This PR adds that.
So by using the following code:
```
@using Microsoft.FluentUI.AspNetCore.Components.DesignTokens
<FluentButton @ref="ref1" @onclick=OnClickFirst>Dark/Light</FluentButton>
<FluentButton @ref="ref2" Appearance="Appearance.Accent">Accent button</FluentButton>
<FluentButton @ref="ref3">And one more</FluentButton>
<FluentButton @ref="ref4" @onclick=OnClickLast>Last button</FluentButton>
@code {
[Inject]
private BaseLayerLuminance BaseLayerLuminance { get; set; } = default!;
[Inject]
private AccentBaseColor AccentBaseColor { get; set; } = default!;
[Inject]
private NeutralBaseColor NeutralBaseColor { …
```
> [DesignTokens] Make `AccentBaseColor` and `NeutralBaseColor` work with WithDefault

- examples/Demo/Shared/Components/SiteSettingsPanel.razor
- examples/Demo/Shared/Components/SiteSettingsPanel.razor.cs
- src/Core.Assets/src/Design/ThemeStorage.ts
- src/Core.Assets/src/DesignTheme.ts
- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor
- src/Core/Components/DesignSystemProvider/FluentDesignTheme.razor.cs
- src/Core/GlobalState.cs
The `FluentDesignTheme` component (and accompanying web component) dit not support setting/getting the `NeutralBaseColor` design token yet. This PR adds that.
To demonstrate this is now possible, a color picker to change this value has been added to the Settings panel:
This allows for drastically changing the way the demo site looks...:
and
> [DesignTheme] Add support for setting/getting NuetralBaseColor

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/Icons/IconsExtensions.cs
- Update the **GetInstance** signature to `CustomIcon GetInstance(this IconInfo icon, bool? throwOnError = true)`
By default, the `throwOnError` argument is `true` to remain compatible with existing code.
- Add a new extension method `bool TryGetInstance(this IconInfo icon, out CustomIcon? result)`
Manually tested
See #3568
> [Icons] AddIconsExtensions.TryGetInstance

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/CompoundButton/FluentCompoundButton.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonDisabled.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonIcon.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonLongText.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonPressed.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonShapes.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/Examples/ToggleButtonSizes.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ToggleButton/FluentToggleButton.md
- src/Core/Components/Button/FluentButton.razor.cs
- src/Core/Components/Button/FluentToggleButton.razor
- src/Core/Components/Button/FluentToggleButton.razor.cs
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_Default.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_IconEnd.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_IconEndNoContent.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_IconOnly.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_IconStart.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_IconStartNoContent.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_Mixed.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_Pressed.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_PressedAndMixed.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_WithAppearanceAndPressedState.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.FluentToggleButton_WithIconAndPressedState.verified.razor.html
- tests/Core/Components/Button/FluentToggleButtonTests.razor
Ads the `FluentToggleButton` component
A toggle button is a two-state behavior that switches a state between on and off. A button’s rest state indicates “off” (`Pressed="false"`) while the selected state indicates “on” (`Pressed="true"`). The toggle state is in addition to the normal click behavior of a button.
> [dev-v5] Add FluentToggleButton

- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
> [Docs] Remove extra '>'

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Tabs/Examples/TabsCustomized.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Tabs/Examples/TabsDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Tabs/Examples/TabsDeferred.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Tabs/FluentTabs.md
- src/Core.Scripts/src/FluentUICustomEvents.ts
- src/Core.Scripts/src/Startup.ts
- src/Core/Components/Tabs/FluentTab.razor
- src/Core/Components/Tabs/FluentTab.razor.cs
- src/Core/Components/Tabs/FluentTab.razor.css
- src/Core/Components/Tabs/FluentTabs.razor
- src/Core/Components/Tabs/FluentTabs.razor.cs
- src/Core/Enums/TabsAppearance.cs
- src/Core/Enums/TabsSize.cs
- src/Core/Events/EventHandlers.cs
- src/Core/Events/TabChangeEventArgs.cs
- tests/Core/Components.Tests.csproj
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_Default.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_DeferredLoading-After.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_DeferredLoading-Before.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_HeaderTemplate.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_Icon.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.FluentTabs_Visible.verified.razor.html
- tests/Core/Components/Tabs/FluentTabsTests.razor
A **FluentTabs** allows people to switch between categories of related information without going to different pages. They’re are ideal for dividing content-heavy pages into distinct but related categories that are easier to process and require less scrolling. **FluentTabs** can also be used for navigation between a small set of closely related, frequently accessed pages.
For navigation beyond closely related categories, use a _FluentLink_ instead. To initiate an action, use a _FluentButton_instead.
To know which tab is selected, you can bind the `ActiveTabId` or `ActiveTab` parameter to a variable. Setting the `ActiveTabId` parameter to an initial value will set the selected tab when the component is first rendered.
A tab can be disabled by setting the `Disabled` parameter to `true`. …
> [dev-v5] FluentTabs

- src/Core/Components/DataGrid/Columns/ColumnBase.razor
If in a DataGrig: ResizableColumns="true" and Sortable="true" 
The width is wrong.
I didn't find it
In DataGridTemplateColumns.razor change the grid to:
```
<div style="height: 500px; overflow-x:auto; display:flex;">
<FluentDataGrid Items="@Data.People" RowSize="@DataGridRowSize.Medium" ResizableColumns="true">
<TemplateColumn Title="Person" Sortable="true">
<div class="flex items-center">
<nobr>
<strong>@context.LastName</strong>, @context.FirstName
</nobr>
</div>
</TemplateColumn>
<TemplateColumn Title="Bonus">
<FluentButton Appearance="Appearance.Accent" @onclick="@(() => Bonus(context))">Regular</FluentButton>
<FluentButton Appearance="Appearance.Accent" @onclick="@(() => DoubleBonus(context))">Double</FluentButton>
</TemplateColumn>
</FluentDataGrid>
</div>
```
And the error will …
> [DataGrid] Fix Width when `ResizableColumns` and `Sortable`

- src/Core/Components/NavMenu/FluentNavGroup.razor
Add code so a `FluentNavGroup` only responds (and stops propagation) to the keycodes that it should handle. Fix #3566
> [NavMenu] Add code to only respond to certain key codes

- examples/Demo/Shared/Pages/TreeView/Examples/TreeViewMultiSelect.razor
- examples/Demo/Shared/Pages/TreeView/TreeViewPage.razor
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnIndex_Descending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Ascending.verified.razor.html
- tests/Core/DataGrid/DataGridSortByTests.DataGridSortByTests_SortByColumnTitle_Descending.verified.razor.html
Add an example to generate a MultiSelect TreeView.
> [TreewView] Add MultiSelect example

- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/DataGrid/FluentDataGridCell.razor.cs
Fix #3611. Rendering gridcolumn in cell style has nothing to do with `Virtualize`. Rendering height in cell style has nothing to do with `DisplayMode`.
> [DataGrid] Fix rendering issue in Table mode

- src/Core/Components/Base/CachedServices.cs
- src/Core/Components/Base/FluentComponentBase.cs
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/Components/Tooltip/FluentTooltip.razor.cs
- tests/Core/Components/Tooltip/FluentTooltipTests.FluentTooltip_Default.verified.razor.html
- tests/Core/Components/Tooltip/FluentTooltipTests.FluentTooltip_NoTooltipProvider.verified.razor.html
- tests/Core/Components/Tooltip/FluentTooltipTests.razor
When the Tooltip parameter is used with a component (ex. `Button.Tooltip`, a tooltip is added to the Provider. But when the component is destroyed, the tooltip remains in the Provider's item lists. This PR cleans up the tooltips linked to components during the Dispose process.
100%
> [dev-v5] Fix Tooltip Parameters

- src/Core/Components/Grid/FluentGrid.razor
- src/Core/Components/Grid/FluentGrid.razor.cs
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_Default.verified.razor.html
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_Items_AllBreakpoints.verified.razor.html
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_Items_Default.verified.razor.html
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_Items_JustifyGap.verified.razor.html
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_Items_NoBreapoint.verified.razor.html
- tests/Core/Components/Grid/FluentGridTests.FluentGrid_SpacingJustify.verified.razor.html
1. Remove the incorrect `div` container to apply the **styles** and the **class** to the `fluent-grid`.
2. Set default `Spacing=0`
Fixed
> [dev-v5] FluentGrid simplifications

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Spacer/Examples/SpacerDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Spacer/Examples/SpacerHorizontalPixels.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Spacer/Examples/SpacerVertical.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Spacer/Examples/SpacerVerticalPixels.razor
Fixing warnings introduced in #3619 After building examples projects:
> Fix: Introduced warnings in the examples project 

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Field/FluentField.md
- src/Core/Components/Field/FluentField.razor.css
- src/Core/Infrastructure/DefaultStyles.cs
- tests/Core/Components/Checkbox/FluentCheckboxTests.FluentCheckbox_LabelTemplate.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Default.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_DefaultTemplate.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageIcon.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-99.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-error.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-success.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-warning.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Size-99.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Size-[empty].verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Size-large.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Size-medium.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_Size-small.verified.razor.html
- tests/Core/Components/List/FluentComboboxTests.FluentCombobox_Label.verified.razor.html
- tests/Core/Components/List/FluentSelectTests.FluentSelect_Label.verified.razor.html
- tests/Core/Components/Switch/FluentSwitchTests.FluentCheckbox_LabelTemplate.verified.razor.html
- tests/Core/Components/TextArea/FluentTextAreaTests.FluentTextArea_Default.verified.razor.html
- tests/Core/Components/TextArea/FluentTextAreaTests.FluentTextArea_LabelTemplate.verified.razor.html
- tests/Core/Components/TextInput/FluentTextInputTests.FluentInputText_Default.verified.razor.html
- tests/Core/Components/TextInput/FluentTextInputTests.FluentInputText_LabelTemplate.verified.razor.html
To allow the default margins of the **FluentField** component to be redefined, 
the `my-3-o` class has been defined (identical to `my-3` but without the `important`).
Updated: `my-3` -> `my-3-o`
> [dev-v5] Update the default class value from `my-3` to `my-3-o`

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Dialog/FluentDialog.md
[dev-v5] Add documentation detail
Add these important informations in the documentation.
> **Note:**  
> 1. The `FluentDialogBody` component is required to display the dialog window correctly.
> 2. ⚠️ If you override the `OnInitializedAsync` method, **you must call** the `base.OnInitializedAsync()` method,
>    in addition to your personalized code.
>    because it configures the Header, Footer and all Action buttons.
>    E.g.: `protected override async Task OnInitializedAsync() { await base.OnInitializedAsync(); // And your code }`
> [dev-v5] Add documentation detail

- src/Core/Components/Field/FluentField.razor
- src/Core/Components/Field/FluentField.razor.cs
- tests/Core/Components/Field/FluentFieldTests.razor
Add the `IncludeInputSlot` parameter to NOT insert a `<div slot="input" id="...">` automatically,
If the `InputComponent` is not set, you must set the `id="@Id"` and `slot="@FluentSlot.FieldInput"` parameters in YOUR input component; And next switch the  `IncludeInputSlot=false`.
```csharp
/// <summary>
/// Gets or sets a value indicating whether the <see cref="ChildContent" /> should be rendered in an extra `div slot="input"`.
/// </summary>
[Parameter]
public bool IncludeInputSlot { get; set; } = true;
/// <summary>
/// Gets or sets the child content of the field.
/// ⚠️ If the <see cref="InputComponent"/> is not set, you must set the `id="@Id"` and `slot="@FluentSlot.FieldInput"` parameters in YOUR input component.
/// </summary>
[Parameter]
public RenderFragment? ChildContent { get; …
```
> [dev-v5] Add `FluentField.IncludeInputSlot` parameter

- README.md
- examples/Demo/Shared/Pages/RebootPage.razor
- examples/Demo/Shared/wwwroot/css/site.css
- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
- src/Templates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.Web/wwwroot/app.css
- src/Templates/templates/aspire-starter/9.0/Aspire-StarterApplication.1.Web/wwwroot/app.css
- src/Templates/templates/blazorweb-csharp/BlazorWeb-CSharp/wwwroot/app.css
- src/Templates/templates/componentswebassembly-csharp/wwwroot/css/app.css
- src/Templates/templates/maui-blazor-solution/MauiApp.1.Shared/wwwroot/app.css
It is possible the leading '/' needs to be removed from the stylesheet tag if the site is being hosted with a different `BasePath` value.
Close #3674
> [Docs] Add message for when using reboot with different BasePath

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentListbox.razor.cs
- src/Core/Components/List/FluentSelect.razor.cs
This PR improves the documentation of the `FluentSelect` component by adding a clarification about the `SelectedOptionsChanged` event.
When using manual options, FluentSelect's internal data structure cannot be reliably updated. Because of that, the `SelectedOptionsChanged` callback will not be triggered.  
This is a known limitation, and we do not foresee changes to this behavior in the short term.
Fixes #3670 and #1207
- Validated that the updated note appears correctly in the FluentSelect documentation page.
- Confirmed that no visual or structural issues were introduced.
Updated documentation:
Let me know if you’d like me to include any additional details.
Thanks!
> [DOCS] - Clarify FluentSelect SelectedOptionsChanged not triggered with manual options (#3670 and #1207)

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/wwwroot/css/site.css
- src/Core/Components/Menu/FluentMenu.razor.cs
- src/Core/Components/Menu/FluentMenu.razor.js
Position menu not just based on x and y but also take screen width and height into account.
**Before:**
**After:**
Based on changes made in Aspire. Thanks @JamesNK!
Fix #3660
> [Menu] Account for screen width and height when positioning menu

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Tooltip/Examples/TooltipDefault.razor
- src/Core/Components/Tooltip/FluentTooltip.razor
- src/Core/Components/Tooltip/FluentTooltip.razor.cs
- src/Core/Components/Tooltip/FluentTooltipProvider.razor
- src/Core/Components/Tooltip/Services/TooltipOptions.cs
- src/Core/Components/Tooltip/Services/TooltipService.cs
This PR adds the `AdditionalAttributes` property to the `TooltipOptions` class in the `Microsoft.FluentUI.AspNetCore.Components.Components.Tooltip` namespace. This property allows users to set a collection of additional attributes that will be applied to the created element even when using the TooltipService. 
Fix #3689
> [Tooltip] Add AdditionalProperties when using TooltipService

- Directory.Packages.props
That's all. Only some NuGet packages updated
> [General] Use newer Markdig package

- Directory.Packages.props
- README.md
- examples/Demo/Client/wwwroot/index.html
- examples/Demo/Server/Pages/_Layout.cshtml
- examples/Demo/Shared/App.razor.cs
- examples/Demo/Shared/Pages/Design/DesignThemePage.razor
- examples/Demo/Shared/Pages/FluentComponentBasePage.razor
- examples/Demo/Shared/Pages/FluentInputBasePage.razor
- examples/Demo/Shared/Pages/FormsOverviewPage.razor
- examples/Demo/Shared/Pages/Home/Home.razor
- examples/Demo/Shared/wwwroot/docs/CodeSetup.md
- examples/Demo/Shared/wwwroot/docs/DesignTokens.md
- examples/Demo/Shared/wwwroot/docs/ProjectSetup.md
- examples/Demo/Shared/wwwroot/docs/Templates.md
- examples/Demo/Shared/wwwroot/docs/WhatsNew-Archive.md
- src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
- src/Templates/Microsoft.FluentUI.AspNetCore.Templates.csproj
Avoid using the term 'Blazor components' as that is not how its is used in the official docs. Addresses #3702
> [Docs] Try to use more correct terminology

- src/Core/Components/Field/FluentField.razor.cs
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageIcon.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-99.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-error.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-success.verified.razor.html
- tests/Core/Components/Field/FluentFieldTests.FluentField_MessageState-warning.verified.razor.html
The default style depended on the presence of a Message condition. This is an error and can cause undesirable behavior. Only the condition on the Label is retained.
Before
After
> [dev-v5] Fix the FluentField DefaultStyles

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Highlighter/Examples/HighlighterDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Highlighter/Examples/HighlighterDelimiters.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Highlighter/FluentHighlighter.md
- src/Core/Components/Highlighter/FluentHighlighter.razor
- src/Core/Components/Highlighter/FluentHighlighter.razor.cs
- src/Core/Components/Highlighter/HighlighterSplitter.cs
- tests/Core/Components/Base/ComponentBaseTests.cs
- tests/Core/Components/Highlighter/FluentHighlighterTests.razor
- Copy of the v4 FluentHighlighter component
- Refactoring to solve naming convention issues
- Add doc
- Add Unit Tests
> [dev-v5] FluentHighlighter

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Autocomplete/AutocompletePage.razor
- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteCloseViaCode.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_CloseManually-DropdownOpened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_CloseManually.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.razor
This PR introduces the ability to close the dropdown of a `FluentAutoComplete` in code.  There could be others but my use-case is that I have a button in the 'Footer' of the dropdown that allows a user to open up a more advanced dialog for searching for a result (shows a grid).  When this button is pressed, a dialog is opened but because the dropdown of the autocomplete is still open, it displays over the dialog.  Here is a screen capture of that happening:
Run the demo project and go to the `Autocomplete` page. Then go to the `Close via code` section, invoke the dropdown and then click on the button in the footer.
Here is an example of it working:
> Autocomplete - close the dropdown via code

- Directory.Packages.props
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Localization.md
- spelling.dic
- src/Core/Components/Base/FluentInputBase.cs
- src/Core/Components/Layout/FluentLayoutHamburger.razor.cs
- src/Core/Extensions/DateTimeExtensions.cs
- src/Core/Localization/LanguageResource.resx
- src/Core/Localization/ReadMe.md
- src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj
- src/Core/Utilities/DateTime/DateTimeProvider.cs
- src/Core/Utilities/DateTime/DateTimeProviderContext.cs
- src/Core/Utilities/DateTime/ReadMe.md
- tests/Core/Extensions/DateTimeExtensionsTests.cs
- tests/Core/Extensions/DateTimeExtensionsToTimeAgoTests.cs
- tests/Core/Utilities/DateTimeProviderTests.cs
1. Add a **DateTimeProvider** and **DateTimeProviderContext**
See the **ReadMe.md** documentation in the **Utilities/DateTime** folder.
> To simplify the possibility to unit test a current Date Time,
> we propose a solution that uses the **Ambient Context Model**.
>
> To do this, use a `DateTimeProvider` class that determines the current date:
> the default `DateTime.Now` is replaced by `DateTimeProvider.Now` in the code.
>
> Example:
> ```csharp
> int GetQuarter()
> {
>     return (DateTimeProvider.Today.Month - 1) / 3 + 1;
> }
> ```
>
> This **provider** returns the system's current date. However, by using it in a unit test, 
> we can adapt the context to specify a predefined (fake / fixed) date.
> 
> ```csharp
> var fakeDate = new DateTime(2018, 5, 26);
> using (var context = new …
```
> [dev-v5] Add DateTimeProvider and DateTimeExtensions

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
This PR introduces a new Position parameter to the FluentAutocomplete component. The new parameter allows developers to control the positioning of the autocomplete dropdown.
```
/// <summary>
/// Gets or sets the vertical default position of the options popup.
/// </summary>
[Parameter]
public VerticalPosition Position { get; set; } = VerticalPosition.Unset;
```
The AutocompletePosition enum includes two options:
**The VerticalPosition enum includes the following options:**
- Top: Displays the dropdown above the input.
- Bottom (default): Displays the dropdown below the input.
- Center: Aligns the dropdown centrally.
- Unset: No positioning specified (default fallback behavior).
**Why this change?**
With this enhancement, developers can now dynamically control the dropdown position based …
> [AutoComplete] - Introduce Position parameter.

- src/Core/Components/InputFile/FluentInputFile.razor.css
This PR fixes the missing focus indicator in `FluentInputFile`.
Before:
After:
Fixes #3693
This issue is being caused by the input field having `opacity` set to `0`. This results in the UI not showing any focus borders. This PR fixes this by giving the parent container the corresponding outline.
> [InputFile] [a11y] Fix missing focus indicator in FluentInputFile (#3693)

- src/Core.Assets/src/index.ts
- src/Core/wwwroot/css/reboot.css
`FluentButton` hasn't been adopting text spacing correctly. This PR fixes this.
Before:
After:
Fixes #3692
> [a11y] Fix certain controls not adapting text spacing (#3692)

- src/Core/Components/List/FluentCombobox.razor
- src/Core/Components/List/FluentCombobox.razor.cs
- tests/Core/List/FluentComboboxTests.FluentCombobox_ClearSelection.verified.html
The correct `GetOptionValue` is already included in the `ListComponentBase` class.
```csharp
// From ListComponentBase
protected virtual string? GetOptionValue(TOption? item)
{
if (item != null)
{
return OptionValue?.Invoke(item) ?? OptionText?.Invoke(item) ?? item?.ToString();
}
else
{
return null;
}
}
```
#3734
> Fix combobox GetOptionValue

- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fix #3742 by not handeling the arrow keys when the active element is a `FluentTextField`
> [DataGrid] Do not handle keypress if active element is text field

- src/Core/Components/ProfileMenu/FluentProfileMenu.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.cs
- tests/Core/ProfileMenu/FluentProfileMenuTests.razor
Add an `OpenChanged` event and add the possibility to bind the `Open` parameter.
See #3486
Updated
> [ProfileMenu] Add OpenChanged event

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/TextArea/Examples/TextAreaChangeAfterKeyPress.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/TextArea/FluentTextArea.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/TextInput/Examples/TextInputChangeAfterKeyPress.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/TextInput/FluentTextInput.md
- src/Core.Scripts/src/ExportedMethods.ts
- src/Core.Scripts/src/Utilities/KeyPress.ts
- src/Core/Components/Base/IFluentComponentChangeAfterKeyPress.cs
- src/Core/Components/KeyCode/FluentKeyPressEventArgs.cs
- src/Core/Components/KeyCode/KeyPress.cs
- src/Core/Components/TextArea/FluentTextArea.razor.cs
- src/Core/Components/TextInput/FluentTextInput.razor.cs
- tests/Core/Components/TextArea/FluentTextAreaTests.razor
- tests/Core/Components/TextInput/FluentTextInputTests.razor
In the example of a command area or search text area, you can use the `ChangeAfterKeyPress` parameter to trigger the `OnChange` event
after a specific key or keys are pressed. E.g. `Enter`, `Escape`, `Tab`, `Ctrl+Enter`, etc.
You can capture the content of the text area from the `Value` parameter.
An `OnChangeAfterKeyPress` event is also triggered when the user presses these key combinations.
This also gives you the key used to trigger the event (this can be useful when you allow multiple key combinations).
```razor
<FluentTextArea  @bind-Value="@ChatInput"
ChangeAfterKeyPress="@([KeyPress.For(KeyCode.Enter).AndCtrlKey(), KeyPress.For(KeyCode.Enter)])"
OnChangeAfterKeyPress="@StartChatDiscussion" />
@code
{
string ChatInput = string.Empty;
async Task …
```
> [dev-v5] Add ChangeAfterKeyPress parameter (TextInput and TextArea)

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/InputFile/InputFilePage.razor
- src/Core/Components/InputFile/FluentInputFile.razor.cs
This PR adds additional details to the `InputFile` docs to explain to the user when he/she should use which `InputFileMode`.
#3355
> [Docs] Update InputFile docs to explain usage of different InputFileModes

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Dialog/FluentDialog.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/List/Combobox/DebugPages/DebugCombobox.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/List/Combobox/DebugPages/DebugComboboxDialog.razor
- src/Core/Components/Dialog/FluentDialog.razor.cs
- tests/Core/Components/Dialog/FluentDialogTests.razor
When a **ComboBox** is used in a **DialogBox**, the HTML toggle event of the **ComboBox** is detected by the **DialogBox**. And the **DialogBox** is closed.
A new test `if (string.CompareOrdinal(args.Id, Instance?.Id) != 0)` can check if the correct toggle is detected.
Before
After
Add a `DebugPages/DebugCombobox.razor` page to validate tricky features (page not included in the documentation)
Updated to specify the correct ID
> [dev-v5] Fix a Combobox in a DialogBox

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/InputFile/FluentInputFile.md
- src/Core/Components/InputFile/FluentInputFile.razor.cs
This PR adapts the changes for the `FluentInputFile` documentation for v5 from #3757
Fixes: #3764
> [Docs] [dev-v5] Adapt changes to InputFile docs (#3764)

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Dialog/FluentDialog.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Dialog/FluentDrawer.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Field/FluentField.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Layout/FluentLayout.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Tabs/FluentTabs.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Localization.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Migration/CopilotInstructionsContent.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Migration/MigrationFluentProgressRing.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Styles.md
- examples/Tools/FluentUI.Demo.DocViewer/Components/MarkdownViewer.razor.css
- examples/Tools/FluentUI.Demo.DocViewer/Models/Section.cs
Now we can use these shortcuts to be coherent with the Microsoft learn pages (see an example [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/main-command-line).
```
> [!NOTE]
> My note
> [!TIP]
> My tip
>[!WARNING]
> My warning
```
> [dev-v5] Add markdown shortcuts [!NOTE], [!TIP] and [!WARNING]

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Progress/Examples/ProgressBarVisible.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Progress/Examples/SpinnerVisible.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Progress/FluentProgressBar.md
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Progress/FluentSpinner.md
- src/Core/Components/Progress/FluentProgressBar.razor
- src/Core/Components/Progress/FluentProgressBar.razor.cs
- src/Core/Components/Progress/FluentSpinner.razor
- src/Core/Components/Progress/FluentSpinner.razor.cs
- tests/Core/Components/Progress/FluentProgressBarTests.razor
- tests/Core/Components/Progress/FluentSpinnerTests.razor
> The ProgressBar component was used with the Visible property. However, when this property is set to False, the component is not rendered, and no empty space is included in the HTML. This results in a flickering effect when the progression is running or not
The `Visible` parameter can be used to show or hide the progress bar.
This parameter is nullable:
- If `true` (default), the component is visible.
- If `false`, the component is hidden.
- If `null`, the component is hidden and not rendered.
100%
> [dev-v5] Update the ProgressBar.Visibility

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/InputFile/Examples/InputFileDialogService.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/InputFile/FluentInputFile.md
- src/Core/Components/Dialog/FluentDialogProvider.razor
- src/Core/Components/Dialog/InputFile/DialogService.cs
- src/Core/Components/Dialog/InputFile/IDialogService.cs
- src/Core/Components/Dialog/InputFile/InputFileInstance.cs
- src/Core/Components/Dialog/InputFile/InputFileOptions.cs
- src/Core/Components/InputFile/FluentInputFile.razor.cs
- src/Core/Components/InputFile/IInputFileOptions.cs
- tests/Core/Components/Dialog/FluentDialogTests.razor
- tests/Core/Components/InputFile/FluentInputFileDialogServiceTests.FluentInputFile_DialogService_Register.verified.razor.html
- tests/Core/Components/InputFile/FluentInputFileDialogServiceTests.razor
- tests/Core/Components/TextArea/KeyPressTests.cs
A easy way to open the file selection dialog is to use the injected **DialogService** service.
1. During the `OnInitialized` method, **register** your trigger HTML element 
using the method `MyFileInstance = DialogService.RegisterInputFileAsync(id)`.
1. Set the `OnCompletedAsync` method to handle the files uploaded.
1. Don't forget to **unregister** the trigger element in the `Dispose` method 
using `MyFileInstance.UnregisterAsync();` or `DialogService.UnregisterInputFileAsync(id)`.
```xml
<FluentButton Id="MyButton">Upload files</FluentButton>
```
```csharp
[Inject]
public IDialogService DialogService { get; set; }
protected override async Task OnInitializedAsync()
{
await DialogService.RegisterInputFileAsync("MyButton", OnCompletedAsync, options => { /* ... */ });    
}
private Task …
```
> [dev-v5] Add DialogService.RegisterInputFileAsync

- src/Core/Components/List/FluentAutocomplete.razor
> [AutoComplete] Do not show previous/next when no option is selected

- src/Core/Components/List/FluentAutocomplete.razor.css
This PR addresses the different default height behaviour for `FluentAutoComplete` when `MaxAutoHeight` is set to `true`
Before:
After:
Fixes: #3793
The movement below the component is happening because the wrapped tags need some padding.
I've tested this changes in Firefox, Edge, Chrome and Safari.
> [AutoComplete] Fix using different height for MaxAutoHeight (#3793)

- examples/Demo/Shared/Pages/List/Autocomplete/Examples/AutocompleteCloseViaCode.razor
This PR removes the Autofocus from one of the Autocomplete examples to prevent scrolling within the documentation page.
Fixes #3826
> [Docs] Remove Autofocus to prevent scrolling in the docs (#3826)

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Layout/FluentLayout.md
- examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Installation.md
1. Add **FluentLayout** note
2. Add a new **Installation** page containing all manual steps
> [dev-v5] Add Installation documentation

- examples/Demo/Shared/Pages/Card/CardPage.razor
Fix typo in Card documentation
> [Docs] Fix typo: exmple

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ErrorBoundary/Examples/FluentErrorBoundayDefault.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/ErrorBoundary/FluentErrorBoundary.md
- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor
- src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor
- src/Core/Components/ErrorBoundary/FluentErrorBoundary.razor.cs
- src/Core/Enums/ErrorBoundaryDetails.cs
- src/Core/Localization/LanguageResource.resx
- tests/Core/Components/ErrorBoundary/Components/ThrowingExceptionComponent.razor
- tests/Core/Components/ErrorBoundary/FluentErrorBoundaryTests.FluentErrorBoundary_WithException.verified.razor.html
- tests/Core/Components/ErrorBoundary/FluentErrorBoundaryTests.razor
The **FluentErrorBoundary** component is used to catch errors in a component tree and display a fallback UI instead of crashing the entire application.
_Error boundaries_ provide a convenient approach for handling exceptions.
The **FluentErrorBoundary** component:
- Renders its child content when an error hasn't occurred.
- Renders error UI when an unhandled exception is thrown by any component within the error boundary.
To define an error boundary, use the **FluentErrorBoundary** component to wrap one or more other components.
The error boundary manages unhandled exceptions thrown by the components that it wraps.
See [the Blazor handle errors using the error boundaries feature](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/handle-errors#error-boundaries) for more details. …
> [dev-v5] Add FluentErrorBoundary

- src/Core/Components/MainLayout/FluentMainLayout.razor
- src/Core/Components/MainLayout/FluentMainLayout.razor.cs
- tests/Core/_ToDo/MainLayout/FluentMainLayoutTests.FluentMainLayout_Default.verified.html
- tests/Core/_ToDo/MainLayout/FluentMainLayoutTests.cs
Fix #3836
Removed header height reductions from `Mainlayout`, added a vertical stack.
Stacks now always have 100% height.
I've kept the `--header-height` variable as it might be used by some users already.
#3836 
I think we should take cases in consideration when the navigation or main content exceeds the 100%.
We can either re-add the subtraction to the vertical stack and add a parameter to the component `SubHeaderHeight` and subtract this from the horizontal stack. 
Or we can let the user define the styles for these stacks themselves.
Added test to check default styles of mainlayout stacks
> [MainLayout] Remove double header reduction

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Card/Examples/CardAppearanceExample.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Card/Examples/CardClickable.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Card/Examples/CardShadowExample.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Card/Examples/CardTemplatePowerpoint.razor
- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Card/FluentCard.md
- src/Core/Components/Card/FluentCard.razor
- src/Core/Components/Card/FluentCard.razor.cs
- src/Core/Components/Card/FluentCard.razor.css
- src/Core/Enums/CardAppearance.cs
- src/Core/Enums/CardShadow.cs
- tests/Core/Components/Card/FluentCardTests.razor
A **FluentCard** is a container that holds information and actions related to a single concept or object, like a document or a contact.
Cards can give information prominence and create predictable patterns.
While they're very flexible, it's important to use them consistently for particular use cases across experiences.
By default, each card is of `role="group"`.
> The following features come from the [React Card](https://react.fluentui.dev/?path=/docs/components-card-card--docs#appearance) component.
> Other properties will be included when the WebComponent is complete.
Cards can have different styles depending on the situation and where it is placed.
Cards can have shadows to create a sense of depth and separation from the background.
Adding a `OnClick` handler to a card will make it …
> [dev-v5] FluentCard

- examples/Demo/Shared/Pages/DataGrid/Examples/DataGridCustomHeader.razor
- examples/Demo/Shared/Pages/DataGrid/Pages/DataGridColumnHeaderGenerationPage.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor
- src/Core/Components/DataGrid/Columns/ColumnBase.razor.cs
Adds a `HeaderCellTitleTemplate` property to the `ColumnBase` type of `FluentDataGrid`.  This allows users to customize the column header text beyond just text, but without having to take ownership of the resize/sort/filter column options UX required when using the `HeaderCellTemplate` property.  If not set, then the column `Title` is displayed as plain text as before.
A new section of the guide/docs site was added to demonstrate this new feature.
* #3850
There doesn't seem to be any existing unit/integration tests related to `FluentDataGrid` header generation, so testing of this change has been ad-hoc, mostly via the generated docs page.
> Add `HeaderCellTitleTemplate` to `DataGrid` `ColumnBase`

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Menu/MenuPage.razor
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
Refine the logic that determines if the DataGrid data needs to be reloaded by implementing a hash calculation on the data. To limit the effect on performance, the hash will only be computed for the given maximum number of items, which is set to 250 by default.
Fix #3847
> [DataGrid] Refine logic that determines if the DataGrid data needs to be reloaded

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/DataGrid/Columns/SelectColumn.cs
When all rows are selected in a DataGrid with a `SelectColumn` (Multiple=true), the header checkbox would always select all items first. An extra click was then needed to deselect all items. This PR extends the logic to deselect all items if all items are already selected.
Fix #3845
> [DataGrid] Make Select/Deselect all more robust

- src/Core/Components/DataGrid/FluentDataGrid.razor.js
Fix #3888 by not adding `position: relative`. It is already defined in header class and there are situations it needs to be overridden (sticky header)
> [DataGrid] Fix header not being sticky in certain situations

- src/Core/Components/List/FluentAutocomplete.razor
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_AutofocusAttribute.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Empty.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_InvokeSearchOptions.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowDown.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-ArrowUp.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Backspace.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Keyboard-Escape.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_MaxAutoHeight_Opened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_MultipleEqualsFalse.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Name.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClearWithOverlayHiddenOnEmpty_HasNoOverlay.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_OnClear_ShowOverlay.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Opened.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_OnDismissClick.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_SelectedOptions_Template.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Templates.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_ValueText_Clears.verified.razor.html
- tests/Core/List/FluentAutocompleteTests.FluentAutocomplete_Width_Empty.verified.razor.html
This PR removes the conditonal check for the placeholder within `FluentAutocomplete`. This results in the `Placeholder` property only being rendered when it is actually supplied.
I've updated all unit tests to remove the empty placeholder attribute as well.
Fixes #3916
> [AutoComplete] Only render placeholder attribute when the parameter is provided

- src/Core/Components/List/FluentAutocomplete.razor
- src/Core/Components/List/FluentAutocomplete.razor.cs
- src/Core/Components/List/ListComponentBase.razor.cs
1. Allow an item to be deselected using the `Delete` or `Backspace` keys.
2. Update the **SelectableItem** item to get the first “not disabled” item.`
In this example, all items are selected using the keyboard only (arrows, Delete, Backspace keys)
No change
> [Autocomplete] Fix keyboard usage in Single mode

- tests/Core/Components/Base/ComponentBaseTests.cs
In the global Base Unit Tests:
1. Add a new `WithCascadingValue` method
Example to use that:
```csharp
{ typeof(FluentDataGrid<>), Loader.MakeGenericType(typeof(string)) },
{ typeof(FluentDataGridRow<>), Loader.MakeGenericType(typeof(string)).WithCascadingValue(new InternalGridContext<string>(new FluentDataGrid<string>(new LibraryConfiguration()))) },
{ typeof(FluentDataGridCell<>), Loader.MakeGenericType(typeof(string))
.WithCascadingValue(new InternalGridContext<string>(new FluentDataGrid<string>(new LibraryConfiguration())))
.WithCascadingValue("OwningRow", new FluentDataGridRow<string>(new LibraryConfiguration()) { InternalGridContext = new InternalGridContext<string>(new FluentDataGrid<string>(new LibraryConfiguration())) }) },
```
3.  Refactoring the creation of an array
> [dev-v5] Base Unit Tests - Add WithCascadingValue method and refactoring

- examples/Demo/Shared/Pages/Accordion/Examples/AccordionDefault.razor
This fixes a mismatch between the description in the content of the second accordion and the actual code.
There is no html button in the code.
The issue was located on the default accordion documentation page.
Before:
After:
> [Docs] Fix mismatch in accordion docs between the code and the description.

- src/Core/Components/List/FluentSelect.razor.cs
- tests/Core/List/FluentSelectTests.FluentSelect_Placeholder.verified.razor.html
This PR changes the CSS variable which is being used to set the text color for the placeholder in `FluentSelect`.
Every other input uses `--input-placeholder-rest` for the text color. `FluentSelect` has been using `--neutral-base-color` before which has a slight darker gray tone.
Before:
After:
I have updated the `FluentSelectTests.FluentSelect_Placeholder.verified.razor.html` unit test to reflect this change.
- [] I have updated the project documentation to reflect my changes.
> [Select] Use correct CSS variable for placeholder color

- examples/Demo/Shared/Pages/DateTimes/Examples/TimePickerDefault.razor
- src/Core/Components/DateTime/FluentTimePicker.razor
- src/Core/Components/DateTime/FluentTimePicker.razor.cs
- src/Core/Components/DateTime/FluentTimePicker.razor.js
- src/Core/Enums/TimeDisplay.cs
1. Fix the internal time format when another culture is used.
2. Add a `TimeDisplay` to display the seconds
```razor
<FluentTimePicker @bind-Value="@SelectedValue" Label="Meeting time:" />
<FluentTimePicker @bind-Value="@SelectedValue" Label="With seconds:" TimeDisplay="@TimeDisplay.HourMinuteSeconds" />
<p>Selected Time: @(SelectedValue?.ToString("HH:mm:ss"))</p>
@code
{
private DateTime? SelectedValue = null;
}
```
> Fix the Time format when another culture is used, and add TimeDisplay enum

- src/Core/Components/Layout/FluentLayoutItem.razor.css
I saw a small bug in the demo for the migration changes, when the list of the sidepanel is too large to fit the screen, it will cause the entire layout to move up a little bit, even blow the footer. I will provide a screen shot of it down below. 
Now with an additional style, telling it to grow to whatever is available, but never larger then fit-content
Also, i just noticed that before it didnt give a scrollable view for the side panel. 
Just a small fix :)
> [dev-v5] Small styling fix

- examples/Demo/FluentUI.Demo.Client/Layout/DemoNavMenu.razor.css
This PR makes switches the anchor elements within the navigation in the v5 demo to block elements to allow the user to click on the entire block instead of the text only.
> [dev-v5] Make anchors block elements

- src/Core/Components/Slider/FluentSlider.razor.cs
- tests/Core/Components/Slider/FluentSliderTests.razor
The **FluentSlider** sends a value change using the JS function `onchange`, but as an ‘oninput’ event: immediately after the cursor is moved. The delay in communicating with the Blazor server and updating the `value` attribute is therefore too long, which causes a loop.
We added a new parameter `ImmediateDelay` (default 60ms) to "debounce" the value.
> A future fix will use a JavaScript Debounce object to avoid sending the value from the client when it is not required.
See #3979
> [dev-v5] Fix Slider - add ImmediateDelay

- src/Core/Components/Toast/ContentComponents/CommunicationToast.razor.cs
- src/Core/Components/Toast/ContentComponents/ConfirmationToast.razor.cs
- src/Core/Components/Toast/ContentComponents/ProgressToast.razor.cs
This pull request introduces changes to enhance compatibility with trimming tools by adding `DynamicDependency` attributes to several toast components. These changes ensure that the public constructors of the components are preserved during trimming.
* [`src/Core/Components/Toast/ContentComponents/CommunicationToast.razor.cs`](diffhunk://#diff-8006d745de9bb35cabdf9820848aa19816712c6fc1a2e26cdc3df9ce82648733R5-R11): Added a `[DynamicDependency]` attribute to preserve public constructors of the `CommunicationToast` class during trimming.
* [`src/Core/Components/Toast/ContentComponents/ConfirmationToast.razor.cs`](diffhunk://#diff-cc625a3374bb5cd698fa6d248a3a0823301803ce25fd541254c200f4f25abd74R1-R13): Introduced a new `ConfirmationToast` class with a `[DynamicDependency]` attribute to …
> [Toast] Add DynamicDependency to prevent trimming errors

- .github/ISSUE_TEMPLATE/bug-report.md
Add more comments to indicate we **must have** 'ready-to-run' reproduction code
Added text:
We expect you to provide steps to reproduce the issue and/or a code repository, gist, code snippet or sample files 
THIS MUST BE 'READY-TO-RUN' code
Can be something we can copy/paste on a page, a repository with a minimal project or a zipped project we can download
As long as we do not need to change anything to reproduce the problem, anything is fine 
If no code is provided or we cannot run the code without any alterations, the issue will get closed
> [General] Update the issue template

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/Tabs/Examples/TabsDefault.razor
- src/Core/Components/Tabs/FluentTab.razor.css
- src/Core/Components/Tabs/FluentTabs.razor.cs
This is a proper fix for #3325 
Default sample has been adapted to allow for sizing option:
`TabSize` default is changed from `Medium` to `Small` but as it was not working before anyway expected impact should be minimal.
> [Tabs] Implement proper tab sizing

- src/Core/DesignTokens/DesignToken.razor.cs
Fix #4004.  We already use the `[DynamicDependency]` attribute in the `DesignToken` class. Except it was only placed on the default constructor...
For v4.12.1, we are adding it to the non-default constructor as well. I've confirmed it is working now in the emulator:
(before adding the code to the constructor, I got the error with a release build on the emulator as well)
> [MAUI] Add DynamicDependency to right DesignTokenconstructor

- README.md
Add a notice in the README about potential certificate renewal issues for the demo website and provide a backup site for users encountering problems.
> Update README with demo website certificate notice

- docs/contributing.md
This PR updates the mentioned NodeJS version in the contributing.md and fixes an issue with displaying a note.
I'm having this version installed as well and I have no issues compiling the repository.
> [Docs] Update NodeJS version and fix note

- src/Core/Components/KeyCode/FluentKeyCode.razor.cs
- src/Core/Components/KeyCode/FluentKeyCode.razor.js
Fixes JSException being thrown in `DIsposeAsync` in `FluentKeyCode`.
Fix: #4087
> [FluentKeyCode] Fix DisposeAsync issue in MAUI

- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
- tests/Core/PropertyColumn/PropertyColumnFormatterTests.razor
- tests/Core/PropertyColumn/PropertyColumnFormatterTests.razor.cs
This pr will remove the TODO from the property column about boxing value types when using a format.
Added test cases for each type of format (nullable value types, value types and reference types).
Also added test to check if exception is thrown.
> [Property Column] Remove boxing when formatting the property.

- src/Core/Components/DataGrid/Columns/PropertyColumn.cs
- src/Core/Components/DataGrid/FluentDataGrid.razor.cs
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor
- src/Core/Components/ProfileMenu/FluentProfileMenu.razor.cs
- src/Core/Components/Splitter/FluentMultiSplitter.razor.cs
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_Customized.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_Default.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.FluentProfileMenu_StartEndTemplate.verified.razor.html
- tests/Core/ProfileMenu/FluentProfileMenuTests.razor
This PR adds a tabindex and key handling to the root element (div) of the ProfileMenu. Fix #4091 
Also added a test for this new functionality and fixed 2 code analyzer errors
> [ProfileMenu] Toggle open on enter/space key press

- src/Core.Assets/src/index.ts
This PR fixes the active indicator size on mobile devices for
- FluentTextArea
- FluentTextField
- FluentSearch
- FluentComboBox
- FluentNumberField
Before:
After:
Fix #4073
This was only really visible on touch devices.
> [Inputs] Fix wrong active size for mobile devices

- .github/workflows/build-core-lib.yml
- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- examples/Demo/Shared/Pages/List/Listbox/Examples/ListboxManual.razor
- examples/Demo/Shared/Pages/List/Select/Examples/SelectDefault.razor
- src/Core/Components/List/FluentOption.razor
- src/Core/Components/List/FluentOption.razor.cs
- src/Core/Components/List/ListComponentBase.razor
- src/Core/Components/List/ListComponentBase.razor.cs
**FluentSelect** has an issue where it is hard to see long item content.
This becomes a problem when there are multiple long values that start the same. 
It's impossible to tell them apart.
See #4136
We added this new attribute to defined when and what to display in the `FluentOption.Title` attribute
```xml
<FluentSelect OptionValue="@(p => p.PersonId.ToString())"
OptionText="@(p => p.LastName + ", " + p.FirstName)"
OptionTitle="@(p => p.LastName.Length + p.FirstName.Length > 20 ? p.LastName : null)" />
´´´
```csharp
/// <summary>
/// Gets or sets the function used to determine the option tooltip (title).
/// If null is returned, then no title is displayed.
/// </summary>
[Parameter]
public virtual Func<TOption, string?>? OptionTitle { get; set; }
```
No changes
> [List] Add an `OptionTitle` attribute

- src/Core/Components/Toast/FluentToast.razor
- src/Core/Components/Toast/FluentToast.razor.cs
- src/Core/Components/Toast/Parameters/IToastParameters.cs
- src/Core/Components/Toast/Parameters/ToastParameters.cs
Add Class & Style parameters to the FluentToast component, via ToastParameters.
> [FluentToast] Add Class & Style properties

- examples/Demo/FluentUI.Demo.Client/Documentation/Components/Theme/Dark/ThemeDark.md
- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor
- examples/Demo/FluentUI.Demo.Client/Layout/DemoMainLayout.razor.cs
- src/Core.Scripts/src/Startup.ts
- src/Core.Scripts/src/Utilities/Theme.ts
The theme is automatically managed by Fluent UI Blazor when the application is first loaded (Startup).  
You can force a specific theme by directly adding the attribute `data-theme="dark"` or `data-theme="light"`
in the `<body>` tag of your `index.html` or `_Host.cshtml` file.
We also added a JavaScript function `Blazor.theme.switchTheme` to simplify the switch from light/dark mode.
The theme does not update by default when the user changes the system or browser theme, and it is not saved across sessions.
You can listen to the `themeChanged` event to implement your own logic, such as saving the user's preference in local storage or cookies.
Or to automatically switch themes based on system preferences.
No changes
> [dev-v5] Keep a predefined dark/light theme

- examples/Demo/Shared/Microsoft.FluentUI.AspNetCore.Components.xml
- src/Core/Components/MenuButton/FluentMenuButton.razor
- src/Core/Components/MenuButton/FluentMenuButton.razor.cs
Fix #4214 by adding the `UseMenuService` parameter. Internally its value will be used by the Menu component
> [MenuButton] Add `UseMenuService` parameter to configure Menu
